/**
 * 관리자 통계 대시보드 (`/admin/stats`) 디자인 계약.
 *
 * 추출 기준: `docs/00_assets/admin/prototype.html` L790~900 (STATS 블록) · 2026-09-16 A6.
 * 서버 렌더 SVG (createBarChart / createDonutChart) 이식 결과 검증.
 */

import type { ScreenContract } from './types';

export const adminStatsContract: ScreenContract = {
    screen: 'admin-stats',
    path: '/admin/stats',
    source: 'admin/prototype.html L790~900 · 2026-09-16 A6',
    viewport: { width: 1440, height: 900 },
    checks: [
        // ── 헤더 GNB stats 활성 ──────────────────────────────
        {
            id: 'gnb.stats.active',
            desc: '통계 GNB 링크 활성 상태',
            selector: '.admin-header-nav a.admin-nav-link.active',
            kind: 'text',
            expected: '통계',
            proto: 'header.html A6 GNB 추가',
            severity: 'P0',
        },
        // ── KPI 카드 4개 ─────────────────────────────────────
        {
            id: 'kpi.count',
            desc: 'KPI 카드 4개',
            selector: '.admin-stat-card',
            kind: 'count',
            expected: 4,
            proto: 'html L790~900 + dashboard stat-grid 재사용',
            severity: 'P0',
        },
        {
            id: 'kpi.visitor30.label',
            desc: '첫 KPI 카드 = 최근 30일 방문자',
            selector: '.admin-stat-card:nth-child(1) .admin-stat-card-label',
            kind: 'text',
            expected: '최근 30일 방문자',
            proto: 'Qn-9 KPI 증감 = 30일 대비',
            severity: 'P0',
        },
        // ── Visitor chart card ──────────────────────────────
        {
            id: 'chart.card.exists',
            desc: '방문자 차트 카드 렌더',
            selector: '.admin-stats-chart-card',
            kind: 'exists',
            expected: true,
            proto: 'html L795',
            severity: 'P0',
        },
        {
            id: 'chart.title.text',
            desc: '방문자 차트 타이틀',
            selector: '.admin-stats-chart-title',
            kind: 'text',
            expected: '방문자 현황',
            proto: 'html L798',
            severity: 'P0',
        },
        {
            id: 'chart.title.font-size',
            desc: '방문자 차트 타이틀 폰트 15',
            selector: '.admin-stats-chart-title',
            kind: 'css',
            prop: 'font-size',
            expected: '15px',
            proto: 'html L798 font-size:15',
            severity: 'P1',
        },
        {
            id: 'chart.tabs.count',
            desc: '월별/연도별 탭 2개',
            selector: '.admin-stats-chart-tab',
            kind: 'count',
            expected: 2,
            proto: 'html L802~803',
            severity: 'P0',
        },
        {
            id: 'chart.tab.month.text',
            desc: '탭 1 = 월별',
            selector: '.admin-stats-chart-tab:nth-child(1)',
            kind: 'text',
            expected: '월별',
            proto: 'html L802',
            severity: 'P0',
        },
        {
            id: 'chart.tab.year.text',
            desc: '탭 2 = 연도별',
            selector: '.admin-stats-chart-tab:nth-child(2)',
            kind: 'text',
            expected: '연도별',
            proto: 'html L803',
            severity: 'P0',
        },
        {
            id: 'chart.svg.exists',
            desc: '방문자 SVG 렌더 (서버 렌더)',
            selector: '.admin-stats-chart-svg svg',
            kind: 'exists',
            expected: true,
            proto: 'Qn-1 서버 SVG · createBarChart 이식',
            severity: 'P0',
        },
        {
            id: 'chart.summary.count',
            desc: '차트 하단 요약 3셀',
            selector: '.admin-stats-chart-summary-cell',
            kind: 'count',
            expected: 3,
            proto: 'html L807~819',
            severity: 'P0',
        },
        // ── Program stats table ─────────────────────────────
        {
            id: 'program.card.exists',
            desc: '프로그램별 참여 현황 카드',
            selector: '.admin-stats-program-card',
            kind: 'exists',
            expected: true,
            proto: 'html L824',
            severity: 'P0',
        },
        {
            id: 'program.title.text',
            desc: '프로그램별 참여 타이틀',
            selector: '.admin-stats-program-card .admin-stats-section-title',
            kind: 'text',
            expected: '프로그램별 참여 현황',
            proto: 'html L825',
            severity: 'P0',
        },
        {
            id: 'program.head.columns',
            desc: '테이블 헤더 컬럼 7개',
            selector: '.admin-stats-program-row--head > span',
            kind: 'count',
            expected: 7,
            proto: 'html L829~836',
            severity: 'P0',
        },
        // ── Gender / Age donuts ─────────────────────────────
        {
            id: 'donut.row.count',
            desc: '도넛 카드 2개 (성별 · 연령)',
            selector: '.admin-stats-donut-card',
            kind: 'count',
            expected: 2,
            proto: 'html L860~897',
            severity: 'P0',
        },
        {
            id: 'donut.gender.title',
            desc: '성별 분포 타이틀',
            selector: '.admin-stats-donut-card:nth-child(1) .admin-stats-section-title',
            kind: 'text',
            expected: '성별 분포',
            proto: 'html L863',
            severity: 'P0',
        },
        {
            id: 'donut.age.title',
            desc: '연령 분포 타이틀',
            selector: '.admin-stats-donut-card:nth-child(2) .admin-stats-section-title',
            kind: 'text',
            expected: '연령 분포',
            proto: 'html L881',
            severity: 'P0',
        },
        {
            id: 'donut.svg.count',
            desc: '도넛 SVG 2개 렌더',
            selector: '.admin-stats-donut-svg svg',
            kind: 'count',
            expected: 2,
            proto: 'Qn-1 서버 SVG · createDonutChart 이식',
            severity: 'P0',
        },
        // ── Deadline / Pending list ─────────────────────────
        {
            id: 'list.row.count',
            desc: '하단 리스트 카드 2개 (마감임박 · 승인대기)',
            selector: '.admin-stats-list-card',
            kind: 'count',
            expected: 2,
            proto: 'Qn-10 마감임박 + A6 승인대기',
            severity: 'P0',
        },
    ],
};
