/**
 * 관리자 대시보드 콘텐츠 (`/admin`) 디자인 계약.
 *
 * 로그인 후 진입 상태에서 검사. shell 계약과 페이지가 같지만 검사 대상이 다르므로 파일 분리.
 * 추출 기준: `docs/00_assets/admin/prototype.html` L602~788 · 2026-09-03 A1.
 */

import type { ScreenContract } from './types';

export const adminDashboardContract: ScreenContract = {
    screen: 'admin-dashboard',
    path: '/admin',
    source: 'admin/prototype.html L602~788 · 2026-09-03 A1',
    viewport: { width: 1440, height: 900 },
    checks: [
        // ── Welcome ──────────────────────────────────────────
        {
            id: 'welcome.title.contains',
            desc: 'Welcome 타이틀 "반가워요" 시작',
            selector: '.admin-dashboard-welcome-title',
            kind: 'exists',
            expected: true,
            proto: 'html L608 반가워요, {이름}님 👋',
            severity: 'P0',
        },
        {
            id: 'welcome.title.font-size',
            desc: 'Welcome 타이틀 폰트 21',
            selector: '.admin-dashboard-welcome-title',
            kind: 'css',
            prop: 'font-size',
            expected: '21px',
            proto: 'html L608 fontSize:21',
            severity: 'P1',
        },
        {
            id: 'welcome.title.font-weight',
            desc: 'Welcome 타이틀 굵기 700',
            selector: '.admin-dashboard-welcome-title',
            kind: 'css',
            prop: 'font-weight',
            expected: '700',
            proto: 'html L608 fontWeight:700',
            severity: 'P2',
        },
        {
            id: 'welcome.sub.text',
            desc: 'Welcome 서브 카피',
            selector: '.admin-dashboard-welcome-sub',
            kind: 'text',
            expected: '오늘도 청년모아 프로그램 운영을 함께합니다.',
            proto: 'html L609',
            severity: 'P1',
        },
        // ── Stat cards ──────────────────────────────────────
        {
            id: 'stat.cards.count',
            desc: 'Stat 카드 4개',
            selector: '.admin-stat-card',
            kind: 'count',
            expected: 4,
            proto: 'html L613 grid repeat(4,1fr)',
            severity: 'P0',
        },
        {
            id: 'stat.label.active',
            desc: '진행중 프로그램 라벨',
            selector: '.admin-stat-card:nth-child(1) .admin-stat-card-label',
            kind: 'text',
            expected: '진행중 프로그램',
            proto: 'html L618',
            severity: 'P1',
        },
        {
            id: 'stat.label.closed',
            desc: '마감 프로그램 라벨',
            selector: '.admin-stat-card:nth-child(2) .admin-stat-card-label',
            kind: 'text',
            expected: '마감 프로그램',
            proto: 'html L633',
            severity: 'P1',
        },
        {
            id: 'stat.label.upcoming',
            desc: '진행 예정 라벨',
            selector: '.admin-stat-card:nth-child(3) .admin-stat-card-label',
            kind: 'text',
            expected: '진행 예정',
            proto: 'html L648',
            severity: 'P1',
        },
        {
            id: 'stat.label.users',
            desc: '전체 회원 라벨',
            selector: '.admin-stat-card:nth-child(4) .admin-stat-card-label',
            kind: 'text',
            expected: '전체 회원',
            proto: 'html L663',
            severity: 'P1',
        },
        {
            id: 'stat.value.font-size',
            desc: 'Stat 수치 폰트 32',
            selector: '.admin-stat-card-value',
            kind: 'css',
            prop: 'font-size',
            expected: '32px',
            proto: 'html L623 fontSize:32',
            severity: 'P1',
        },
        {
            id: 'stat.value.font-weight',
            desc: 'Stat 수치 굵기 700',
            selector: '.admin-stat-card-value',
            kind: 'css',
            prop: 'font-weight',
            expected: '700',
            proto: 'html L623 fontWeight:700',
            severity: 'P2',
        },
        {
            id: 'stat.icon.width',
            desc: 'Stat 아이콘 34px',
            selector: '.admin-stat-card-icon',
            kind: 'box',
            prop: 'width',
            expected: 34,
            tolerance: 1,
            proto: 'html L619 width:34',
            severity: 'P2',
        },
        // ── Body row grid ────────────────────────────────────
        {
            id: 'body.recent.exists',
            desc: '최근 프로그램 카드 존재',
            selector: '.admin-recent-programs',
            kind: 'exists',
            expected: true,
            proto: 'html L681',
            severity: 'P0',
        },
        {
            id: 'body.recent.title',
            desc: '최근 프로그램 타이틀',
            selector: '.admin-recent-programs .admin-card-title',
            kind: 'text',
            expected: '최근 프로그램 현황',
            proto: 'html L683',
            severity: 'P1',
        },
        {
            id: 'body.recent.head-columns',
            desc: '최근 프로그램 헤더 4컬럼',
            selector: '.admin-recent-programs-row--head span',
            kind: 'count',
            expected: 4,
            proto: 'html L687 grid 4 columns',
            severity: 'P2',
        },
        // ── Quick links ─────────────────────────────────────
        {
            id: 'side.quick.title',
            desc: '빠른 메뉴 타이틀',
            selector: '.admin-quick-links-title',
            kind: 'text',
            expected: '빠른 메뉴',
            proto: 'html L709',
            severity: 'P1',
        },
        {
            id: 'side.quick.count',
            desc: '빠른 메뉴 3개',
            selector: '.admin-quick-link',
            kind: 'count',
            expected: 3,
            proto: 'html L711~728',
            severity: 'P1',
        },
        // ── Pending approval ────────────────────────────────
        {
            id: 'side.pending.exists',
            desc: '승인 대기 카드 존재',
            selector: '.admin-pending-card',
            kind: 'exists',
            expected: true,
            proto: 'html L733',
            severity: 'P0',
        },
        {
            id: 'side.pending.label',
            desc: '승인 대기 라벨 텍스트 포함',
            selector: '.admin-pending-card-label',
            kind: 'text',
            expected: '승인 대기',
            proto: 'html L735~737',
            severity: 'P1',
        },
        {
            id: 'side.pending.value.font-size',
            desc: '승인 대기 count 폰트 32',
            selector: '.admin-pending-card-value',
            kind: 'css',
            prop: 'font-size',
            expected: '32px',
            proto: 'html L743 fontSize:32',
            severity: 'P1',
        },
        {
            id: 'side.pending.cta.text',
            desc: '바로 처리하기 CTA 텍스트',
            selector: '.admin-pending-card-cta-link',
            kind: 'text',
            expected: '바로 처리하기 →',
            proto: 'html L747',
            severity: 'P1',
            deferred: 'A5: 승인 처리 페이지 미구현. 링크만 노출',
        },
        // ── 마감 임박 ────────────────────────────────────────
        {
            id: 'urgent.exists',
            desc: '마감 임박 프로그램 카드 존재',
            selector: '.admin-urgent-programs',
            kind: 'exists',
            expected: true,
            proto: 'html L755',
            severity: 'P0',
        },
        {
            id: 'urgent.title',
            desc: '마감 임박 타이틀',
            selector: '.admin-urgent-programs .admin-card-title',
            kind: 'text',
            expected: '마감 임박 프로그램',
            proto: 'html L759',
            severity: 'P1',
        },
        {
            id: 'urgent.pill',
            desc: 'D-7 이내 pill',
            selector: '.admin-urgent-pill',
            kind: 'text',
            expected: 'D-7 이내',
            proto: 'html L760',
            severity: 'P1',
        },
        {
            id: 'urgent.head-columns',
            desc: '마감 임박 헤더 5컬럼',
            selector: '.admin-urgent-programs-row--head span',
            kind: 'count',
            expected: 5,
            proto: 'html L765 grid 5 columns',
            severity: 'P2',
        },
        // ── deferred: Stat trend copy (A6 이월) ──────────────
        {
            id: 'stat.trend.increased',
            desc: '"지난달보다 증가" 카피 (A6 실계산 대체 예정)',
            selector: '.admin-stat-card-trend-caption',
            kind: 'text',
            expected: '지난달보다 증가',
            proto: 'html L626',
            severity: 'P2',
            deferred: 'A6 (docs/specs/A6): 통계 화면에서 실계산',
        },
    ],
};
