/**
 * 관리자 shell (다크 헤더) 디자인 계약.
 *
 * 로그인 후 `/admin` 진입 상태에서 검사한다. spec 이 사전 로그인 처리.
 * 추출 기준: `docs/00_assets/admin/prototype.html` L336~537 · 2026-09-03 A1.
 */

import type { ScreenContract } from './types';

export const adminShellContract: ScreenContract = {
    screen: 'admin-shell',
    path: '/admin',
    source: 'admin/prototype.html L336~537 · 2026-09-03 A1',
    viewport: { width: 1440, height: 900 },
    checks: [
        // ── 헤더 기본 골격 ──────────────────────────────────
        {
            id: 'header.height',
            desc: '다크 헤더 높이 56',
            selector: '.admin-header',
            kind: 'box',
            prop: 'height',
            expected: 56,
            tolerance: 1,
            proto: 'html L336 height:56',
            severity: 'P1',
        },
        {
            id: 'header.background',
            desc: '헤더 배경 #111827',
            selector: '.admin-header',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgb(17, 24, 39)',
            proto: 'html L336 background:#111827',
            severity: 'P1',
        },
        {
            id: 'header.position',
            desc: '헤더 sticky',
            selector: '.admin-header',
            kind: 'css',
            prop: 'position',
            expected: 'sticky',
            proto: 'html L336 position:sticky',
            severity: 'P2',
        },
        // ── 로고 · 뱃지 ──────────────────────────────────────
        {
            id: 'header.logo.height',
            desc: '로고 높이 34',
            selector: '.admin-header-logo',
            kind: 'box',
            prop: 'height',
            expected: 34,
            tolerance: 1,
            proto: 'html L340 height:34',
            severity: 'P2',
        },
        {
            id: 'header.badge.text',
            desc: 'ADMIN 뱃지 텍스트',
            selector: '.admin-header-badge',
            kind: 'text',
            expected: 'ADMIN',
            proto: 'html L341',
            severity: 'P0',
        },
        {
            id: 'header.badge.font-size',
            desc: 'ADMIN 뱃지 폰트 10',
            selector: '.admin-header-badge',
            kind: 'css',
            prop: 'font-size',
            expected: '10px',
            proto: 'html L341 fontSize:10',
            severity: 'P2',
        },
        {
            id: 'header.badge.color',
            desc: 'ADMIN 뱃지 텍스트 색상 #A6A3B3',
            selector: '.admin-header-badge',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(166, 163, 179)',
            proto: 'html L341 color:#A6A3B3',
            severity: 'P2',
        },
        // ── divider ─────────────────────────────────────────
        {
            id: 'header.divider.exists',
            desc: '로고~스코프 사이 divider',
            selector: '.admin-header-divider',
            kind: 'exists',
            expected: true,
            proto: 'html L344',
            severity: 'P2',
        },
        // ── 센터 스코프 셀렉터 ──────────────────────────────
        {
            id: 'header.scope.exists',
            desc: '센터 스코프 셀렉터 존재',
            selector: '.admin-header-scope',
            kind: 'exists',
            expected: true,
            proto: 'html L345~371',
            severity: 'P0',
        },
        {
            id: 'header.scope.label',
            desc: 'SYSTEM_ADMIN 스코프 라벨 "전체"',
            selector: '.admin-header-scope-label',
            kind: 'text',
            expected: '전체',
            proto: 'html L350 SYSTEM_ADMIN 라벨',
            severity: 'P1',
        },
        {
            id: 'header.scope.font-size',
            desc: '스코프 라벨 폰트 12',
            selector: '.admin-header-scope-label',
            kind: 'css',
            prop: 'font-size',
            expected: '12px',
            proto: 'html L350 fontSize:12',
            severity: 'P2',
        },
        // ── GNB — Qn-6 B: 통계/프로그램/사용자 GNB 미노출 ─────
        {
            id: 'gnb.hidden-links.count',
            desc: 'A1: 미구현 GNB 3항목 미노출 (deviation)',
            selector: '.admin-header-nav a[href="#"]',
            kind: 'count',
            expected: 0,
            proto: 'html L397~399 통계/프로그램/사용자 관리 링크',
            severity: 'P2',
            deviation: 'Qn-6 B: A2/A5/A6 순차 도입. A1 은 대시보드 활성 링크만 노출',
        },
        // ── 우측 아이콘 자리 ────────────────────────────────
        {
            id: 'header.search.placeholder',
            desc: '검색 자리 존재 (disabled)',
            selector: '.admin-header-icon-btn[aria-label*="검색"]',
            kind: 'exists',
            expected: true,
            proto: 'html L406~413 검색 인풋',
            severity: 'P2',
            deferred: 'A7 (docs/specs/A7): 검색·알림·센터 셀렉터 실동작',
        },
        {
            id: 'header.bell.placeholder',
            desc: '알림 벨 자리 존재 (disabled)',
            selector: '.admin-header-bell',
            kind: 'exists',
            expected: true,
            proto: 'html L444~453 알림 벨',
            severity: 'P2',
            deferred: 'A7 (docs/specs/A7): 알림 벨 드롭다운·미읽음 뱃지',
        },
        // ── 유저 드롭다운 ────────────────────────────────────
        {
            id: 'header.user.trigger.exists',
            desc: '유저 드롭다운 트리거 존재',
            selector: '.admin-header-user-trigger',
            kind: 'exists',
            expected: true,
            proto: 'html L497~501',
            severity: 'P0',
        },
        {
            id: 'header.user.avatar.width',
            desc: '유저 아바타 30px',
            selector: '.admin-header-avatar',
            kind: 'box',
            prop: 'width',
            expected: 30,
            tolerance: 1,
            proto: 'html L499 width:30',
            severity: 'P2',
        },
        // ── 유저 드롭다운 초기 hidden ─────────────────────────
        {
            id: 'header.user.dropdown.hidden-initial',
            desc: '유저 드롭다운 초기 hidden',
            selector: '#admin-user-dropdown[hidden]',
            kind: 'count',
            expected: 1,
            proto: 'A1 표준 — 트리거 클릭 시 열림',
            severity: 'P1',
        },
        // ── 데모 권한 전환 없음 (production 제거) ─────────────
        {
            id: 'header.demo-role-switcher.absent',
            desc: '데모 권한 전환 pill 미노출 (production)',
            selector: '[title="데모: 권한 전환"]',
            kind: 'count',
            expected: 0,
            proto: 'html L376 데모 pill',
            severity: 'P2',
            deviation: 'HANDOFF: 데모 pill → 프로덕션 제거',
        },
        // ── Body 배경 ────────────────────────────────────────
        {
            id: 'shell.body.background',
            desc: '메인 배경 #FAFAFB',
            selector: '.admin-shell-main',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgb(250, 250, 251)',
            proto: 'html L540 background:#FAFAFB',
            severity: 'P2',
        },
    ],
};
