/**
 * 관리자 프로그램 관리 (`/admin/programs`, `/admin/programs/{id}`) 디자인 계약.
 *
 * A2 (2026-09-09 · Qn-1~9 모두 A) 산출. prototype.html L907~1069 (사용자 사이드 PROGRAMS)
 * + admin POLICY (다크 헤더 · 인디고 primary · 존댓말) + `admin-notice` 관례 참조.
 * 카드/캘린더 뷰는 A8 이월 (계약에도 포함하지 않음 — A8 계약에서 신설).
 */

import type { ScreenContract } from './types';

export const adminProgramListContract: ScreenContract = {
    screen: 'admin-program-list',
    path: '/admin/programs',
    source: 'admin POLICY + prototype.html L907~1033 · 2026-09-09 A2',
    viewport: { width: 1440, height: 900 },
    checks: [
        {
            id: 'header.gnb.programs.active',
            desc: '관리자 GNB "프로그램 관리" 링크 활성',
            selector: 'nav.admin-header-nav a.admin-nav-link.active',
            kind: 'text',
            expected: '프로그램 관리',
            proto: 'admin/fragments/header.html currentPage=programs',
            severity: 'P0',
        },
        {
            id: 'page.title.exists',
            desc: '페이지 타이틀 "프로그램 관리"',
            selector: '.admin-program-title',
            kind: 'text',
            expected: '프로그램 관리',
            proto: 'admin/program/list.html',
            severity: 'P0',
        },
        {
            id: 'page.subtitle.exists',
            desc: '서브 카피 존재',
            selector: '.admin-program-sub',
            kind: 'exists',
            expected: true,
            proto: 'admin/program/list.html',
            severity: 'P1',
        },
        {
            id: 'actionbar.search.input',
            desc: '검색 인풋 존재 (placeholder="프로그램명, 센터 검색")',
            selector: '.admin-program-search-input',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L919',
            severity: 'P0',
        },
        {
            id: 'actionbar.tabs.exists',
            desc: '상태 필터 세그먼트 존재',
            selector: '.admin-program-tabs',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L907~945',
            severity: 'P0',
        },
        {
            id: 'actionbar.tabs.count',
            desc: '필터 5종 (전체/모집중/진행예정/종료/운영중단)',
            selector: '.admin-program-tabs .admin-program-tab',
            kind: 'count',
            expected: 5,
            proto: 'spec §3-1 Qn-3 A',
            severity: 'P0',
        },
        {
            id: 'list.head.row',
            desc: '테이블 헤더 행 존재',
            selector: '.admin-program-row.admin-program-row--head',
            kind: 'exists',
            expected: true,
            proto: 'admin/program/list.html',
            severity: 'P0',
        },
        {
            id: 'list.head.col.name',
            desc: '헤더 "프로그램명" 컬럼',
            selector: '.admin-program-row--head .admin-program-col-name',
            kind: 'text',
            expected: '프로그램명',
            proto: 'prototype.html L960 컬럼 헤더',
            severity: 'P1',
        },
        {
            id: 'list.head.col.status',
            desc: '헤더 "상태" 컬럼',
            selector: '.admin-program-row--head .admin-program-col-status',
            kind: 'text',
            expected: '상태',
            proto: 'prototype.html L960',
            severity: 'P1',
        },
        {
            id: 'list.head.col.applied',
            desc: '헤더 "신청현황" 컬럼',
            selector: '.admin-program-row--head .admin-program-col-applied',
            kind: 'text',
            expected: '신청현황',
            proto: 'prototype.html L960',
            severity: 'P1',
        },
        {
            id: 'list.head.col.actions',
            desc: '헤더 "관리" 컬럼',
            selector: '.admin-program-row--head .admin-program-col-actions',
            kind: 'text',
            expected: '관리',
            proto: 'prototype.html L960',
            severity: 'P1',
        },
        {
            id: 'list.rows.seeded',
            desc: '시드된 프로그램 5건 이상 렌더 (첫 페이지 10건)',
            selector: '.admin-program-row:not(.admin-program-row--head)',
            kind: 'count-min',
            expected: 5,
            proto: 'DataInitializer 시드',
            severity: 'P0',
        },
        {
            id: 'row.edit.link',
            desc: '각 row 편집 링크 (액션 컬럼)',
            selector: '.admin-program-row:not(.admin-program-row--head) .admin-program-col-actions a',
            kind: 'count-min',
            expected: 1,
            proto: 'spec §3-1 Qn-7 A',
            severity: 'P0',
        },
        {
            id: 'row.status.badge',
            desc: '각 row 상태 뱃지 노출',
            selector: '.admin-program-row:not(.admin-program-row--head) .admin-status-badge',
            kind: 'count-min',
            expected: 1,
            proto: 'spec §1-B',
            severity: 'P0',
        },
        // deferred — A3/A6/A8 이월
        {
            id: 'row.apply.period.column',
            desc: '신청기간 컬럼 (A3 이월 · A2 에서는 "-")',
            selector: '.admin-program-row:not(.admin-program-row--head) .admin-program-col-apply',
            kind: 'text',
            expected: '(신청기간)',
            proto: 'prototype.html L960',
            severity: 'P2',
            deferred: 'A3 (docs/specs/ADMIN-00-master-directive.md §5-A3) — A2 는 "-" 자리만',
        },
        {
            id: 'row.views.column',
            desc: '조회수 컬럼 (A6 이월 · A2 에서는 "-")',
            selector: '.admin-program-row:not(.admin-program-row--head) .admin-program-col-views',
            kind: 'text',
            expected: '(조회수)',
            proto: 'prototype.html L960',
            severity: 'P2',
            deferred: 'A6 (통계 트랙)',
        },
        {
            id: 'actionbar.view.toggle',
            desc: '뷰 토글 (카드/캘린더) — A8 이월',
            selector: '.admin-program-view-toggle',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L907~945',
            severity: 'P2',
            deferred: 'A8 (docs/specs/ADMIN-00-master-directive.md §5-A8) — 카드/캘린더 뷰',
        },
        {
            id: 'actionbar.csv.button',
            desc: 'CSV 내보내기 버튼 — A8 이월',
            selector: '.admin-program-csv-btn',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L4195 CSV 헤더',
            severity: 'P2',
            deferred: 'A8',
        },
        {
            id: 'list.checkbox.column',
            desc: '체크박스 컬럼 — A8 이월',
            selector: '.admin-program-row--head .admin-program-col-check',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L907~945',
            severity: 'P2',
            deferred: 'A8 (일괄 선택)',
        },
    ],
};

export const adminProgramDetailContract: ScreenContract = {
    screen: 'admin-program-detail',
    path: '/admin/programs/1',
    source: 'admin POLICY + spec §3-2 · 2026-09-09 A2',
    viewport: { width: 1440, height: 900 },
    checks: [
        {
            id: 'header.gnb.programs.active',
            desc: '관리자 GNB "프로그램 관리" 활성 (상세에서도)',
            selector: 'nav.admin-header-nav a.admin-nav-link.active',
            kind: 'text',
            expected: '프로그램 관리',
            proto: 'admin/fragments/header.html',
            severity: 'P0',
        },
        {
            id: 'breadcrumb.exists',
            desc: '브레드크럼 "프로그램 목록" 링크',
            selector: '.admin-program-breadcrumb-link',
            kind: 'exists',
            expected: true,
            proto: 'admin/program/detail.html',
            severity: 'P1',
        },
        {
            id: 'title.exists',
            desc: '프로그램 제목 렌더',
            selector: '.admin-program-detail-title',
            kind: 'exists',
            expected: true,
            proto: 'admin/program/detail.html',
            severity: 'P0',
        },
        {
            id: 'status.badge.exists',
            desc: '상태 뱃지 렌더 (헤더)',
            selector: '.admin-program-detail-meta .admin-status-badge',
            kind: 'exists',
            expected: true,
            proto: 'spec §3-2',
            severity: 'P0',
        },
        {
            id: 'action.preview.link',
            desc: '"사용자 화면 미리보기" 링크',
            selector: '.admin-program-detail-actions a[target="_blank"]',
            kind: 'exists',
            expected: true,
            proto: 'spec §3-2 A안',
            severity: 'P1',
        },
        {
            id: 'action.edit.disabled',
            desc: '"편집" 버튼 disabled (A3 이월)',
            selector: '.admin-program-detail-actions button[disabled]',
            kind: 'count-min',
            expected: 2,
            proto: 'spec §3-2 (A3 이월)',
            severity: 'P0',
        },
        {
            id: 'info.card.exists',
            desc: '기본 정보 카드',
            selector: '.admin-program-detail-card',
            kind: 'count-min',
            expected: 3,
            proto: 'spec §3-2 (기본 정보 + 하위 관리 + 자격요건 + 설명)',
            severity: 'P0',
        },
        {
            id: 'sublink.eligibility',
            desc: '하위 관리: 자격요건 편집 링크 (F4)',
            selector: 'a[href*="/eligibility"]',
            kind: 'exists',
            expected: true,
            proto: 'spec §3-2 (F4 완료)',
            severity: 'P0',
        },
        {
            id: 'sublink.dynamic',
            desc: '하위 관리: 동적 필드 관리 링크 (F0c)',
            selector: 'a[href*="/dynamic-fields"]',
            kind: 'exists',
            expected: true,
            proto: 'spec §3-2 (F0c 완료)',
            severity: 'P0',
        },
        {
            id: 'sublink.applications.deferred',
            desc: '하위 관리: 신청 현황 (A4 이월 · disabled)',
            selector: '.admin-program-detail-link--disabled',
            kind: 'exists',
            expected: true,
            proto: 'spec §3-2 (A4 이월)',
            severity: 'P1',
        },
    ],
};
