/**
 * 관리자 로그인 (`/admin/login`) 디자인 계약.
 *
 * 추출 기준: `docs/00_assets/admin/prototype.html` L60~96 · 2026-09-03 A1 신설.
 * 서술 계약: docs/design-contracts/admin/login.md
 */

import type { ScreenContract } from './types';

export const adminLoginContract: ScreenContract = {
    screen: 'admin-login',
    path: '/admin/login',
    source: 'admin/prototype.html L60~96 · 2026-09-03 A1',
    viewport: { width: 1440, height: 900 },
    checks: [
        // ── Auth Header ──────────────────────────────────────────
        {
            id: 'auth-header.height',
            desc: 'Auth Header 높이 64',
            selector: '.admin-auth-header',
            kind: 'box',
            prop: 'height',
            expected: 64,
            tolerance: 1,
            proto: 'html L61 height:64',
            severity: 'P1',
        },
        {
            id: 'auth-header.badge.text',
            desc: 'ADMIN 뱃지 텍스트',
            selector: '.admin-auth-header-badge',
            kind: 'text',
            expected: 'ADMIN',
            proto: 'html L63',
            severity: 'P0',
        },
        {
            id: 'auth-header.logo.height',
            desc: '로고 높이 32',
            selector: '.admin-auth-header-logo',
            kind: 'box',
            prop: 'height',
            expected: 32,
            tolerance: 1,
            proto: 'html L62 height:32',
            severity: 'P2',
        },
        // ── 타이틀 · 서브 카피 ────────────────────────────────
        {
            id: 'title.text',
            desc: '타이틀 "관리자 로그인"',
            selector: '.admin-auth-title',
            kind: 'text',
            expected: '관리자 로그인',
            proto: 'html L70',
            severity: 'P0',
        },
        {
            id: 'title.font-size',
            desc: '타이틀 폰트 26',
            selector: '.admin-auth-title',
            kind: 'css',
            prop: 'font-size',
            expected: '26px',
            proto: 'html L70 fontSize:26',
            severity: 'P1',
        },
        {
            id: 'title.font-weight',
            desc: '타이틀 굵기 700',
            selector: '.admin-auth-title',
            kind: 'css',
            prop: 'font-weight',
            expected: '700',
            proto: 'html L70 fontWeight:700',
            severity: 'P2',
        },
        {
            id: 'subtitle.text',
            desc: '서브 카피',
            selector: '.admin-auth-subtitle',
            kind: 'text',
            expected: '청년모아 관리자 페이지에 오신 것을 환영합니다',
            proto: 'html L71',
            severity: 'P1',
        },
        // ── 카드 ─────────────────────────────────────────────
        {
            id: 'card.width',
            desc: '카드 max-width 420',
            selector: '.admin-auth-inner',
            kind: 'box',
            prop: 'width',
            expected: 420,
            tolerance: 1,
            proto: 'html L69 max-width:420',
            severity: 'P1',
        },
        {
            id: 'card.border-radius',
            desc: '카드 radius 16',
            selector: '.admin-auth-card',
            kind: 'css',
            prop: 'border-radius',
            expected: '16px',
            proto: 'html L72 borderRadius:16',
            severity: 'P2',
        },
        // ── 인풋 ─────────────────────────────────────────────
        {
            id: 'input.username.exists',
            desc: '아이디 input 존재',
            selector: 'input[name="username"]',
            kind: 'exists',
            expected: true,
            proto: 'html L76',
            severity: 'P0',
        },
        {
            id: 'input.password.exists',
            desc: '비밀번호 input 존재',
            selector: 'input[name="password"]',
            kind: 'exists',
            expected: true,
            proto: 'html L80',
            severity: 'P0',
        },
        {
            id: 'input.border-radius',
            desc: '아이디 input radius 8',
            selector: 'input[name="username"]',
            kind: 'css',
            prop: 'border-radius',
            expected: '8px',
            proto: 'html L76 borderRadius:8',
            severity: 'P2',
        },
        // ── 로그인 버튼 ──────────────────────────────────────
        {
            id: 'submit.text',
            desc: '로그인 버튼 텍스트',
            selector: '.admin-auth-submit',
            kind: 'text',
            expected: '로그인',
            proto: 'html L86',
            severity: 'P0',
        },
        {
            id: 'submit.border-radius',
            desc: '로그인 버튼 radius 10',
            selector: '.admin-auth-submit',
            kind: 'css',
            prop: 'border-radius',
            expected: '10px',
            proto: 'html L86 borderRadius:10',
            severity: 'P2',
        },
        {
            id: 'submit.font-size',
            desc: '로그인 버튼 폰트 15',
            selector: '.admin-auth-submit',
            kind: 'css',
            prop: 'font-size',
            expected: '15px',
            proto: 'html L86 fontSize:15',
            severity: 'P2',
        },
        {
            id: 'submit.font-weight',
            desc: '로그인 버튼 굵기 700',
            selector: '.admin-auth-submit',
            kind: 'css',
            prop: 'font-weight',
            expected: '700',
            proto: 'html L86 fontWeight:700',
            severity: 'P2',
        },
        // ── 회원가입 버튼 — A1 은 렌더 안 함 (deviation) ──────
        {
            id: 'signup-button.absent',
            desc: 'A1: 회원가입 버튼 미노출 (deviation)',
            selector: '.admin-auth-card button:not([type="submit"])',
            kind: 'count',
            expected: 0,
            proto: 'html L87 회원가입 버튼 — ADMIN-00 Q8 signup 미구현',
            severity: 'P2',
            deviation: 'ADMIN-00 Q8: 관리자 signup 미구현. prototype 이탈 확정',
        },
        // ── 하단 링크 ────────────────────────────────────────
        {
            id: 'find-id.link',
            desc: '아이디 찾기 링크',
            selector: '.admin-auth-help-link[href="/find-id"]',
            kind: 'text',
            expected: '아이디 찾기',
            proto: 'html L90',
            severity: 'P1',
        },
        {
            id: 'find-pw.link',
            desc: '비밀번호 찾기 링크',
            selector: '.admin-auth-help-link[href="/find-password"]',
            kind: 'text',
            expected: '비밀번호 찾기',
            proto: 'html L92',
            severity: 'P1',
        },
        // ── 사용자 헤더 부재 (auth 레이아웃) ─────────────────
        {
            id: 'user-header.absent',
            desc: '사용자 헤더 미렌더 (auth 레이아웃)',
            selector: '.site-header',
            kind: 'count',
            expected: 0,
            proto: 'html L61 Auth Header 별개',
            severity: 'P1',
        },
    ],
};
