/**
 * 관리자 프로그램 신청 관리 (`/admin/programs/{id}/applications`, `/admin/programs/{id}/applications/{aid}`) 디자인 계약.
 *
 * A4 admin-program-detail (2026-09-15 · Qn 24건 모두 A) 산출. prototype.html L1370~1441 (목록)
 * + L2677~2749 (상세 모달) + admin POLICY (다크 헤더 · 인디고 primary · 존댓말).
 *
 * 상세 UI 는 spec §Qn-B A "480px 모달" 이지만 구현은 페이지 wrapper 로 렌더 (deviation) — 상세 fragment 자체는
 * modal 로 정의되어 후속 HTMX 도입 시 재활용 가능.
 */

import type { ScreenContract } from './types';

export const adminProgramApplicationsListContract: ScreenContract = {
    screen: 'admin-program-applications-list',
    path: '/admin/programs/1/applications',
    source: 'admin POLICY + prototype.html L1370~1441 · 2026-09-15 A4',
    viewport: { width: 1440, height: 900 },
    checks: [
        {
            id: 'header.gnb.programs.active',
            desc: '관리자 GNB "프로그램 관리" 링크 활성',
            selector: 'nav.admin-header-nav a.admin-nav-link.active',
            kind: 'text',
            expected: '프로그램 관리',
            proto: 'admin/fragments/header.html currentPage=programs',
            severity: 'P0',
        },
        {
            id: 'page.title.exists',
            desc: '페이지 타이틀 "신청 관리"',
            selector: '.admin-program-form-title',
            kind: 'text',
            expected: '신청 관리',
            proto: 'admin/program/applications.html · prototype L1372',
            severity: 'P0',
        },
        {
            id: 'breadcrumb.back',
            desc: '브레드크럼 "← 프로그램 상세로" 링크',
            selector: '.admin-program-breadcrumb-link',
            kind: 'text',
            expected: '← 프로그램 상세로',
            proto: 'spec §6-1',
            severity: 'P1',
        },
        // 요약 배지 5종 (전체 · 대기 · 승인 · 반려 · 취소 · 정원)
        {
            id: 'summary.badges.container',
            desc: '요약 배지 컨테이너',
            selector: '[data-testid="summary-badges"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype L1374~1384',
            severity: 'P0',
        },
        {
            id: 'summary.total',
            desc: '전체 카운트 배지',
            selector: '[data-testid="summary-total"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype L1374',
            severity: 'P0',
        },
        {
            id: 'summary.pending',
            desc: '대기 카운트 배지',
            selector: '[data-testid="summary-pending"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype L1376',
            severity: 'P0',
        },
        {
            id: 'summary.approved',
            desc: '승인 카운트 배지',
            selector: '[data-testid="summary-approved"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype L1378',
            severity: 'P0',
        },
        {
            id: 'summary.rejected',
            desc: '반려 카운트 배지',
            selector: '[data-testid="summary-rejected"]',
            kind: 'exists',
            expected: true,
            proto: 'spec §6-1 요약 배지',
            severity: 'P0',
        },
        {
            id: 'summary.cancelled',
            desc: '취소 카운트 배지',
            selector: '[data-testid="summary-cancelled"]',
            kind: 'exists',
            expected: true,
            proto: 'spec §6-1 요약 배지',
            severity: 'P0',
        },
        // 필터 세그먼트 (5종 · 상태별)
        {
            id: 'filter.all',
            desc: '상태 필터 "전체"',
            selector: '[data-testid="filter-all"]',
            kind: 'text',
            expected: '전체',
            proto: 'spec §6-1 필터 바',
            severity: 'P0',
        },
        {
            id: 'filter.pending',
            desc: '상태 필터 "대기"',
            selector: '[data-testid="filter-pending"]',
            kind: 'text',
            expected: '대기',
            proto: 'spec §6-1',
            severity: 'P0',
        },
        {
            id: 'filter.approved',
            desc: '상태 필터 "승인"',
            selector: '[data-testid="filter-approved"]',
            kind: 'text',
            expected: '승인',
            proto: 'spec §6-1',
            severity: 'P0',
        },
        {
            id: 'filter.rejected',
            desc: '상태 필터 "반려"',
            selector: '[data-testid="filter-rejected"]',
            kind: 'text',
            expected: '반려',
            proto: 'spec §6-1',
            severity: 'P1',
        },
        {
            id: 'filter.cancelled',
            desc: '상태 필터 "취소"',
            selector: '[data-testid="filter-cancelled"]',
            kind: 'text',
            expected: '취소',
            proto: 'spec §6-1',
            severity: 'P1',
        },
        {
            id: 'filter.search.input',
            desc: '신청자 검색 인풋',
            selector: '[data-testid="filter-q"]',
            kind: 'exists',
            expected: true,
            proto: 'spec §6-1 · prototype L1370 검색',
            severity: 'P0',
        },
        // 테이블
        {
            id: 'list.head.row',
            desc: '테이블 헤더 행 존재',
            selector: '.admin-application-row--head',
            kind: 'exists',
            expected: true,
            proto: 'admin/program/applications.html',
            severity: 'P0',
        },
        {
            id: 'list.rows.seeded',
            desc: '시드된 신청 1건 이상 렌더 (program 1 은 28 APPROVED)',
            selector: '.admin-application-row:not(.admin-application-row--head)',
            kind: 'count-min',
            expected: 1,
            proto: 'DataInitializer 시드 (program 1 = 28 APPROVED)',
            severity: 'P0',
        },
        {
            id: 'row.status.badge',
            desc: '각 row 상태 뱃지 노출',
            selector: '[data-testid="row-status-badge"]',
            kind: 'count-min',
            expected: 1,
            proto: 'spec §6-1 · prototype L1440',
            severity: 'P0',
        },
        {
            id: 'row.open.detail',
            desc: '각 row 상세 링크',
            selector: '[data-testid="open-detail-btn"]',
            kind: 'count-min',
            expected: 1,
            proto: 'spec §6-1 클릭 → 모달',
            severity: 'P0',
        },
        // A8 (2026-09-17) 편입 · Qn-App1 A: Approve bulk 만. Reject 는 A8-reject-bulk 로 재이월
        {
            id: 'bulk.selection.bar',
            desc: 'Bulk selection bar (A8 편입 · 일괄 승인 · Reject 는 이월)',
            selector: '.admin-bulk-action-bar[data-bulk-domain="applications"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype L1397~1412 · A8 spec §4-3',
            severity: 'P0',
        },
        {
            id: 'actionbar.csv.button',
            desc: 'CSV 내보내기 버튼 (A8 편입)',
            selector: '[data-testid="csv-export-btn"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype L1391 · L4185 · A8 Qn-CSV1',
            severity: 'P0',
        },
        {
            id: 'actionbar.approve.all',
            desc: '대기 전체 승인 버튼 — A8 이월',
            selector: '[data-testid="approve-all-pending-btn"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype L1387',
            severity: 'P2',
            deferred: 'A8 — 대기 전체 승인 (spec §Qn-Δ2 B)',
        },
    ],
};

export const adminProgramApplicationDetailContract: ScreenContract = {
    screen: 'admin-program-application-detail',
    path: '/admin/programs/1/applications/1',
    source: 'admin POLICY + prototype.html L2677~2749 · 2026-09-15 A4',
    viewport: { width: 1440, height: 900 },
    checks: [
        {
            id: 'header.gnb.programs.active',
            desc: '관리자 GNB "프로그램 관리" 링크 활성',
            selector: 'nav.admin-header-nav a.admin-nav-link.active',
            kind: 'text',
            expected: '프로그램 관리',
            proto: 'admin/fragments/header.html currentPage=programs',
            severity: 'P0',
        },
        {
            id: 'page.title.exists',
            desc: '상세 페이지 타이틀 "프로그램 신청 상세"',
            selector: '.admin-program-form-title',
            kind: 'text',
            expected: '프로그램 신청 상세',
            proto: 'prototype L2679',
            severity: 'P0',
        },
        {
            id: 'breadcrumb.back',
            desc: '뒤로가기 "← 신청 목록"',
            selector: '[data-testid="back-to-list"]',
            kind: 'text',
            expected: '← 신청 목록',
            proto: 'spec §6-2',
            severity: 'P1',
        },
        {
            id: 'user.info.section',
            desc: '신청자 정보 grid section',
            selector: '[data-testid="detail-user-info"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype L2684~2699 · spec §6-2 §2',
            severity: 'P0',
        },
        {
            id: 'detail.status.badge',
            desc: '상세 상태 배지',
            selector: '[data-testid="detail-status-badge"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype L2681',
            severity: 'P0',
        },
        // 상태 변경 3 액션
        {
            id: 'action.approve',
            desc: '승인 버튼',
            selector: '[data-testid="btn-approve"]',
            kind: 'text',
            expected: '승인',
            proto: 'prototype L2732~2734 · spec §6-2 §5',
            severity: 'P0',
        },
        {
            id: 'action.reject.reason.input',
            desc: '반려 사유 인풋 (필수)',
            selector: '[data-testid="reject-reason-input"]',
            kind: 'exists',
            expected: true,
            proto: 'spec §Qn-2 A 반려 사유 필수',
            severity: 'P0',
        },
        {
            id: 'action.reject.button',
            desc: '반려 버튼',
            selector: '[data-testid="btn-reject"]',
            kind: 'text',
            expected: '반려',
            proto: 'prototype L2732~2734',
            severity: 'P0',
        },
        {
            id: 'action.cancel.reason.input',
            desc: '강제 취소 사유 인풋 (필수 · Qn-C A)',
            selector: '[data-testid="cancel-reason-input"]',
            kind: 'exists',
            expected: true,
            proto: 'spec §5 Qn-C A',
            severity: 'P0',
        },
        {
            id: 'action.cancel.button',
            desc: '강제 취소 버튼 (Qn-C A · deviation)',
            selector: '[data-testid="btn-cancel"]',
            kind: 'text',
            expected: '강제 취소',
            proto: 'spec §5 Qn-C A · deviation (prototype 3옵션 이탈)',
            severity: 'P0',
        },
        // 담당자 의견
        {
            id: 'admin.note.input',
            desc: '담당자 의견 textarea (max 1000자)',
            selector: '[data-testid="admin-note-input"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype L2739 · spec §Qn-1 A V15 adminNote',
            severity: 'P0',
        },
        {
            id: 'admin.note.save',
            desc: '담당자 의견 저장 버튼',
            selector: '[data-testid="btn-save-note"]',
            kind: 'text',
            expected: '의견 저장',
            proto: 'spec §6-2 §6',
            severity: 'P0',
        },
        // deferred — HTMX modal 이월
        {
            id: 'modal.overlay',
            desc: 'HTMX 모달 오버레이 — 후행 이월',
            selector: '.admin-application-modal-overlay',
            kind: 'exists',
            expected: true,
            proto: 'prototype L2677 모달 480px',
            severity: 'P2',
            deferred: 'HTMX modal 전환 — 현재는 페이지 wrapper 로 렌더 (deviation)',
        },
    ],
};
