/**
 * 관리자 약관 관리 (`/admin/terms`, `/admin/terms/new`, `/admin/terms/{id}`) 디자인 계약.
 *
 * 참고: admin prototype 에 약관 관리 화면 부재 (spec §0 · §1). admin-notice 계약 승계 (다크 헤더 · 인디고 primary · 존댓말).
 * A-admin-terms-crud (2026-09-04 · Qn-1 B · Qn-2 B · Qn-3~9 A) 산출.
 */

import type { ScreenContract } from './types';

export const adminTermListContract: ScreenContract = {
    screen: 'admin-term-list',
    path: '/admin/terms',
    source: 'admin POLICY + admin-notice 계약 승계 · 2026-09-04 A-admin-terms-crud',
    viewport: { width: 1440, height: 900 },
    checks: [
        {
            id: 'header.gnb.terms.active',
            desc: '관리자 GNB "약관 관리" 링크 활성',
            selector: 'nav.admin-header-nav a.admin-nav-link.active',
            kind: 'text',
            expected: '약관 관리',
            proto: 'admin/fragments/header.html currentPage=terms',
            severity: 'P0',
        },
        {
            id: 'page.title.exists',
            desc: '페이지 타이틀 "약관 관리"',
            selector: '.admin-term-title',
            kind: 'text',
            expected: '약관 관리',
            proto: 'admin/term/list.html',
            severity: 'P0',
        },
        {
            id: 'page.subtitle.exists',
            desc: '서브 카피 존재',
            selector: '.admin-term-sub',
            kind: 'exists',
            expected: true,
            severity: 'P1',
        },
        {
            id: 'create.button.exists',
            desc: '"신규 등록" 버튼 (SYSTEM_ADMIN 세션 기준)',
            selector: '.admin-term-header a.admin-btn.admin-btn--primary',
            kind: 'text',
            expected: '+ 신규 등록',
            severity: 'P0',
        },
        {
            id: 'list.head.row',
            desc: '테이블 헤더 존재',
            selector: '.admin-term-row.admin-term-row--head',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'list.head.col.title',
            desc: '헤더 "제목" 컬럼',
            selector: '.admin-term-row--head .admin-term-col-title',
            kind: 'text',
            expected: '제목',
            severity: 'P1',
        },
        {
            id: 'list.head.col.version',
            desc: '헤더 "버전" 컬럼',
            selector: '.admin-term-row--head .admin-term-col-version',
            kind: 'text',
            expected: '버전',
            severity: 'P1',
        },
        {
            id: 'list.rows.seeded',
            desc: '시드된 약관 2건 렌더 (SERVICE + PRIVACY)',
            selector: '.admin-term-row:not(.admin-term-row--head)',
            kind: 'count-min',
            expected: 2,
            severity: 'P0',
        },
        {
            id: 'list.summary.active-required',
            desc: '"활성 필수 약관 N건" 요약 배지 존재',
            selector: '.admin-term-summary',
            kind: 'exists',
            expected: true,
            severity: 'P1',
        },
    ],
};

export const adminTermFormContract: ScreenContract = {
    screen: 'admin-term-form',
    path: '/admin/terms/new',
    source: 'admin POLICY + admin-notice-form 승계 · 2026-09-04 A-admin-terms-crud',
    viewport: { width: 1440, height: 900 },
    checks: [
        {
            id: 'header.gnb.terms.active',
            desc: '관리자 GNB "약관 관리" 링크 활성',
            selector: 'nav.admin-header-nav a.admin-nav-link.active',
            kind: 'text',
            expected: '약관 관리',
            severity: 'P0',
        },
        {
            id: 'page.title',
            desc: '페이지 타이틀 "약관 등록"',
            selector: '.admin-term-title',
            kind: 'text',
            expected: '약관 등록',
            severity: 'P0',
        },
        {
            id: 'field.code.exists',
            desc: '약관 코드 입력 필드 (신규 시 편집 가능)',
            selector: 'input#code[name="code"]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'field.title.exists',
            desc: '제목 입력 필드',
            selector: 'input#title[name="title"]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'field.content.exists',
            desc: '본문 textarea (Qn-2 B 임시 구현)',
            selector: 'textarea#content[name="content"]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'field.contentPath.exists',
            desc: '본문 경로 필드 (legacy 하위 호환)',
            selector: 'input#contentPath[name="contentPath"]',
            kind: 'exists',
            expected: true,
            severity: 'P1',
        },
        {
            id: 'field.sortOrder.exists',
            desc: '정렬 순서 필드',
            selector: 'input#sortOrder[name="sortOrder"]',
            kind: 'exists',
            expected: true,
            severity: 'P1',
        },
        {
            id: 'field.required.exists',
            desc: '필수 동의 체크박스',
            selector: 'input#required[name="required"]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'field.isActive.exists',
            desc: '활성 여부 체크박스',
            selector: 'input#isActive[name="isActive"]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'submit.button.exists',
            desc: '"등록" 버튼',
            selector: '.admin-term-form-actions button[type="submit"]',
            kind: 'text',
            expected: '등록',
            severity: 'P0',
        },
    ],
};

export const adminTermEditContract: ScreenContract = {
    screen: 'admin-term-edit',
    path: '/admin/terms/1',
    source: 'admin POLICY + admin-notice-edit 승계 · 2026-09-04 A-admin-terms-crud',
    viewport: { width: 1440, height: 900 },
    checks: [
        {
            id: 'page.title',
            desc: '페이지 타이틀 "약관 편집"',
            selector: '.admin-term-title',
            kind: 'text',
            expected: '약관 편집',
            severity: 'P0',
        },
        {
            id: 'field.code.readonly',
            desc: 'Qn-9 A: 편집 모드에서 code readonly',
            selector: 'input#code[readonly]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'field.bumpVersion.exists',
            desc: 'Qn-6 A: "이번 수정은 개정입니다" 체크박스 (편집 모드)',
            selector: 'input#bumpVersion[name="bumpVersion"]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'submit.button.update',
            desc: '"수정 저장" 버튼',
            selector: '.admin-term-form-actions button[type="submit"]',
            kind: 'text',
            expected: '수정 저장',
            severity: 'P0',
        },
        {
            id: 'delete.button.exists',
            desc: '삭제 버튼 (SYSTEM_ADMIN)',
            selector: '.admin-term-form-actions .admin-btn--danger',
            kind: 'text',
            expected: '삭제',
            severity: 'P0',
        },
        {
            id: 'delete.modal.exists',
            desc: '삭제 confirm 모달 마크업',
            selector: '#term-delete-modal.admin-confirm-modal',
            kind: 'exists',
            expected: true,
            severity: 'P1',
        },
    ],
};
