/**
 * 관리자 프로그램 등록/편집 폼 (`/admin/programs/new`, `/admin/programs/{id}`) 디자인 계약.
 *
 * A3-1 (2026-09-10 · Qn-A/B/C/1~8/Δ1~6 모두 A) 산출.
 * 원본: docs/00_assets/admin/prototype.html L2422~2618 (Program Form 3탭)
 * A3-2 이월 (본 계약 밖): F4/F0c 인라인 통합 · Course · ProgramAttachment · 이미지 파일 업로드 · draft
 */

import type { ScreenContract } from './types';

export const adminProgramFormNewContract: ScreenContract = {
    screen: 'admin-program-form-new',
    path: '/admin/programs/new',
    source: 'admin POLICY + prototype.html L2422~2618 · 2026-09-10 A3-1',
    viewport: { width: 1440, height: 900 },
    checks: [
        {
            id: 'header.gnb.programs.active',
            desc: '관리자 GNB "프로그램 관리" 활성',
            selector: 'nav.admin-header-nav a.admin-nav-link.active',
            kind: 'text',
            expected: '프로그램 관리',
            proto: 'admin/fragments/header.html currentPage=programs',
            severity: 'P0',
        },
        {
            id: 'page.title.new',
            desc: '신규 모드 페이지 타이틀',
            selector: '.admin-program-form-title',
            kind: 'text',
            expected: '프로그램 신규 등록',
            proto: 'prototype.html L2422 · A3-1 spec §6-1',
            severity: 'P0',
        },
        {
            id: 'breadcrumb.list',
            desc: '브레드크럼 "← 프로그램 목록" 링크',
            selector: '.admin-program-breadcrumb-link',
            kind: 'exists',
            expected: true,
            severity: 'P1',
        },
        {
            id: 'tabs.count',
            desc: '3탭 (프로그램 정보 / 신청 정보 / 약관 정보)',
            selector: '.admin-program-form-tab',
            kind: 'count-min',
            expected: 3,
            proto: 'prototype.html L2432~2436',
            severity: 'P0',
        },
        {
            id: 'tabs.info.label',
            desc: '탭 1 라벨',
            selector: '.admin-program-form-tab[data-tab-target="tab-info"]',
            kind: 'text',
            expected: '프로그램 정보',
            proto: 'prototype.html L2433',
            severity: 'P0',
        },
        {
            id: 'tabs.apply.label',
            desc: '탭 2 라벨',
            selector: '.admin-program-form-tab[data-tab-target="tab-apply"]',
            kind: 'text',
            expected: '신청 정보',
            proto: 'prototype.html L2434',
            severity: 'P0',
        },
        {
            id: 'tabs.terms.label',
            desc: '탭 3 라벨',
            selector: '.admin-program-form-tab[data-tab-target="tab-terms"]',
            kind: 'text',
            expected: '약관 정보',
            proto: 'prototype.html L2435',
            severity: 'P0',
        },
        {
            id: 'tab.info.active.by.default',
            desc: '탭 1 (정보) 기본 활성',
            selector: '#tab-info.admin-program-form-tab-panel--active',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        // ---------------- 탭 1: 프로그램 정보 필드 ----------------
        {
            id: 'field.title',
            desc: '프로그램 제목 입력',
            selector: 'form.admin-program-form input[name="title"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L2452~2454',
            severity: 'P0',
        },
        {
            id: 'field.description',
            desc: '프로그램 설명 입력',
            selector: 'form.admin-program-form input[name="description"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L2457~2458',
            severity: 'P0',
        },
        {
            id: 'field.imageUrl',
            desc: '대표 이미지 URL 입력 (Qn-4 A · 파일 업로드는 A3-2 이월)',
            selector: 'form.admin-program-form input[name="imageUrl"]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'field.category',
            desc: '카테고리 입력',
            selector: 'form.admin-program-form input[name="category"]',
            kind: 'exists',
            expected: true,
            severity: 'P1',
        },
        {
            id: 'field.region',
            desc: '지역 입력',
            selector: 'form.admin-program-form input[name="region"]',
            kind: 'exists',
            expected: true,
            severity: 'P1',
        },
        {
            id: 'field.organization',
            desc: '청년센터(운영기관) 입력 (deviation: prototype 은 select 9종, 본 티켓은 text)',
            selector: 'form.admin-program-form input[name="organization"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L2495~2501 (deviation)',
            severity: 'P0',
        },
        {
            id: 'field.startDate',
            desc: '진행 시작일 date',
            selector: 'form.admin-program-form input[name="startDate"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L2467',
            severity: 'P0',
        },
        {
            id: 'field.endDate',
            desc: '진행 종료일 date',
            selector: 'form.admin-program-form input[name="endDate"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L2469',
            severity: 'P0',
        },
        {
            id: 'field.content',
            desc: '상세 내용 textarea',
            selector: 'form.admin-program-form textarea[name="content"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L2519',
            severity: 'P0',
        },
        // ---------------- 탭 2: 신청 정보 필드 ----------------
        {
            id: 'field.applyStartDate',
            desc: '신청 시작일 (Qn-Δ4 A: 필수)',
            selector: 'form.admin-program-form input[name="applyStartDate"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L2476',
            severity: 'P0',
        },
        {
            id: 'field.applyEndDate',
            desc: '신청 마감일 (Qn-Δ4 A: 필수)',
            selector: 'form.admin-program-form input[name="applyEndDate"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L2478',
            severity: 'P0',
        },
        {
            id: 'field.venue',
            desc: '진행 장소',
            selector: 'form.admin-program-form input[name="venue"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L2486',
            severity: 'P0',
        },
        {
            id: 'field.contact',
            desc: '문의처',
            selector: 'form.admin-program-form input[name="contact"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L2490',
            severity: 'P0',
        },
        {
            id: 'field.capacity',
            desc: '모집 인원',
            selector: 'form.admin-program-form input[name="capacity"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L2506',
            severity: 'P0',
        },
        {
            id: 'field.approvalMode.radio',
            desc: '승인 방식 radio (AUTO/MANUAL 2개)',
            selector: 'form.admin-program-form input[type="radio"][name="approvalMode"]',
            kind: 'count-min',
            expected: 2,
            proto: 'prototype.html L2537~2547',
            severity: 'P0',
        },
        {
            id: 'field.active.checkbox',
            desc: '활성 상태 체크박스 (Qn-Δ6 A: status 수동 편집)',
            selector: 'form.admin-program-form input[type="checkbox"][name="active"]',
            kind: 'exists',
            expected: true,
            severity: 'P1',
        },
        // ---------------- 탭 3: 약관 정보 필드 ----------------
        {
            id: 'field.termsService',
            desc: '이용 약관 textarea',
            selector: 'form.admin-program-form textarea[name="termsService"]',
            kind: 'exists',
            expected: true,
            proto: 'prototype.html L2604 (deviation: 3분류 textarea 로 단순화)',
            severity: 'P0',
        },
        {
            id: 'field.termsPrivacy',
            desc: '개인정보 처리방침 textarea',
            selector: 'form.admin-program-form textarea[name="termsPrivacy"]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'field.termsMarketing',
            desc: '마케팅 수신 약관 textarea',
            selector: 'form.admin-program-form textarea[name="termsMarketing"]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        // ---------------- 액션 ----------------
        {
            id: 'action.cancel',
            desc: '취소 링크',
            selector: '.admin-program-form-actions a.admin-btn.admin-btn--outline',
            kind: 'text',
            expected: '취소',
            proto: 'prototype.html L2613',
            severity: 'P0',
        },
        {
            id: 'action.submit.new',
            desc: '신규 모드 저장 버튼 라벨 "등록"',
            selector: '.admin-program-form-actions button[type="submit"]',
            kind: 'text',
            expected: '등록',
            proto: 'prototype.html L2614',
            severity: 'P0',
        },
        {
            id: 'action.delete.hidden.on.new',
            desc: '신규 모드에서 삭제 버튼 미노출',
            selector: '.admin-program-form-actions .admin-btn--danger',
            kind: 'count',
            expected: 0,
            severity: 'P1',
        },
        {
            id: 'delete.modal.hidden.on.new',
            desc: '신규 모드에서 delete 모달 미노출',
            selector: '#program-delete-modal',
            kind: 'count',
            expected: 0,
            severity: 'P1',
        },
        {
            id: 'sublinks.hidden.on.new',
            desc: '신규 모드에서 F4/F0c 진입 링크 미노출 (id 미존재)',
            selector: '.admin-program-form-sub-links',
            kind: 'count',
            expected: 0,
            severity: 'P1',
        },
    ],
};

export const adminProgramEditContract: ScreenContract = {
    screen: 'admin-program-form-edit',
    path: '/admin/programs/1',
    source: 'admin POLICY + prototype.html L2422~2618 · 2026-09-10 A3-1 (Qn-A A: 상세=편집 폼)',
    viewport: { width: 1440, height: 900 },
    checks: [
        {
            id: 'header.gnb.programs.active',
            desc: '관리자 GNB "프로그램 관리" 활성 (편집 폼에서도)',
            selector: 'nav.admin-header-nav a.admin-nav-link.active',
            kind: 'text',
            expected: '프로그램 관리',
            severity: 'P0',
        },
        {
            id: 'page.title.edit',
            desc: '편집 모드 페이지 타이틀',
            selector: '.admin-program-form-title',
            kind: 'text',
            expected: '프로그램 편집',
            severity: 'P0',
        },
        {
            id: 'edit.title.prefilled',
            desc: '제목 인풋 prefilled',
            selector: 'form.admin-program-form input[name="title"]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'edit.organization.prefilled',
            desc: '청년센터 prefilled',
            selector: 'form.admin-program-form input[name="organization"]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'edit.header.status.badge',
            desc: '상태 뱃지 렌더 (헤더)',
            selector: '.admin-program-form-header-meta .admin-status-badge',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'edit.tabs.count',
            desc: '편집에도 3탭',
            selector: '.admin-program-form-tab',
            kind: 'count-min',
            expected: 3,
            severity: 'P0',
        },
        {
            id: 'edit.action.submit.label',
            desc: '편집 모드 저장 버튼 라벨',
            selector: '.admin-program-form-actions button[type="submit"]',
            kind: 'text',
            expected: '저장',
            severity: 'P0',
        },
        {
            id: 'edit.action.delete.exists',
            desc: '편집 모드 삭제 버튼 노출',
            selector: '.admin-program-form-actions .admin-btn--danger',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'edit.delete.modal.markup',
            desc: '삭제 confirm 모달 markup',
            selector: '#program-delete-modal',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
        {
            id: 'edit.sublink.eligibility',
            desc: 'F4 진입 링크 (Qn-B A: 별도 페이지 유지)',
            selector: '.admin-program-form-sub-links a[href*="/eligibility"]',
            kind: 'exists',
            expected: true,
            proto: 'A3-1 spec Qn-B A',
            severity: 'P0',
        },
        {
            id: 'edit.sublink.dynamic',
            desc: 'F0c 진입 링크 (Qn-B A)',
            selector: '.admin-program-form-sub-links a[href*="/dynamic-fields"]',
            kind: 'exists',
            expected: true,
            severity: 'P0',
        },
    ],
};
