/**
 * 청년센터 화면 (`/centers`) 디자인 계약 — 기계 검사 항목.
 *
 * 추출 기준: docs/00_assets/prototype.tsx L2161~2425 (CentersScreen) / 2026-07-28
 * 서술 계약 (3-column 축·list↔map 상태머신): docs/design-contracts/centers.md
 *
 * 디자인 토큰 (prototype.tsx L10~21):
 *   primary #3F30E9 = rgb(63, 48, 233) / primaryLight oklch(0.93 0.0425 280) / primaryBg oklch(0.96 0.0255 280)
 *   bg oklch(0.985 0.004 280) / border oklch(0.9 0.014 280) / borderLight oklch(0.95 0.007 280)
 *   radius 12 / tagR 20 / headerH 68
 *   Btn size='m' → height 42 · padding 0 20 · fontSize 14 · radius 8 (L85, L97)
 *
 * 상태 매핑 — runner 는 'anon' / 'auth' 두 상태만 지원하므로 이 화면은 다음과 같이 배정한다.
 *   states: ['anon'] → `/centers`            (상세 패널 닫힘. 리스트 360 + 지도)
 *   states: ['auth'] → `/centers/{id}`       (로그인 + 상세 패널 열림. 리스트 240 + 상세 320 + 지도)
 * 갭 리포트의 "로그인" 섹션 = **상세 패널 열림** 상태다. 각 항목 desc 에 `[상세 열림]` 을 붙여 구분한다.
 *
 * 지도 내부(마커·클러스터·인포윈도우)는 계약에서 제외한다 — E2E 헬퍼 `abortExternal()` 이
 * 카카오맵 SDK 도메인을 차단하므로 렌더 자체가 되지 않는다. 컨테이너의 존재·크기만 검사한다.
 */

import type { ScreenContract } from './types';

export const centersContract: ScreenContract = {
    screen: 'centers',
    path: '/centers',
    source: 'prototype.tsx L2161~2425 (CentersScreen), 2026-07-28 추출',
    viewport: { width: 1440, height: 900 },
    checks: [
        // ══ 1. 필터 바 ══════════════════════════════════════════
        {
            id: 'filter.bar.height',
            desc: '필터 바 높이 56',
            selector: '.centers-filter-inner',
            kind: 'box',
            prop: 'height',
            expected: 56,
            proto: 'tsx L2199 (height:56)',
            severity: 'P1',
        },
        {
            id: 'filter.bar.gap',
            desc: '필터 바 항목 간격 12',
            selector: '.centers-filter-form',
            kind: 'css',
            prop: 'column-gap',
            expected: '12px',
            proto: 'tsx L2199 (gap:12)',
            severity: 'P2',
        },
        {
            id: 'filter.bar.borderColor',
            desc: '필터 바 하단 보더는 border 토큰 (borderLight 아님)',
            selector: '.centers-filter-bar',
            kind: 'css',
            prop: 'border-bottom-color',
            expected: 'oklch(0.9 0.014 280)',
            proto: 'tsx L2198 (borderBottom 1px solid T.border)',
            severity: 'P2',
        },
        {
            id: 'filter.search.width',
            desc: '센터명 검색 박스 너비 250',
            selector: '.centers-filter-search',
            kind: 'box',
            prop: 'width',
            expected: 250,
            proto: 'tsx L2201 (width:250)',
            severity: 'P2',
        },
        {
            id: 'filter.search.height',
            desc: '센터명 검색 박스 높이 38',
            selector: '.centers-filter-search',
            kind: 'box',
            prop: 'height',
            expected: 38,
            proto: 'tsx L2201 (height:38)',
            severity: 'P2',
        },
        {
            id: 'filter.search.radius',
            desc: '센터명 검색 박스 radius 8',
            selector: '.centers-filter-search',
            kind: 'css',
            prop: 'border-radius',
            expected: '8px',
            proto: 'tsx L2201 (borderRadius:8)',
            severity: 'P2',
        },
        {
            id: 'filter.search.fontSize',
            desc: '센터명 검색 input 폰트 13',
            selector: '.centers-filter-search',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L2203 (fontSize:13)',
            severity: 'P2',
        },
        {
            id: 'filter.search.icon',
            desc: '검색 박스 내부 좌측 search 아이콘 (lucide SVG)',
            selector: '.centers-filter-search-wrap svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L2202 (<Icon n="search" size={15}>)',
            severity: 'P1',
        },
        {
            id: 'filter.region.trigger.height',
            desc: '지역 드롭다운 트리거 높이 38',
            selector: '.centers-filter-region-trigger',
            kind: 'box',
            prop: 'height',
            expected: 38,
            proto: 'tsx L2209 (height:38)',
            severity: 'P2',
        },
        {
            id: 'filter.region.trigger.minWidth',
            desc: '지역 드롭다운 트리거 최소폭 140',
            selector: '.centers-filter-region-trigger',
            kind: 'css',
            prop: 'min-width',
            expected: '140px',
            proto: 'tsx L2209 (minWidth:140)',
            severity: 'P2',
        },
        {
            id: 'filter.region.trigger.radius',
            desc: '지역 드롭다운 트리거 radius 8',
            selector: '.centers-filter-region-trigger',
            kind: 'css',
            prop: 'border-radius',
            expected: '8px',
            proto: 'tsx L2209 (borderRadius:8)',
            severity: 'P2',
        },
        {
            id: 'filter.region.trigger.fontSize',
            desc: '지역 드롭다운 라벨 폰트 13',
            selector: '.centers-filter-region-text',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L2220 (fontSize:13)',
            severity: 'P2',
        },
        {
            id: 'filter.region.chevron.isSvg',
            desc: '지역 드롭다운 chevron 은 lucide SVG — 텍스트 ▾ 대체 금지',
            selector: '.centers-filter-region-chevron svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L2221 (<Icon n="chevD" size={14}>)',
            severity: 'P1',
        },
        {
            id: 'filter.region.panel.width',
            desc: '지역 드롭다운 패널 너비 260',
            selector: '.centers-filter-region-panel',
            kind: 'css',
            prop: 'width',
            expected: '260px',
            proto: 'tsx L2226 (width:260)',
            severity: 'P2',
        },
        {
            id: 'filter.region.panel.radius',
            desc: '지역 드롭다운 패널 radius 12',
            selector: '.centers-filter-region-panel',
            kind: 'css',
            prop: 'border-radius',
            expected: '12px',
            proto: 'tsx L2226 (borderRadius:12)',
            severity: 'P2',
        },
        {
            id: 'filter.region.list.maxHeight',
            desc: '지역 목록 스크롤 최대 높이 220',
            selector: '.centers-filter-region-list',
            kind: 'css',
            prop: 'max-height',
            expected: '220px',
            proto: 'tsx L2234 (maxHeight:220)',
            severity: 'P2',
        },
        {
            id: 'filter.region.search.isSvg',
            desc: '지역 검색 input 좌측 search 아이콘 (lucide SVG)',
            selector: '.centers-filter-region-panel svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L2229 (<Icon n="search" size={15} color=primary>)',
            severity: 'P2',
        },
        {
            id: 'filter.toggle.track.width',
            desc: '운영중 토글 트랙 너비 40',
            selector: '.centers-filter-toggle-track',
            kind: 'box',
            prop: 'width',
            expected: 40,
            proto: 'tsx L2261 (width:40)',
            severity: 'P2',
        },
        {
            id: 'filter.toggle.track.height',
            desc: '운영중 토글 트랙 높이 22',
            selector: '.centers-filter-toggle-track',
            kind: 'box',
            prop: 'height',
            expected: 22,
            proto: 'tsx L2261 (height:22)',
            severity: 'P2',
        },
        {
            id: 'filter.toggle.handle.width',
            desc: '운영중 토글 손잡이 18',
            selector: '.centers-filter-toggle-handle',
            kind: 'box',
            prop: 'width',
            expected: 18,
            proto: 'tsx L2262 (width:18)',
            severity: 'P2',
        },
        {
            id: 'filter.toggle.label.fontSize',
            desc: '운영중 토글 라벨 폰트 13',
            selector: '.centers-filter-toggle-label',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L2264 (fontSize:13)',
            severity: 'P2',
        },
        {
            id: 'filter.toggle.label.text',
            desc: '운영중 토글 라벨 카피',
            selector: '.centers-filter-toggle-label',
            kind: 'text',
            expected: '운영중만 보기',
            proto: 'tsx L2264',
            severity: 'P1',
        },

        // ══ 2. 3-column 레이아웃 (아키텍처 = P0) ════════════════
        {
            id: 'layout.display',
            desc: '콘텐츠 영역은 가로 flex — 3개 컬럼을 한 줄에 배치',
            selector: '.centers-layout',
            kind: 'css',
            prop: 'display',
            expected: 'flex',
            proto: 'tsx L2269 (display:flex)',
            severity: 'P0',
        },
        {
            id: 'layout.columns',
            desc: '컬럼 3개 = 리스트 + 인라인 상세 + 지도',
            selector: '.centers-layout > *',
            kind: 'count',
            expected: 3,
            proto: 'tsx L2270 / L2319 / L2352',
            severity: 'P0',
        },
        {
            id: 'layout.detail.isInline',
            desc: '상세는 레이아웃 안의 인라인 패널 — 별도 라우트 전용 화면이 아님',
            selector: '.centers-layout > .centers-detail-col',
            kind: 'exists',
            expected: true,
            proto: 'tsx L2320 (detailCenter && <div .../> 형제 컬럼)',
            severity: 'P0',
        },
        {
            id: 'layout.list.width',
            desc: '리스트 컬럼 폭 360 (상세 닫힘)',
            selector: '.centers-list-col',
            kind: 'box',
            prop: 'width',
            expected: 360,
            proto: 'tsx L2271 (width: detailId?240:360)',
            severity: 'P0',
        },
        {
            id: 'layout.detail.width',
            desc: '상세 패널 폭 320 고정',
            selector: '.centers-detail-col',
            kind: 'css',
            prop: 'width',
            expected: '320px',
            proto: 'tsx L2321 (width:320, flexShrink:0)',
            severity: 'P0',
        },
        {
            id: 'layout.map.flexGrow',
            desc: '지도 컬럼이 남는 폭을 모두 차지 (flex:1)',
            selector: '.centers-map-panel',
            kind: 'css',
            prop: 'flex-grow',
            expected: '1',
            proto: 'tsx L2353 (flex:1)',
            severity: 'P0',
        },
        {
            id: 'layout.gap',
            desc: '컬럼 간격 16',
            selector: '.centers-layout',
            kind: 'css',
            prop: 'column-gap',
            expected: '16px',
            proto: 'tsx L2269 (gap:16)',
            severity: 'P1',
        },
        {
            id: 'layout.alignItems',
            desc: '컬럼 상단 정렬 — 리스트가 지도 높이만큼 늘어나면 안 됨',
            selector: '.centers-layout',
            kind: 'css',
            prop: 'align-items',
            expected: 'flex-start',
            proto: 'tsx L2269 (alignItems:flex-start)',
            severity: 'P1',
        },
        {
            id: 'layout.paddingTop',
            desc: '콘텐츠 상단 여백 16 은 컨테이너가 담당 — 레이아웃에 16 중복 금지',
            selector: '.centers-layout',
            kind: 'css',
            prop: 'padding-top',
            expected: '0px',
            proto: 'tsx L2269 (padding:16px 80px 40px — 상단 총합 16)',
            severity: 'P2',
        },
        {
            id: 'layout.listTransition',
            desc: '리스트 폭 360↔240 전환 250ms ease',
            selector: '.centers-list-col',
            kind: 'css',
            prop: 'transition',
            // Chrome 은 기본 timing-function(ease) 을 computed 값에서 생략한다 → 'width 0.25s'
            expected: 'width 0.25s',
            proto: 'tsx L2271 (transition: width 250ms ease)',
            severity: 'P2',
        },

        // ══ 3. 지도 컬럼 (컨테이너만 — 내부는 계약 제외) ════════
        {
            id: 'map.panel.height',
            desc: '지도 패널 높이 640',
            selector: '.centers-map-panel',
            kind: 'box',
            prop: 'height',
            expected: 640,
            proto: 'tsx L2353 (height:640, minHeight:640)',
            severity: 'P1',
        },
        {
            id: 'map.panel.radius',
            desc: '지도 패널 radius 12',
            selector: '.centers-map-panel',
            kind: 'css',
            prop: 'border-radius',
            expected: '12px',
            proto: 'tsx L2353 (borderRadius:T.radius)',
            severity: 'P2',
        },
        {
            id: 'map.container.height',
            desc: '지도 캔버스가 패널 전체 높이(640)를 채움',
            selector: '#center-map',
            kind: 'box',
            prop: 'height',
            expected: 640,
            proto: 'tsx L2355 (height:100%)',
            severity: 'P1',
        },
        {
            id: 'map.searchHere.exists',
            desc: '"이 지역에서 검색" floating 버튼',
            selector: '.centers-map-search-here',
            kind: 'exists',
            expected: true,
            proto: 'tsx L2382~2386',
            severity: 'P1',
        },
        {
            id: 'map.searchHere.isSvg',
            desc: '"이 지역에서 검색" 좌측 refresh 아이콘 (SVG)',
            selector: '.centers-map-search-here svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L2384 (<Icon n="refresh" size={14}>)',
            severity: 'P2',
        },
        {
            id: 'map.searchHere.radius',
            desc: '"이 지역에서 검색" pill radius 20 (tagR)',
            selector: '.centers-map-search-here',
            kind: 'css',
            prop: 'border-radius',
            expected: '20px',
            proto: 'tsx L2383 (borderRadius:T.tagR)',
            severity: 'P2',
        },
        {
            id: 'map.mockLabel',
            desc: '지도 우하단 "카카오맵 API 연동 예정" 라벨',
            selector: '.center-map-mock-label',
            kind: 'exists',
            expected: true,
            proto: 'tsx L2389~2391',
            severity: 'P2',
            deviation:
                'prototype 은 SVG 목업 지도라 연동 예정 라벨을 달았음. 구현은 실제 카카오맵 SDK 연동 완료 → 라벨 불필요 (F0h)',
        },

        // ══ 4. 리스트 컬럼 헤더 ═════════════════════════════════
        {
            id: 'list.count.fontSize',
            desc: '"총 N개 센터" 폰트 13',
            selector: '.centers-list-count',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L2273 (fontSize:13)',
            severity: 'P2',
        },
        {
            id: 'list.sort.count',
            desc: '정렬 pill 2개 (이름순 / 프로그램많은순)',
            selector: '.centers-sort-pill-item',
            kind: 'count',
            expected: 2,
            proto: 'tsx L2276',
            severity: 'P1',
        },
        {
            id: 'list.sort.wrap.background',
            desc: '정렬 pill 컨테이너는 배경 없음 — 개별 pill 만 active 배경',
            selector: '.centers-sort-pill',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgba(0, 0, 0, 0)',
            proto: 'tsx L2275 (display:flex, gap:4 — 배경 미지정)',
            severity: 'P2',
        },
        {
            id: 'list.sort.gap',
            desc: '정렬 pill 간격 4',
            selector: '.centers-sort-pill',
            kind: 'css',
            prop: 'column-gap',
            expected: '4px',
            proto: 'tsx L2275 (gap:4)',
            severity: 'P2',
        },
        {
            id: 'list.sort.item.fontSize',
            desc: '정렬 pill 폰트 12',
            selector: '.centers-sort-pill-item',
            kind: 'css',
            prop: 'font-size',
            expected: '12px',
            proto: 'tsx L2277 (fontSize:12)',
            severity: 'P2',
        },
        {
            id: 'list.sort.item.radius',
            desc: '정렬 pill radius 20 (tagR)',
            selector: '.centers-sort-pill-item',
            kind: 'css',
            prop: 'border-radius',
            expected: '20px',
            proto: 'tsx L2277 (borderRadius:T.tagR)',
            severity: 'P2',
        },
        {
            id: 'list.scroll.maxHeight',
            desc: '리스트 스크롤 영역 최대 높이 600',
            selector: '.centers-list-scroll',
            kind: 'css',
            prop: 'max-height',
            expected: '600px',
            proto: 'tsx L2282 (maxHeight:600)',
            severity: 'P2',
        },
        {
            id: 'list.scroll.gap',
            desc: '카드 세로 간격 8',
            selector: '.centers-list-scroll',
            kind: 'css',
            prop: 'row-gap',
            expected: '8px',
            proto: 'tsx L2282 (gap:8)',
            severity: 'P2',
        },

        // ══ 5. 센터 카드 (full 모드) ════════════════════════════
        {
            id: 'card.radius',
            desc: '카드 radius 12',
            selector: '.center-card',
            kind: 'css',
            prop: 'border-radius',
            expected: '12px',
            proto: 'tsx L2287 (borderRadius:T.radius)',
            severity: 'P2',
        },
        // 카드 보더 1.5px (tsx L2287) 는 계약에 넣지 않는다 — Chrome 이 computed border-width 를
        // 디바이스 픽셀로 반올림해 dpr=1 에서 항상 '1px' 로 보고한다. prototype 도 동일하게 렌더되므로
        // 이 값으로는 갭을 판별할 수 없다. docs/design-contracts/centers.md §6 참조.
        {
            id: 'card.padding',
            desc: '카드 패딩 14 (full 모드)',
            selector: '.center-card-full',
            kind: 'css',
            prop: 'padding-top',
            expected: '14px',
            proto: "tsx L2287 (padding: detailId?'10px 12px':'14px')",
            severity: 'P2',
        },
        {
            id: 'card.name.fontSize',
            desc: '카드 센터명 폰트 15',
            selector: '.center-card-name',
            kind: 'css',
            prop: 'font-size',
            expected: '15px',
            proto: 'tsx L2303 (fontSize:15)',
            severity: 'P2',
        },
        {
            id: 'card.name.fontWeight',
            desc: '카드 센터명 weight 700',
            selector: '.center-card-name',
            kind: 'css',
            prop: 'font-weight',
            expected: '700',
            proto: 'tsx L2303 (fontWeight:700)',
            severity: 'P2',
        },
        {
            id: 'card.head.gap',
            desc: '센터명–배지 간격 7',
            selector: '.center-card-head',
            kind: 'css',
            prop: 'column-gap',
            expected: '7px',
            proto: 'tsx L2302 (gap:7)',
            severity: 'P2',
        },
        {
            id: 'card.badge.fontSize',
            desc: '운영 배지 폰트 11',
            selector: '.center-card-full .center-card-badge',
            kind: 'css',
            prop: 'font-size',
            expected: '11px',
            proto: 'tsx L2304 (fontSize:11)',
            severity: 'P2',
        },
        {
            id: 'card.badge.radius',
            desc: '운영 배지 radius 20 (tagR)',
            selector: '.center-card-full .center-card-badge',
            kind: 'css',
            prop: 'border-radius',
            expected: '20px',
            proto: 'tsx L2304 (borderRadius:T.tagR)',
            severity: 'P2',
        },
        {
            id: 'card.badge.padding',
            desc: '운영 배지 패딩 2px 7px',
            selector: '.center-card-full .center-card-badge',
            kind: 'css',
            prop: 'padding-left',
            expected: '7px',
            proto: "tsx L2304 (padding:'2px 7px')",
            severity: 'P2',
        },
        {
            id: 'card.address.fontSize',
            desc: '카드 주소 폰트 12',
            selector: '.center-card-address',
            kind: 'css',
            prop: 'font-size',
            expected: '12px',
            proto: 'tsx L2307 (fontSize:12)',
            severity: 'P2',
        },
        {
            id: 'card.address.marginBottom',
            desc: '카드 주소 하단 여백 6',
            selector: '.center-card-address',
            kind: 'css',
            prop: 'margin-bottom',
            expected: '6px',
            proto: 'tsx L2307 (marginBottom:6)',
            severity: 'P2',
        },
        {
            id: 'card.foot.paddingTop',
            desc: '카드 푸터 상단 여백 8 + 구분선',
            selector: '.center-card-foot',
            kind: 'css',
            prop: 'padding-top',
            expected: '8px',
            proto: 'tsx L2308 (paddingTop:8, borderTop)',
            severity: 'P2',
        },
        {
            id: 'card.programs.color',
            desc: '"프로그램 N건" primary 색',
            selector: '.center-card-programs',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(63, 48, 233)',
            proto: 'tsx L2309 (color:T.primary)',
            severity: 'P2',
        },
        {
            id: 'card.more.text',
            desc: '카드 우하단 "상세보기 →"',
            selector: '.center-card-more',
            kind: 'text',
            expected: '상세보기 →',
            proto: 'tsx L2310',
            severity: 'P1',
        },

        // ══ 6. [상세 열림] 리스트 compact 전환 ══════════════════
        {
            id: 'detail.list.width',
            desc: '[상세 열림] 리스트 컬럼 240 으로 축소',
            selector: '.centers-list-col',
            kind: 'box',
            prop: 'width',
            expected: 240,
            proto: 'tsx L2271 (width: detailId?240:360)',
            severity: 'P0',
            states: ['auth'],
        },
        {
            id: 'detail.panel.width',
            desc: '[상세 열림] 상세 패널 실제 렌더 폭 320',
            selector: '.centers-detail-col',
            kind: 'box',
            prop: 'width',
            expected: 320,
            proto: 'tsx L2321 (width:320)',
            severity: 'P0',
            states: ['auth'],
        },
        {
            id: 'detail.sort.hidden',
            desc: '[상세 열림] 정렬 pill 숨김 (!detailId 조건)',
            selector: '.centers-sort-pill',
            kind: 'count',
            expected: 0,
            proto: 'tsx L2274 (!detailId && ...)',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'detail.card.compact.exists',
            desc: '[상세 열림] 카드가 compact 모드로 전환',
            selector: '.center-card-compact',
            kind: 'exists',
            expected: true,
            proto: 'tsx L2288~2298 (detailId ? compact : full)',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'detail.card.compact.padding',
            desc: '[상세 열림] compact 카드 패딩 10px 12px',
            selector: '.center-card-compact',
            kind: 'css',
            prop: 'padding-top',
            expected: '10px',
            proto: "tsx L2287 (padding:'10px 12px')",
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.card.compact.icon.size',
            desc: '[상세 열림] compact 카드 pin 아이콘 박스 30',
            selector: '.center-card-compact-icon',
            kind: 'box',
            prop: 'width',
            expected: 30,
            proto: 'tsx L2290 (width:30, height:30)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.card.compact.icon.radius',
            desc: '[상세 열림] compact 카드 아이콘 박스 radius 6',
            selector: '.center-card-compact-icon',
            kind: 'css',
            prop: 'border-radius',
            expected: '6px',
            proto: 'tsx L2290 (borderRadius:6)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.card.compact.icon.isSvg',
            desc: '[상세 열림] compact 카드 아이콘은 lucide pin SVG',
            selector: '.center-card-compact-icon svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L2291 (<Icon n="pin" size={15}>)',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'detail.card.compact.name.fontSize',
            desc: '[상세 열림] compact 카드 센터명 폰트 13',
            selector: '.center-card-compact-name',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L2294 (fontSize:13)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.card.compact.region.fontSize',
            desc: '[상세 열림] compact 카드 지역 폰트 11',
            selector: '.center-card-compact-region',
            kind: 'css',
            prop: 'font-size',
            expected: '11px',
            proto: 'tsx L2295 (fontSize:11)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.card.compact.badge.text',
            desc: '[상세 열림] compact 배지는 "종료" (full 은 "운영종료")',
            selector: '.center-card-compact .center-card-badge.inactive',
            kind: 'text',
            expected: '종료',
            proto: "tsx L2297 (c.open?'운영중':'종료')",
            severity: 'P2',
            states: ['auth'],
            deviation:
                '구현은 full/compact 모두 "운영종료" 로 통일. 카피 차이는 계약에서 제외 (2026-07-28 사용자 확정)',
        },

        // ══ 7. [상세 열림] 상세 패널 내부 ═══════════════════════
        {
            id: 'detail.image.height',
            desc: '[상세 열림] 상세 이미지 높이 160',
            selector: '.centers-detail-image',
            kind: 'box',
            prop: 'height',
            expected: 160,
            proto: 'tsx L2322 (height:160)',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'detail.close.size',
            desc: '[상세 열림] 닫기 버튼 28x28',
            selector: '.centers-detail-close',
            kind: 'box',
            prop: 'width',
            expected: 28,
            proto: 'tsx L2325 (width:28, height:28)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.close.isSvg',
            desc: '[상세 열림] 닫기 아이콘은 lucide close SVG — × 문자 금지',
            selector: '.centers-detail-close svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L2326 (<Icon n="close" size={14} color="#fff">)',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'detail.badge.fontSize',
            desc: '[상세 열림] 이미지 위 운영 배지 폰트 11',
            selector: '.centers-detail-image-badge',
            kind: 'css',
            prop: 'font-size',
            expected: '11px',
            proto: 'tsx L2328 (fontSize:11)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.badge.radius',
            desc: '[상세 열림] 이미지 위 운영 배지 radius 20 (tagR)',
            selector: '.centers-detail-image-badge',
            kind: 'css',
            prop: 'border-radius',
            expected: '20px',
            proto: 'tsx L2328 (borderRadius:T.tagR)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.body.paddingLeft',
            desc: '[상세 열림] 상세 본문 좌우 패딩 18 (상하 16)',
            selector: '.centers-detail-body',
            kind: 'css',
            prop: 'padding-left',
            expected: '18px',
            proto: "tsx L2330 (padding:'16px 18px')",
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.name.fontSize',
            desc: '[상세 열림] 센터명 폰트 17',
            selector: '.centers-detail-name',
            kind: 'css',
            prop: 'font-size',
            expected: '17px',
            proto: 'tsx L2331 (fontSize:17)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.name.marginBottom',
            desc: '[상세 열림] 센터명 하단 여백 4',
            selector: '.centers-detail-head',
            kind: 'css',
            prop: 'margin-bottom',
            expected: '4px',
            proto: 'tsx L2331 (marginBottom:4)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.desc.fontSize',
            desc: '[상세 열림] 센터 소개 폰트 13',
            selector: '.centers-detail-desc',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L2332 (fontSize:13)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.desc.lineHeight',
            desc: '[상세 열림] 센터 소개 line-height 1.6 (=20.8px)',
            selector: '.centers-detail-desc',
            kind: 'css',
            prop: 'line-height',
            expected: '20.8px',
            proto: 'tsx L2332 (lineHeight:1.6)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.meta.rowCount',
            desc: '[상세 열림] 메타 3행 (주소·운영시간·연락처)',
            selector: '.centers-detail-meta-row',
            kind: 'count',
            expected: 3,
            proto: "tsx L2334 ([['pin',addr],['calendar',hours],['user',tel]])",
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'detail.meta.gap',
            desc: '[상세 열림] 메타 행 간격 8',
            selector: '.centers-detail-meta',
            kind: 'css',
            prop: 'row-gap',
            expected: '8px',
            proto: 'tsx L2333 (gap:8)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.meta.marginBottom',
            desc: '[상세 열림] 메타 블록 하단 여백 14',
            selector: '.centers-detail-meta',
            kind: 'css',
            prop: 'margin-bottom',
            expected: '14px',
            proto: 'tsx L2333 (marginBottom:14)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.meta.badge.size',
            desc: '[상세 열림] 메타 아이콘 박스 26x26',
            selector: '.centers-detail-meta-badge',
            kind: 'box',
            prop: 'width',
            expected: 26,
            proto: 'tsx L2336 (width:26, height:26)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.meta.badge.radius',
            desc: '[상세 열림] 메타 아이콘 박스 radius 6',
            selector: '.centers-detail-meta-badge',
            kind: 'css',
            prop: 'border-radius',
            expected: '6px',
            proto: 'tsx L2336 (borderRadius:6)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.meta.badge.background',
            desc: '[상세 열림] 메타 아이콘 박스 배경 primaryLight (primaryBg 아님)',
            selector: '.centers-detail-meta-badge',
            kind: 'css',
            prop: 'background-color',
            expected: 'oklch(0.93 0.0425 280)',
            proto: 'tsx L2336 (background:T.primaryLight)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.meta.badge.isSvg',
            desc: '[상세 열림] 메타 아이콘은 lucide SVG (pin/calendar/user)',
            selector: '.centers-detail-meta-badge svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L2337 (<Icon n={icon} size={13}>)',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'detail.meta.value.fontSize',
            desc: '[상세 열림] 메타 값 텍스트 폰트 12',
            selector: '.centers-detail-meta-row > span:not(.centers-detail-meta-badge)',
            kind: 'css',
            prop: 'font-size',
            expected: '12px',
            proto: 'tsx L2339 (fontSize:12)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.programs.radius',
            desc: '[상세 열림] "진행중인 프로그램" 박스 radius 8',
            selector: '.centers-detail-programs',
            kind: 'css',
            prop: 'border-radius',
            expected: '8px',
            proto: 'tsx L2343 (borderRadius:8)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.programs.background',
            desc: '[상세 열림] "진행중인 프로그램" 박스 배경 bg 토큰',
            selector: '.centers-detail-programs',
            kind: 'css',
            prop: 'background-color',
            expected: 'oklch(0.985 0.004 280)',
            proto: 'tsx L2343 (background:T.bg)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.programs.label.fontSize',
            desc: '[상세 열림] "진행중인 프로그램" 라벨 폰트 12',
            selector: '.centers-detail-programs-label',
            kind: 'css',
            prop: 'font-size',
            expected: '12px',
            proto: 'tsx L2344 (fontSize:12)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.programs.count.fontSize',
            desc: '[상세 열림] 프로그램 건수 폰트 20',
            selector: '.centers-detail-programs-count',
            kind: 'css',
            prop: 'font-size',
            expected: '20px',
            proto: 'tsx L2345 (fontSize:20)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.cta.height',
            desc: '[상세 열림] CTA 버튼 높이 42 (Btn size="m")',
            selector: '.centers-detail-cta',
            kind: 'box',
            prop: 'height',
            expected: 42,
            proto: 'tsx L2347 + L85 (sizes.m.h = 42)',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'detail.cta.fontSize',
            desc: '[상세 열림] CTA 버튼 폰트 14 (Btn size="m")',
            selector: '.centers-detail-cta',
            kind: 'css',
            prop: 'font-size',
            expected: '14px',
            proto: 'tsx L2347 + L85 (sizes.m.fs = 14)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.cta.radius',
            desc: '[상세 열림] CTA 버튼 radius 8',
            selector: '.centers-detail-cta',
            kind: 'css',
            prop: 'border-radius',
            expected: '8px',
            proto: 'tsx L97 (Btn borderRadius:8)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.cta.background',
            desc: '[상세 열림] CTA 버튼 배경 primary',
            selector: '.centers-detail-cta',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgb(63, 48, 233)',
            proto: 'tsx L88 (variant primary bg:T.primary)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'detail.cta.text',
            desc: '[상세 열림] CTA 카피',
            selector: '.centers-detail-cta',
            kind: 'text',
            expected: '프로그램 전체보기',
            proto: 'tsx L2347',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'detail.map.flexGrow',
            desc: '[상세 열림] 지도는 여전히 flex:1 — 상세가 열려도 3-column 유지',
            selector: '.centers-map-panel',
            kind: 'css',
            prop: 'flex-grow',
            expected: '1',
            proto: 'tsx L2353 (flex:1)',
            severity: 'P0',
            states: ['auth'],
        },
        {
            id: 'detail.map.height',
            desc: '[상세 열림] 지도 높이 640 유지',
            selector: '.centers-map-panel',
            kind: 'box',
            prop: 'height',
            expected: 640,
            proto: 'tsx L2353 (height:640)',
            severity: 'P1',
            states: ['auth'],
        },
    ],
};
