/**
 * 전 페이지 공통 헤더·푸터 디자인 계약 — 기계 검사 항목.
 *
 * 추출 기준: docs/00_assets/prototype.tsx
 *   - Header        L402~464
 *   - Footer        L467~496
 *   - Avatar        L368~377   (size*0.42 = 이니셜 폰트)
 *   - UserMenuPanel L380~399
 *   - NotifPanel    L322~364
 *   - 디자인 토큰 T L10~21     (headerH 68 / tagR 20 / radius 12)
 * 추출일: 2026-07-28
 *
 * 서술 계약 (전환 애니메이션·드롭다운 열림 동작·hover): docs/design-contracts/common.md
 *
 * 왜 계약이 2개인가 —
 *   Header 는 `transparent = isHome && !scrolled` (proto L406) 로 **두 벌의 시각 규격**을 갖는다.
 *   일반 모드(흰 배경)는 `/programs` 에서, transparent 모드는 `/` 최상단에서만 관측 가능하므로
 *   경로가 다른 두 계약으로 쪼갠다.
 *     - commonContract      → `/programs` (일반 헤더 + 푸터 전체)
 *     - commonHomeContract  → `/`         (transparent 헤더 색상 규격만)
 *
 * 색상 참조 (proto L11~17):
 *   primary #3F30E9 = rgb(63, 48, 233) / error #EF4444 = rgb(239, 68, 68)
 *   푸터 배경 #F5F5F5 = rgb(245, 245, 245) / 푸터 링크 #444 / 카피라이트 #888
 */

import type { Check, ScreenContract } from './types';

/** 로그인 검사에 쓰는 시드 유저 (e2e/helpers.ts seedEmail(1)) — DataInitializer 가 "시드유저N" 으로 생성 */
const SEED_USER_NAME = '시드유저1';

// ─────────────────────────────────────────────────────────────
// 1. 헤더 — 일반 모드 (`/programs`)
// ─────────────────────────────────────────────────────────────
const headerChecks: Check[] = [
    // ── 골격 ────────────────────────────────────────────────
    {
        id: 'header.height',
        desc: '헤더 높이 68 (T.headerH)',
        selector: '.site-header',
        kind: 'box',
        prop: 'height',
        expected: 68,
        proto: 'tsx L415 (height:T.headerH) / L20',
        severity: 'P0',
    },
    {
        id: 'header.background',
        desc: '일반 모드 헤더 배경 = surface(#fff)',
        selector: '.site-header',
        kind: 'css',
        prop: 'background-color',
        expected: 'rgb(255, 255, 255)',
        proto: 'tsx L415 (background:T.surface)',
        severity: 'P1',
    },
    {
        id: 'header.borderBottom',
        desc: '일반 모드 헤더 하단 1px border',
        selector: '.site-header',
        kind: 'css',
        prop: 'border-bottom-width',
        expected: '1px',
        proto: 'tsx L415 (borderBottom:1px solid T.border)',
        severity: 'P2',
    },
    {
        id: 'header.boxShadow',
        desc: '일반 모드 헤더 그림자 0 1px 8px rgba(0,0,0,0.06) — 브랜드 틴트 shadow-sm 이 아님',
        selector: '.site-header',
        kind: 'css',
        prop: 'box-shadow',
        expected: 'rgba(0, 0, 0, 0.06) 0px 1px 8px 0px',
        proto: 'tsx L415 (boxShadow)',
        severity: 'P2',
        deviation:
            'POLICY.md P-2 — 그림자는 브랜드 틴트 토큰(--shadow-*) 유지. prototype 은 헤더·알림패널만 중립 검정을 쓰는데 두 곳만 예외를 두면 토큰 체계에 구멍이 생긴다',
    },
    {
        id: 'header.padding',
        desc: '헤더 좌우 패딩 80',
        selector: '.header-inner',
        kind: 'css',
        prop: 'padding-left',
        expected: '80px',
        proto: 'tsx L415 (padding:0 80px)',
        severity: 'P2',
    },

    // ── 로고 ────────────────────────────────────────────────
    {
        id: 'header.logo.wrap.flex',
        desc: '로고 영역 flex:1 — nav 를 정확히 중앙에 두기 위한 3분할 구조',
        selector: '.header-logo-wrap',
        kind: 'css',
        prop: 'flex-grow',
        expected: '1',
        proto: 'tsx L417 (flex:1)',
        severity: 'P1',
    },
    {
        id: 'header.logo.gap',
        desc: '로고 심볼–텍스트 간격 8',
        selector: '.header-logo',
        kind: 'css',
        prop: 'column-gap',
        expected: '8px',
        proto: 'tsx L418 (gap:8)',
        severity: 'P2',
    },
    {
        id: 'header.logo.img.height',
        desc: '로고 심볼 높이 34',
        selector: '.header-logo-img',
        kind: 'box',
        prop: 'height',
        expected: 34,
        proto: 'tsx L419 (height:34)',
        severity: 'P2',
    },
    {
        id: 'header.logo.text.fontSize',
        desc: '로고 워드마크 폰트 18',
        selector: '.header-logo-text',
        kind: 'css',
        prop: 'font-size',
        expected: '18px',
        proto: 'tsx L420 (fontSize:18)',
        severity: 'P2',
    },
    {
        id: 'header.logo.text.fontWeight',
        desc: '로고 워드마크 weight 800',
        selector: '.header-logo-text',
        kind: 'css',
        prop: 'font-weight',
        expected: '800',
        proto: 'tsx L420 (fontWeight:800)',
        severity: 'P2',
    },
    {
        id: 'header.logo.text.letterSpacing',
        desc: '로고 워드마크 자간 -0.3',
        selector: '.header-logo-text',
        kind: 'css',
        prop: 'letter-spacing',
        expected: '-0.3px',
        proto: 'tsx L420 (letterSpacing:-0.3)',
        severity: 'P2',
    },
    {
        id: 'header.logo.text.color',
        desc: '일반 모드 로고 워드마크 = primary',
        selector: '.header-logo-text',
        kind: 'css',
        prop: 'color',
        expected: 'rgb(63, 48, 233)',
        proto: 'tsx L420 (color:T.primary)',
        severity: 'P2',
    },

    // ── 네비게이션 (정보구조 — 카피 예외 아님) ──────────────
    {
        id: 'header.nav.count',
        desc: '주 네비 3개 — 프로그램 / 청년센터 / 공지사항',
        selector: '.header-nav .nav-link',
        kind: 'count',
        expected: 3,
        proto: 'tsx L409~413 (nav 배열)',
        severity: 'P0',
    },
    {
        id: 'header.nav.1.label',
        desc: '네비 1번 = 프로그램',
        selector: '.header-nav .nav-link:nth-child(1)',
        kind: 'text',
        expected: '프로그램',
        proto: 'tsx L410',
        severity: 'P1',
    },
    {
        id: 'header.nav.2.label',
        desc: '네비 2번 = 청년센터',
        selector: '.header-nav .nav-link:nth-child(2)',
        kind: 'text',
        expected: '청년센터',
        proto: 'tsx L411',
        severity: 'P1',
    },
    {
        id: 'header.nav.3.label',
        desc: '네비 3번 = 공지사항',
        selector: '.header-nav .nav-link:nth-child(3)',
        kind: 'text',
        expected: '공지사항',
        proto: 'tsx L412',
        severity: 'P1',
    },
    {
        id: 'header.nav.gap',
        desc: '네비 항목 간격 36',
        selector: '.header-nav',
        kind: 'css',
        prop: 'column-gap',
        expected: '36px',
        proto: 'tsx L424 (gap:36)',
        severity: 'P2',
    },
    {
        id: 'header.nav.fontSize',
        desc: '네비 폰트 15',
        selector: '.header-nav .nav-link',
        kind: 'css',
        prop: 'font-size',
        expected: '15px',
        proto: 'tsx L426 (fontSize:15)',
        severity: 'P2',
    },
    {
        id: 'header.nav.inactive.fontWeight',
        desc: '비활성 네비 weight 400',
        selector: '.header-nav .nav-link:not(.active)',
        kind: 'css',
        prop: 'font-weight',
        expected: '400',
        proto: 'tsx L426 (fontWeight: screen===n.screen?600:400)',
        severity: 'P2',
    },
    {
        id: 'header.nav.active.exists',
        desc: '현재 화면 네비에 활성 표식 (`/programs` 진입 시 프로그램)',
        selector: '.header-nav .nav-link.active',
        kind: 'exists',
        expected: true,
        proto: 'tsx L426 (screen===n.screen 분기)',
        severity: 'P0',
    },
    {
        id: 'header.nav.active.fontWeight',
        desc: '활성 네비 weight 600',
        selector: '.header-nav .nav-link.active',
        kind: 'css',
        prop: 'font-weight',
        expected: '600',
        proto: 'tsx L426',
        severity: 'P2',
    },
    {
        id: 'header.nav.active.underline',
        desc: '활성 네비 하단 2px 언더라인',
        selector: '.header-nav .nav-link.active',
        kind: 'css',
        prop: 'border-bottom-width',
        expected: '2px',
        proto: 'tsx L426 (borderBottom:2px solid)',
        severity: 'P2',
    },
    {
        id: 'header.nav.active.color',
        desc: '일반 모드 활성 네비 = primary',
        selector: '.header-nav .nav-link.active',
        kind: 'css',
        prop: 'color',
        expected: 'rgb(63, 48, 233)',
        proto: 'tsx L426',
        severity: 'P2',
    },
    {
        id: 'header.nav.paddingBottom',
        desc: '네비 하단 패딩 4 (언더라인 간격)',
        selector: '.header-nav .nav-link',
        kind: 'css',
        prop: 'padding-bottom',
        expected: '4px',
        proto: 'tsx L426 (paddingBottom:4)',
        severity: 'P2',
    },

    // ── 우측 액션 영역 ──────────────────────────────────────
    {
        id: 'header.right.flex',
        desc: '우측 영역 flex:1 (로고 영역과 대칭 → nav 중앙 고정)',
        selector: '.header-right',
        kind: 'css',
        prop: 'flex-grow',
        expected: '1',
        proto: 'tsx L430 (flex:1)',
        severity: 'P1',
    },
    {
        id: 'header.right.gap',
        desc: '우측 액션 간격 16',
        selector: '.header-right',
        kind: 'css',
        prop: 'column-gap',
        expected: '16px',
        proto: 'tsx L430 (gap:16)',
        severity: 'P2',
    },
    {
        id: 'header.right.justify',
        desc: '우측 액션 우측 정렬',
        selector: '.header-right',
        kind: 'css',
        prop: 'justify-content',
        expected: 'flex-end',
        proto: 'tsx L430 (justifyContent:flex-end)',
        severity: 'P2',
    },
    {
        id: 'header.search.exists',
        desc: '검색 아이콘 (전 상태 공통)',
        selector: '.header-right a[aria-label="검색"]',
        kind: 'exists',
        expected: true,
        proto: 'tsx L431 (Icon n="search")',
        severity: 'P0',
    },
    {
        id: 'header.search.size',
        desc: '검색 아이콘 20x20',
        selector: '.header-right a[aria-label="검색"] svg',
        kind: 'box',
        prop: 'width',
        expected: 20,
        proto: 'tsx L431 (size=20)',
        severity: 'P2',
    },

    // ── 비로그인: 로그인 아이콘 ─────────────────────────────
    {
        id: 'header.login.exists',
        desc: '비로그인 시 로그인 아이콘 1개 (버튼 아닌 아이콘)',
        selector: '.header-right a[aria-label="로그인"]',
        kind: 'exists',
        expected: true,
        proto: 'tsx L459 (Icon n="login")',
        severity: 'P0',
    },
    {
        id: 'header.login.size',
        desc: '로그인 아이콘 21x21 (검색 20 과 다름)',
        selector: '.header-right a[aria-label="로그인"] svg',
        kind: 'box',
        prop: 'width',
        expected: 21,
        proto: 'tsx L459 (size=21)',
        severity: 'P2',
    },
    {
        id: 'header.login.color',
        desc: '일반 모드 로그인 아이콘 = primary',
        selector: '.header-right a[aria-label="로그인"]',
        kind: 'css',
        prop: 'color',
        expected: 'rgb(63, 48, 233)',
        proto: 'tsx L459 (color: transparent?#fff:T.primary)',
        severity: 'P2',
    },
    {
        id: 'header.anon.noBell',
        desc: '비로그인 시 알림 종 없음',
        selector: '.header-bell-trigger',
        kind: 'exists',
        expected: false,
        proto: 'tsx L432 (isLoggedIn && …)',
        severity: 'P1',
    },
    {
        id: 'header.anon.noUserMenu',
        desc: '비로그인 시 유저 메뉴 없음',
        selector: '.header-user-trigger',
        kind: 'exists',
        expected: false,
        proto: 'tsx L445 (isLoggedIn ? … : Icon login)',
        severity: 'P1',
    },

    // ── 로그인: 알림 종 ─────────────────────────────────────
    {
        id: 'header.bell.exists',
        desc: '로그인 시 알림 종 트리거',
        selector: '.header-bell-trigger',
        kind: 'exists',
        expected: true,
        proto: 'tsx L434~437',
        severity: 'P0',
        states: ['auth'],
    },
    {
        id: 'header.bell.size',
        desc: '종 아이콘 20x20',
        selector: '.header-bell-trigger svg',
        kind: 'box',
        prop: 'width',
        expected: 20,
        proto: 'tsx L435 (size=20)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'header.bell.dot.exists',
        desc: '종 우상단 미읽음 dot',
        selector: '.header-bell-dot',
        kind: 'exists',
        expected: true,
        proto: 'tsx L436',
        severity: 'P1',
        states: ['auth'],
    },
    {
        id: 'header.bell.dot.width',
        desc: 'dot 지름 7 (hidden 상태에서도 계산되도록 css 로 측정)',
        selector: '.header-bell-dot',
        kind: 'css',
        prop: 'width',
        expected: '7px',
        proto: 'tsx L436 (width:7)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'header.bell.dot.top',
        desc: 'dot 위치 top -2 (아이콘 밖으로 살짝 나감)',
        selector: '.header-bell-dot',
        kind: 'css',
        prop: 'top',
        expected: '-2px',
        proto: 'tsx L436 (top:-2)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'header.bell.dot.right',
        desc: 'dot 위치 right -2',
        selector: '.header-bell-dot',
        kind: 'css',
        prop: 'right',
        expected: '-2px',
        proto: 'tsx L436 (right:-2)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'header.bell.dot.color',
        desc: 'dot 색 = error',
        selector: '.header-bell-dot',
        kind: 'css',
        prop: 'background-color',
        expected: 'rgb(239, 68, 68)',
        proto: 'tsx L436 (background:T.error)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'header.bell.dot.borderWidth',
        desc: 'dot 테두리 1.5px (배경과 분리)',
        selector: '.header-bell-dot',
        kind: 'css',
        prop: 'border-top-width',
        expected: '1.5px',
        proto: 'tsx L436 (border:1.5px solid)',
        severity: 'P2',
        states: ['auth'],
        deviation:
            'Chromium computed style 는 devicePixelRatio=1 환경에서 sub-pixel border-width 를 정수로 라운딩해 ' +
            '`1px` 을 반환한다. CSS 는 `border-width: 1.5px` 로 prototype 값 그대로 설정돼 있고 시각적 두께도 ' +
            'prototype 과 동일. 계약 runner 가 다중 허용값(1px|1.5px) 을 지원하기 전까지 개별 예외 처리.',
    },

    // ── 로그인: 아바타 + 이름 + chevron ─────────────────────
    {
        id: 'header.user.trigger.exists',
        desc: '로그인 시 아바타·이름·chevron 묶음 트리거',
        selector: '.header-user-trigger',
        kind: 'exists',
        expected: true,
        proto: 'tsx L447~451',
        severity: 'P0',
        states: ['auth'],
    },
    {
        id: 'header.user.trigger.gap',
        desc: '트리거 내부 간격 8',
        selector: '.header-user-trigger',
        kind: 'css',
        prop: 'column-gap',
        expected: '8px',
        proto: 'tsx L447 (gap:8)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'header.avatar.size',
        desc: '헤더 아바타 30x30',
        selector: '.header-avatar',
        kind: 'box',
        prop: 'width',
        expected: 30,
        proto: 'tsx L448 (Avatar size=30)',
        severity: 'P1',
        states: ['auth'],
    },
    {
        id: 'header.avatar.radius',
        desc: '아바타 원형',
        selector: '.header-avatar',
        kind: 'css',
        prop: 'border-radius',
        expected: '50%',
        proto: 'tsx L371 (borderRadius:50%)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'header.avatar.fontSize',
        desc: '아바타 이니셜 폰트 13 = round(30*0.42)',
        selector: '.header-avatar',
        kind: 'css',
        prop: 'font-size',
        expected: '13px',
        proto: 'tsx L369 (fs=round(size*0.42))',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'header.avatar.fontWeight',
        desc: '아바타 이니셜 weight 700',
        selector: '.header-avatar',
        kind: 'css',
        prop: 'font-weight',
        expected: '700',
        proto: 'tsx L374 (fontWeight:700)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'header.user.name.notEmpty',
        desc:
            '헤더 사용자 이름이 실제 텍스트로 렌더 — `<sec:authentication>` element 는 Spring Security 7 에서 ' +
            '리터럴 렌더되어 이름이 사라진 전례 있음 (2026-07-03)',
        selector: '.header-user-name:not(:empty)',
        kind: 'exists',
        expected: true,
        proto: 'tsx L449 ({이름}님)',
        severity: 'P0',
        states: ['auth'],
    },
    {
        id: 'header.user.name.text',
        desc: `사용자 이름은 "{이름}님" 패턴 (시드 유저 = ${SEED_USER_NAME})`,
        selector: '.header-user-name',
        kind: 'text',
        expected: `${SEED_USER_NAME}님`,
        proto: 'tsx L449',
        severity: 'P1',
        states: ['auth'],
    },
    {
        id: 'header.user.name.fontSize',
        desc: '사용자 이름 폰트 14',
        selector: '.header-user-name',
        kind: 'css',
        prop: 'font-size',
        expected: '14px',
        proto: 'tsx L449 (fontSize:14)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'header.user.name.fontWeight',
        desc: '사용자 이름 weight 500',
        selector: '.header-user-name',
        kind: 'css',
        prop: 'font-weight',
        expected: '500',
        proto: 'tsx L449 (fontWeight:500)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'header.user.chev.size',
        desc: 'chevron-down 14x14',
        selector: '.header-chev',
        kind: 'box',
        prop: 'width',
        expected: 14,
        proto: 'tsx L450 (Icon n="chevD" size=14)',
        severity: 'P2',
        states: ['auth'],
    },
];

// ─────────────────────────────────────────────────────────────
// 2. 드롭다운 패널 (닫힌 상태에서 규격만 검사 — 열림 동작은 서술 계약)
// ─────────────────────────────────────────────────────────────
const dropdownChecks: Check[] = [
    // ── 유저 메뉴 패널 ──────────────────────────────────────
    {
        id: 'userMenu.panel.exists',
        desc: '유저 메뉴 드롭다운 패널이 DOM 에 존재',
        selector: '#header-user-dropdown',
        kind: 'exists',
        expected: true,
        proto: 'tsx L452~456 (UserMenuPanel)',
        severity: 'P1',
        states: ['auth'],
    },
    {
        id: 'userMenu.panel.width',
        desc: '유저 메뉴 패널 고정폭 220',
        selector: '#header-user-dropdown',
        kind: 'css',
        prop: 'width',
        expected: '220px',
        proto: 'tsx L382 (width:220)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'userMenu.panel.radius',
        desc: '유저 메뉴 패널 radius 14',
        selector: '#header-user-dropdown',
        kind: 'css',
        prop: 'border-radius',
        expected: '14px',
        proto: 'tsx L382 (borderRadius:14)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'userMenu.panel.shadow',
        desc: '유저 메뉴 패널 그림자 0 12px 40px rgba(0,0,0,0.14)',
        selector: '#header-user-dropdown',
        kind: 'css',
        prop: 'box-shadow',
        expected: 'rgba(0, 0, 0, 0.14) 0px 12px 40px 0px',
        proto: 'tsx L382 (boxShadow)',
        severity: 'P2',
        states: ['auth'],
        deviation:
            'POLICY.md P-2 — 그림자 브랜드 틴트 토큰 유지',
    },
    {
        id: 'userMenu.item.count',
        desc: '유저 메뉴 항목 2개 — 프로필 카드(마이페이지) + 로그아웃',
        selector: '#header-user-dropdown [role="menuitem"]',
        kind: 'count',
        expected: 2,
        proto: 'tsx L383 / L392',
        severity: 'P1',
        states: ['auth'],
    },
    {
        id: 'userMenu.profile.padding',
        desc: '프로필 카드 패딩 16px 18px',
        selector: '.header-dropdown-profile',
        kind: 'css',
        prop: 'padding-top',
        expected: '16px',
        proto: 'tsx L383 (padding:16px 18px)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'userMenu.profile.gap',
        desc: '프로필 카드 내부 간격 10',
        selector: '.header-dropdown-profile',
        kind: 'css',
        prop: 'column-gap',
        expected: '10px',
        proto: 'tsx L383 (gap:10)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'userMenu.profile.avatar.size',
        desc: '프로필 카드 아바타 38 (헤더 30 보다 큼)',
        selector: '.header-dropdown-profile-avatar',
        kind: 'css',
        prop: 'width',
        expected: '38px',
        proto: 'tsx L384 (Avatar size=38)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'userMenu.profile.name.fontSize',
        desc: '프로필 카드 이름 폰트 15',
        selector: '.header-dropdown-profile-name',
        kind: 'css',
        prop: 'font-size',
        expected: '15px',
        proto: 'tsx L386 (fontSize:15)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'userMenu.profile.email.notEmpty',
        desc: '프로필 카드에 이메일 노출 (이름 아래 보조 정보)',
        selector: '.header-dropdown-profile-email:not(:empty)',
        kind: 'exists',
        expected: true,
        proto: 'tsx L387',
        severity: 'P1',
        states: ['auth'],
    },
    {
        id: 'userMenu.profile.email.fontSize',
        desc: '프로필 카드 이메일 폰트 12',
        selector: '.header-dropdown-profile-email',
        kind: 'css',
        prop: 'font-size',
        expected: '12px',
        proto: 'tsx L387 (fontSize:12)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'userMenu.logout.padding',
        desc: '로그아웃 행 패딩 11px 18px',
        selector: '.header-dropdown-item',
        kind: 'css',
        prop: 'padding-top',
        expected: '11px',
        proto: 'tsx L392 (padding:11px 18px)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'userMenu.logout.fontSize',
        desc: '로그아웃 라벨 폰트 14',
        selector: '.header-dropdown-item span',
        kind: 'css',
        prop: 'font-size',
        expected: '14px',
        proto: 'tsx L394 (fontSize:14)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'userMenu.logout.icon.exists',
        desc: '로그아웃 아이콘은 SVG (login 아이콘 좌우반전) — 이모지·문자 대체 금지',
        selector: '.header-dropdown-item-icon',
        kind: 'exists',
        expected: true,
        proto: 'tsx L393 (Icon n="login" scaleX(-1))',
        severity: 'P1',
        states: ['auth'],
    },

    // ── 알림 패널 ───────────────────────────────────────────
    {
        id: 'notif.panel.exists',
        desc: '알림 드롭다운 패널이 DOM 에 존재',
        selector: '.notif-panel',
        kind: 'exists',
        expected: true,
        proto: 'tsx L438~442 (NotifPanel)',
        severity: 'P1',
        states: ['auth'],
    },
    {
        id: 'notif.panel.width',
        desc: '알림 패널 폭 380',
        selector: '.notif-panel',
        kind: 'css',
        prop: 'width',
        expected: '380px',
        proto: 'tsx L329 (width:380)',
        severity: 'P1',
        states: ['auth'],
    },
    {
        id: 'notif.panel.radius',
        desc: '알림 패널 radius 14',
        selector: '.notif-panel',
        kind: 'css',
        prop: 'border-radius',
        expected: '14px',
        proto: 'tsx L329 (borderRadius:14)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'notif.panel.shadow',
        desc: '알림 패널 그림자 0 12px 40px rgba(0,0,0,0.14) — 브랜드 틴트 shadow-lg 이 아님',
        selector: '.notif-panel',
        kind: 'css',
        prop: 'box-shadow',
        expected: 'rgba(0, 0, 0, 0.14) 0px 12px 40px 0px',
        proto: 'tsx L329 (boxShadow)',
        severity: 'P2',
        states: ['auth'],
        deviation:
            'POLICY.md P-2 — 그림자 브랜드 틴트 토큰 유지',
    },
    {
        id: 'notif.head.padding',
        desc: '알림 패널 헤더 패딩 16px 18px',
        selector: '.notif-panel-head',
        kind: 'css',
        prop: 'padding-top',
        expected: '16px',
        proto: 'tsx L330 (padding:16px 18px)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'notif.title.fontSize',
        desc: '알림 제목 폰트 16',
        selector: '.notif-panel-title',
        kind: 'css',
        prop: 'font-size',
        expected: '16px',
        proto: 'tsx L332 (fontSize:16)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'notif.badge.height',
        desc: '미읽음 카운트 배지 높이 18',
        selector: '.notif-panel-badge',
        kind: 'css',
        prop: 'height',
        expected: '18px',
        proto: 'tsx L333 (height:18)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'notif.badge.radius',
        desc: '미읽음 카운트 배지 radius 9 (완전 pill)',
        selector: '.notif-panel-badge',
        kind: 'css',
        prop: 'border-radius',
        expected: '9px',
        proto: 'tsx L333 (borderRadius:9)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'notif.actions.clearAll',
        desc: '헤더 우측 액션은 "모두 읽음 | 모두 지우기" 2개 — 모두 지우기 미구현',
        selector: '.notif-panel-actions .notif-clear-all',
        kind: 'exists',
        expected: true,
        proto: 'tsx L338 (clearAll)',
        severity: 'P1',
        states: ['auth'],
        deviation:
            '알림은 읽음 처리만 제공하기로 결정 (2026-07-28). 하드 삭제는 감사 추적을 잃고 백엔드 API 신설이 필요해 도입하지 않는다',
    },
    {
        id: 'notif.actions.divider',
        desc: '두 액션 사이 `|` 구분자',
        selector: '.notif-panel-actions .notif-action-divider',
        kind: 'exists',
        expected: true,
        proto: 'tsx L337',
        severity: 'P2',
        states: ['auth'],
        deviation:
            '모두 지우기 미도입에 따라 구분자도 불필요 (notif.actions.clearAll 참조)',
    },
    {
        id: 'notif.item.count',
        desc: '알림 항목 최대 4건 (패널은 4건까지만 보여주고 나머지는 전체보기)',
        selector: '.notif-panel .notif-item',
        kind: 'count',
        expected: 4,
        proto: 'tsx L323 (NOTIF_ITEMS.slice(0,4))',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'notif.item.padding',
        desc: '알림 항목 패딩 14px 16px',
        selector: '.notif-item',
        kind: 'css',
        prop: 'padding-top',
        expected: '14px',
        proto: 'tsx L347 (padding:14px 16px)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'notif.item.icon.size',
        desc: '알림 항목 좌측 원형 아이콘 36',
        selector: '.notif-icon',
        kind: 'css',
        prop: 'width',
        expected: '36px',
        proto: 'tsx L348 (width:36)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'notif.item.icon.svg',
        desc: '원형 아이콘 안에 종·달력 등 lucide SVG — 현재는 빈 원',
        selector: '.notif-icon svg',
        kind: 'exists',
        expected: true,
        proto: 'tsx L349 (Icon n={item.icon} size=16)',
        severity: 'P1',
        states: ['auth'],
    },
    {
        id: 'notif.item.remove',
        desc: '알림 항목 우측 개별 삭제(x) 버튼 (2026-08-13 도입, prototype L356~358)',
        selector: '.notif-item .notif-item-close',
        kind: 'exists',
        expected: true,
        proto: 'tsx L356~358 (remove) — /notifications/{id}/delete API 재사용',
        severity: 'P1',
        states: ['auth'],
    },
    {
        id: 'notif.item.title.fontSize',
        desc: '알림 항목 제목 폰트 14',
        selector: '.notif-item-title',
        kind: 'css',
        prop: 'font-size',
        expected: '14px',
        proto: 'tsx L352 (fontSize:14)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'notif.item.body.fontSize',
        desc: '알림 항목 본문 폰트 13',
        selector: '.notif-item-message',
        kind: 'css',
        prop: 'font-size',
        expected: '13px',
        proto: 'tsx L353 (fontSize:13)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'notif.item.time.fontSize',
        desc: '알림 항목 시간 폰트 12',
        selector: '.notif-item-time',
        kind: 'css',
        prop: 'font-size',
        expected: '12px',
        proto: 'tsx L354 (fontSize:12)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'notif.footer.text',
        desc: '패널 하단 전체보기 링크',
        selector: '.notif-panel-footer',
        kind: 'text',
        expected: '알림 전체보기',
        proto: 'tsx L361',
        severity: 'P1',
        states: ['auth'],
    },
    {
        id: 'notif.footer.fontSize',
        desc: '전체보기 폰트 13 / weight 600',
        selector: '.notif-panel-footer',
        kind: 'css',
        prop: 'font-size',
        expected: '13px',
        proto: 'tsx L361 (fontSize:13)',
        severity: 'P2',
        states: ['auth'],
    },
    {
        id: 'notif.footer.color',
        desc: '전체보기 색 = primary',
        selector: '.notif-panel-footer',
        kind: 'css',
        prop: 'color',
        expected: 'rgb(63, 48, 233)',
        proto: 'tsx L361 (color:T.primary)',
        severity: 'P2',
        states: ['auth'],
    },
];

// ─────────────────────────────────────────────────────────────
// 3. 푸터
// ─────────────────────────────────────────────────────────────
const footerChecks: Check[] = [
    {
        id: 'footer.background',
        desc: '푸터 배경 #F5F5F5 (토큰 bg 가 아닌 고정 회색)',
        selector: '.site-footer',
        kind: 'css',
        prop: 'background-color',
        expected: 'rgb(245, 245, 245)',
        proto: 'tsx L476 (background:#F5F5F5)',
        severity: 'P2',
    },
    {
        id: 'footer.borderTop',
        desc: '푸터 상단 1px border',
        selector: '.site-footer',
        kind: 'css',
        prop: 'border-top-width',
        expected: '1px',
        proto: 'tsx L476 (borderTop)',
        severity: 'P2',
    },
    {
        id: 'footer.paddingTop',
        desc: '푸터 상단 패딩 20',
        selector: '.site-footer',
        kind: 'css',
        prop: 'padding-top',
        expected: '20px',
        proto: 'tsx L476 (padding:20px 80px 16px)',
        severity: 'P2',
    },
    {
        id: 'footer.paddingBottom',
        desc: '푸터 하단 패딩 16 (상단 20 과 비대칭)',
        selector: '.site-footer',
        kind: 'css',
        prop: 'padding-bottom',
        expected: '16px',
        proto: 'tsx L476 (padding:20px 80px 16px)',
        severity: 'P2',
    },
    {
        id: 'footer.paddingLeft',
        desc: '푸터 좌우 패딩 80 (헤더와 동일)',
        selector: '.site-footer',
        kind: 'css',
        prop: 'padding-left',
        expected: '80px',
        proto: 'tsx L476',
        severity: 'P2',
    },
    {
        id: 'footer.inner.gap',
        desc: '푸터 3블록(로고·중앙·SNS) 간격 40',
        selector: '.footer-inner',
        kind: 'css',
        prop: 'column-gap',
        expected: '40px',
        proto: 'tsx L477 (gap:40)',
        severity: 'P2',
    },
    {
        id: 'footer.inner.alignItems',
        desc: '푸터 3블록 세로 중앙 정렬',
        selector: '.footer-inner',
        kind: 'css',
        prop: 'align-items',
        expected: 'center',
        proto: 'tsx L477 (alignItems:center)',
        severity: 'P2',
    },
    {
        id: 'footer.logo.img.height',
        desc: '푸터 로고 심볼 28 (헤더 34 보다 작음)',
        selector: '.footer-logo-img',
        kind: 'box',
        prop: 'height',
        expected: 28,
        proto: 'tsx L479 (height:28)',
        severity: 'P2',
    },
    {
        id: 'footer.logo.gap',
        desc: '푸터 로고 심볼–텍스트 간격 7',
        selector: '.footer-logo',
        kind: 'css',
        prop: 'column-gap',
        expected: '7px',
        proto: 'tsx L478 (gap:7)',
        severity: 'P2',
    },
    {
        id: 'footer.logo.text.fontSize',
        desc: '푸터 워드마크 폰트 16',
        selector: '.footer-logo-text',
        kind: 'css',
        prop: 'font-size',
        expected: '16px',
        proto: 'tsx L480 (fontSize:16)',
        severity: 'P2',
    },
    {
        id: 'footer.logo.text.color',
        desc: '푸터 워드마크 = primary',
        selector: '.footer-logo-text',
        kind: 'css',
        prop: 'color',
        expected: 'rgb(63, 48, 233)',
        proto: 'tsx L480 (color:T.primary)',
        severity: 'P2',
    },
    {
        id: 'footer.center.flex',
        desc: '중앙 블록 flex:1 (SNS 를 우측 끝으로 밀어냄)',
        selector: '.footer-center',
        kind: 'css',
        prop: 'flex-grow',
        expected: '1',
        proto: 'tsx L482 (flex:1)',
        severity: 'P1',
    },

    // ── 푸터 링크 (정보구조) ────────────────────────────────
    {
        id: 'footer.links.count',
        desc: '푸터 링크 4개 — 개인정보처리방침 / 이용약관 / 이메일 무단 수집거부 / 관리자',
        selector: '.footer-links a',
        kind: 'count',
        expected: 4,
        proto: 'tsx L468 (links) + L486 (관리자)',
        severity: 'P1',
        deferred:
            'admin 트랙 — 기대값 4 는 관리자 링크 포함 수 (footer.links.admin 참조). 현행 3개',
    },
    {
        id: 'footer.links.1.text',
        desc: '푸터 링크 1 = 개인정보처리방침',
        selector: '.footer-links a:nth-child(1)',
        kind: 'text',
        expected: '개인정보처리방침',
        proto: 'tsx L468',
        severity: 'P1',
    },
    {
        id: 'footer.links.2.text',
        desc: '푸터 링크 2 = 이용약관',
        selector: '.footer-links a:nth-child(2)',
        kind: 'text',
        expected: '이용약관',
        proto: 'tsx L468',
        severity: 'P1',
    },
    {
        id: 'footer.links.3.text',
        // 260819: prototype tsx L468 은 "이메일주소무단수집거부" (공백 없음). 사용자 지시로 가독성 개선 →
        // "이메일 무단 수집거부" (공백 포함) 로 변경. POLICY P-1 카피 정책에 준하는 이탈.
        desc: '푸터 링크 3 = 이메일 무단 수집거부',
        selector: '.footer-links a:nth-child(3)',
        kind: 'text',
        expected: '이메일 무단 수집거부',
        proto: 'tsx L468 (원문 "이메일주소무단수집거부" · 260819 공백 개선)',
        severity: 'P1',
    },
    {
        id: 'footer.links.admin',
        desc: '푸터 우측 끝 "관리자" 진입 링크 — 미구현',
        selector: '.footer-links .footer-admin-link',
        kind: 'exists',
        expected: true,
        proto: 'tsx L486 (go("forbidden"))',
        severity: 'P1',
        deferred:
            'admin 트랙 — docs/specs/ADMIN-00-master-directive.md (A1 shell). 지금 링크를 넣으면 /admin 미구현이라 404',
    },
    {
        id: 'footer.links.divider',
        desc: '정책 링크와 관리자 사이 1x10 세로 구분선',
        selector: '.footer-links .footer-links-divider',
        kind: 'exists',
        expected: true,
        proto: 'tsx L485 (width:1 height:10 background:#ccc)',
        severity: 'P2',
        deferred:
            'admin 트랙 — footer.links.admin 과 세트',
    },
    {
        id: 'footer.links.gap',
        desc: '푸터 링크 간격 16',
        selector: '.footer-links',
        kind: 'css',
        prop: 'column-gap',
        expected: '16px',
        proto: 'tsx L483 (gap:16)',
        severity: 'P2',
    },
    {
        id: 'footer.links.marginBottom',
        desc: '링크 줄과 카피라이트 줄 간격 6',
        selector: '.footer-links',
        kind: 'css',
        prop: 'margin-bottom',
        expected: '6px',
        proto: 'tsx L483 (marginBottom:6)',
        severity: 'P2',
    },
    {
        id: 'footer.links.fontSize',
        desc: '푸터 링크 폰트 11',
        selector: '.footer-links a',
        kind: 'css',
        prop: 'font-size',
        expected: '11px',
        proto: 'tsx L484 (fontSize:11)',
        severity: 'P2',
    },
    {
        id: 'footer.links.fontWeight',
        desc: '푸터 링크 weight 500',
        selector: '.footer-links a',
        kind: 'css',
        prop: 'font-weight',
        expected: '500',
        proto: 'tsx L484 (fontWeight:500)',
        severity: 'P2',
    },
    {
        id: 'footer.links.color',
        desc: '푸터 링크 색 #444',
        selector: '.footer-links a',
        kind: 'css',
        prop: 'color',
        expected: 'rgb(68, 68, 68)',
        proto: 'tsx L484 (color:#444)',
        severity: 'P2',
    },

    // ── 카피라이트 ──────────────────────────────────────────
    {
        id: 'footer.copy.fontSize',
        desc: '카피라이트 폰트 11',
        selector: '.footer-copy',
        kind: 'css',
        prop: 'font-size',
        expected: '11px',
        proto: 'tsx L488 (fontSize:11)',
        severity: 'P2',
    },
    {
        id: 'footer.copy.color',
        desc: '카피라이트 색 #888',
        selector: '.footer-copy',
        kind: 'css',
        prop: 'color',
        expected: 'rgb(136, 136, 136)',
        proto: 'tsx L488 (color:#888)',
        severity: 'P2',
    },
    {
        id: 'footer.copy.text',
        desc: '카피라이트 문구',
        selector: '.footer-copy',
        kind: 'text',
        expected: 'Copyright © 2026 청년모아 All Rights Reserved',
        proto: 'tsx L488',
        severity: 'P2',
        deviation:
            '연도를 `java.time.Year.now()` 로 동적 생성하기로 결정 (하드코딩 금지 원칙). 2026 년 현재는 문자열이 동일하지만, ' +
            '연도가 바뀌면 계약이 깨지므로 검사에서 제외한다.',
    },

    // ── SNS ─────────────────────────────────────────────────
    {
        id: 'footer.sns.count',
        desc: 'SNS 아이콘 4개 — Instagram / YouTube / KakaoTalk / Facebook',
        selector: '.footer-sns img',
        kind: 'count',
        expected: 4,
        proto: 'tsx L469~474 (socials)',
        severity: 'P1',
    },
    {
        id: 'footer.sns.size',
        desc: 'SNS 아이콘 24x24',
        selector: '.footer-sns img',
        kind: 'box',
        prop: 'width',
        expected: 24,
        proto: 'tsx L491 (width:24 height:24)',
        severity: 'P2',
    },
    {
        id: 'footer.sns.gap',
        desc: 'SNS 아이콘 간격 8',
        selector: '.footer-sns',
        kind: 'css',
        prop: 'column-gap',
        expected: '8px',
        proto: 'tsx L490 (gap:8)',
        severity: 'P2',
    },
];

/**
 * 기본 계약 — `/programs` (일반 흰 배경 헤더 + 푸터).
 *
 * `/programs` 를 고른 이유: 헤더 transparent 분기가 홈 전용이라 (proto L405~406)
 * "13개 화면 중 12개가 쓰는 규격" 을 관측하려면 홈이 아닌 경로여야 한다.
 * 동시에 활성 네비(active 표식) 검사도 가능하다.
 */
export const commonContract: ScreenContract = {
    screen: 'common',
    path: '/programs',
    source: 'prototype.tsx L402~464 (Header) / L467~496 (Footer) / L322~399 (NotifPanel·Avatar·UserMenuPanel), 2026-07-28 추출',
    viewport: { width: 1440, height: 900 },
    checks: [...headerChecks, ...dropdownChecks, ...footerChecks],
};

/**
 * 홈 전용 계약 — `/` 최상단의 transparent 헤더.
 *
 * proto L406~408: `transparent = isHome && !scrolled` 일 때
 *   fg = #fff, fgSec = rgba(255,255,255,0.85), 배경·보더·그림자 제거.
 * 스크롤 후 흰 배경으로 되돌아가는 **전환 자체**는 기계 검사 대상이 아니므로 서술 계약에 기록한다.
 */
export const commonHomeContract: ScreenContract = {
    screen: 'common-home',
    path: '/',
    source: 'prototype.tsx L406~460 (Header transparent 분기) / L371~374 (Avatar transparent), 2026-07-28 추출',
    viewport: { width: 1440, height: 900 },
    checks: [
        {
            id: 'homeHeader.transparent.class',
            desc: '홈 헤더에 transparent 모드가 적용되어 있음',
            selector: '.site-header--transparent',
            kind: 'exists',
            expected: true,
            proto: 'tsx L406 (transparent = isHome && !scrolled)',
            severity: 'P0',
        },
        {
            id: 'homeHeader.background',
            desc: '홈 최상단 헤더 배경 투명',
            selector: '.site-header',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgba(0, 0, 0, 0)',
            proto: 'tsx L415 (background: transparent)',
            severity: 'P0',
        },
        {
            id: 'homeHeader.borderBottomColor',
            desc: '홈 최상단 헤더 하단 보더 없음',
            selector: '.site-header',
            kind: 'css',
            prop: 'border-bottom-color',
            expected: 'rgba(0, 0, 0, 0)',
            proto: 'tsx L415 (borderBottom:none)',
            severity: 'P1',
        },
        {
            id: 'homeHeader.boxShadow',
            desc: '홈 최상단 헤더 그림자 없음',
            selector: '.site-header',
            kind: 'css',
            prop: 'box-shadow',
            expected: 'none',
            proto: 'tsx L415 (boxShadow:none)',
            severity: 'P1',
        },
        {
            id: 'homeHeader.height',
            desc: 'transparent 모드에서도 헤더 높이 68 유지',
            selector: '.site-header',
            kind: 'box',
            prop: 'height',
            expected: 68,
            proto: 'tsx L415 (height:T.headerH)',
            severity: 'P1',
        },
        {
            id: 'homeHeader.logo.text.color',
            desc: '로고 워드마크 흰색',
            selector: '.header-logo-text',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(255, 255, 255)',
            proto: 'tsx L420 (color: transparent?#fff:T.primary)',
            severity: 'P1',
        },
        {
            id: 'homeHeader.nav.color',
            desc: '비활성 네비 rgba(255,255,255,0.88)',
            selector: '.header-nav .nav-link',
            kind: 'css',
            prop: 'color',
            expected: 'rgba(255, 255, 255, 0.88)',
            proto: 'tsx L426',
            severity: 'P2',
        },
        {
            id: 'homeHeader.search.color',
            desc: '검색 아이콘 fgSec = rgba(255,255,255,0.85)',
            selector: '.header-right a[aria-label="검색"]',
            kind: 'css',
            prop: 'color',
            expected: 'rgba(255, 255, 255, 0.85)',
            proto: 'tsx L408 (fgSec) / L431',
            severity: 'P2',
        },
        {
            id: 'homeHeader.login.color',
            desc: '로그인 아이콘 흰색',
            selector: '.header-right a[aria-label="로그인"]',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(255, 255, 255)',
            proto: 'tsx L459',
            severity: 'P2',
        },
        {
            id: 'homeHeader.bell.color',
            desc: '알림 종 fgSec = rgba(255,255,255,0.85)',
            selector: '.header-bell-trigger',
            kind: 'css',
            prop: 'color',
            expected: 'rgba(255, 255, 255, 0.85)',
            proto: 'tsx L408 (fgSec) / L435',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'homeHeader.bell.dot.borderColor',
            desc: 'transparent 모드에서 dot 테두리도 투명 (흰 링 제거)',
            selector: '.header-bell-dot',
            kind: 'css',
            prop: 'border-top-color',
            expected: 'rgba(0, 0, 0, 0)',
            proto: 'tsx L436 (border: transparent?transparent:T.surface)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'homeHeader.avatar.background',
            desc: 'transparent 모드 아바타 배경 rgba(255,255,255,0.25)',
            selector: '.header-avatar',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgba(255, 255, 255, 0.25)',
            proto: 'tsx L371 (transparent?rgba(255,255,255,0.25):T.primaryLight)',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'homeHeader.avatar.color',
            desc: 'transparent 모드 아바타 이니셜 흰색',
            selector: '.header-avatar',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(255, 255, 255)',
            proto: 'tsx L374 (color: transparent?#fff:T.primary)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'homeHeader.userName.color',
            desc: 'transparent 모드 사용자 이름 흰색',
            selector: '.header-user-name',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(255, 255, 255)',
            proto: 'tsx L449',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'homeHeader.chev.color',
            desc: 'transparent 모드 chevron rgba(255,255,255,0.8)',
            selector: '.header-chev',
            kind: 'css',
            prop: 'color',
            expected: 'rgba(255, 255, 255, 0.8)',
            proto: 'tsx L450',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'homeHeader.nav.noActive',
            desc: '홈에서는 주 네비 3개 중 활성 항목 없음 (홈은 nav 배열에 없음)',
            selector: '.header-nav .nav-link.active',
            kind: 'count',
            expected: 0,
            proto: 'tsx L409~413 (nav 에 home 미포함)',
            severity: 'P2',
        },
    ],
};
