/**
 * 홈 화면 (`/`) 디자인 계약 — 기계 검사 항목.
 *
 * 추출 기준: docs/00_assets/prototype.tsx L499~694 (HomeScreen) / 2026-07-28
 * 서술 계약 (아키텍처·상태·CTA 라우팅): docs/design-contracts/home.md
 *
 * 디자인 토큰 (prototype.tsx L10~21):
 *   primary #3F30E9 = rgb(63, 48, 233) / radius 12 / tagR 20 / headerH 68
 *   text    oklch(0.22 0.051 280) / textSec oklch(0.55 0.034 280) / textTri oklch(0.7 0.02 280)
 */

import type { ScreenContract } from './types';

export const homeContract: ScreenContract = {
    screen: 'home',
    path: '/',
    source: 'prototype.tsx L499~694 (HomeScreen), 2026-07-28 추출',
    viewport: { width: 1440, height: 900 },
    checks: [
        // ── Hero ────────────────────────────────────────────────
        {
            id: 'hero.height',
            desc: 'Hero 전체 높이 = 488 + headerH(68)',
            selector: '.hero',
            kind: 'box',
            prop: 'height',
            expected: 556,
            tolerance: 2,
            proto: 'tsx L513',
            severity: 'P1',
        },
        {
            id: 'hero.inner.alignItems',
            desc: 'Hero 콘텐츠 정렬 — prototype 은 중앙 정렬',
            selector: '.hero-inner',
            kind: 'css',
            prop: 'align-items',
            expected: 'center',
            proto: 'tsx L522 (alignItems:center)',
            severity: 'P0',
        },
        {
            id: 'hero.inner.textAlign',
            desc: 'Hero 텍스트 정렬 — prototype 은 중앙',
            selector: '.hero-inner',
            kind: 'css',
            prop: 'text-align',
            expected: 'center',
            proto: 'tsx L522 (textAlign:center)',
            severity: 'P0',
        },
        {
            id: 'hero.eyebrow.isChip',
            desc: 'Hero 배지는 반투명 chip (배경 있음) — 순수 텍스트가 아님',
            selector: '.hero-eyebrow',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgba(255, 255, 255, 0.2)',
            proto: 'tsx L523 (background rgba(255,255,255,0.2))',
            severity: 'P1',
        },
        {
            id: 'hero.eyebrow.radius',
            desc: 'Hero 배지 chip radius 20 (tagR)',
            selector: '.hero-eyebrow',
            kind: 'css',
            prop: 'border-radius',
            expected: '20px',
            proto: 'tsx L523 (borderRadius:20)',
            severity: 'P1',
        },
        {
            id: 'hero.eyebrow.fontSize',
            desc: 'Hero 배지 폰트 14',
            selector: '.hero-eyebrow',
            kind: 'css',
            prop: 'font-size',
            expected: '14px',
            proto: 'tsx L524 (fontSize:14)',
            severity: 'P2',
        },
        {
            id: 'hero.eyebrow.fontWeight',
            desc: 'Hero 배지 weight 500',
            selector: '.hero-eyebrow',
            kind: 'css',
            prop: 'font-weight',
            expected: '500',
            proto: 'tsx L524 (fontWeight:500)',
            severity: 'P2',
        },
        {
            id: 'hero.title.fontSize',
            desc: 'Hero h1 폰트 42',
            selector: '.hero-title',
            kind: 'css',
            prop: 'font-size',
            expected: '42px',
            proto: 'tsx L526 (fontSize:42)',
            severity: 'P1',
        },
        {
            id: 'hero.title.fontWeight',
            desc: 'Hero h1 weight 800',
            selector: '.hero-title',
            kind: 'css',
            prop: 'font-weight',
            expected: '800',
            proto: 'tsx L526 (fontWeight:800)',
            severity: 'P2',
        },
        {
            id: 'hero.title.text',
            desc: 'Hero h1 카피',
            selector: '.hero-title',
            kind: 'text',
            expected: '경기도 청년의 내일을\n함께 만들어갑니다',
            proto: 'tsx L526',
            severity: 'P1',
            deviation:
                '서비스명이 「청년모아」로 정착해 경기도 한정 카피를 쓰지 않기로 결정 (2026-07-28). 현행 "청년의 모든 기회를 / 한곳에서" 유지',
        },
        {
            id: 'hero.desc.fontSize',
            desc: 'Hero 설명 폰트 16',
            selector: '.hero-desc',
            kind: 'css',
            prop: 'font-size',
            expected: '16px',
            proto: 'tsx L527 (fontSize:16)',
            severity: 'P2',
        },
        {
            id: 'hero.desc.text',
            desc: 'Hero 설명 카피',
            selector: '.hero-desc',
            kind: 'text',
            expected: '경기도 31개 시·군 청년센터의 프로그램을 한눈에 확인하세요',
            proto: 'tsx L527',
            severity: 'P1',
            deviation:
                'hero.title.text 와 동일 사유 (2026-07-28). 현행 "프로그램·공간·정책을 청년모아에서 만나보세요" 유지',
        },
        {
            id: 'hero.search.width',
            desc: '검색바 너비 460',
            selector: '.hero-search-bar',
            kind: 'box',
            prop: 'width',
            expected: 460,
            proto: 'tsx L528 (width:460)',
            severity: 'P1',
        },
        {
            id: 'hero.search.height',
            desc: '검색바 높이 52',
            selector: '.hero-search-bar',
            kind: 'box',
            prop: 'height',
            expected: 52,
            proto: 'tsx L528 (height:52)',
            severity: 'P1',
        },
        {
            id: 'hero.search.input.fontSize',
            desc: '검색 input 폰트 15',
            selector: '.hero-search-input',
            kind: 'css',
            prop: 'font-size',
            expected: '15px',
            proto: 'tsx L530 (fontSize:15)',
            severity: 'P2',
        },
        {
            id: 'hero.chips.count',
            desc: '인기 검색어 칩 5개',
            selector: '.hero-chip',
            kind: 'count',
            expected: 5,
            proto: 'tsx L538',
            severity: 'P1',
        },

        // ── Quick Stats ─────────────────────────────────────────
        {
            id: 'stats.gap',
            desc: 'Stats 항목 간격 48',
            selector: '.quick-stats',
            kind: 'css',
            prop: 'column-gap',
            expected: '48px',
            proto: 'tsx L547 (gap:48)',
            severity: 'P2',
        },
        {
            id: 'stats.count',
            desc: 'Stats 지표 3개',
            selector: '.quick-stat',
            kind: 'count',
            expected: 3,
            proto: 'tsx L548',
            severity: 'P1',
        },
        {
            id: 'stats.icon.size',
            desc: 'Stats 아이콘 박스 44x44',
            selector: '.quick-stat-icon',
            kind: 'box',
            prop: 'width',
            expected: 44,
            proto: 'tsx L550 (width:44)',
            severity: 'P2',
        },
        {
            id: 'stats.icon.isSvg',
            desc: 'Stats 아이콘은 lucide SVG (check) — 텍스트 ✓ 대체 금지',
            selector: '.quick-stat-icon svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L551 (<Icon n="check">)',
            severity: 'P1',
        },
        {
            id: 'stats.value.fontSize',
            desc: 'Stats 숫자 폰트 22',
            selector: '.quick-stat-value',
            kind: 'css',
            prop: 'font-size',
            expected: '22px',
            proto: 'tsx L554',
            severity: 'P2',
        },

        // ── 퀵메뉴 4그리드 ──────────────────────────────────────
        {
            id: 'quickmenu.maxWidth',
            desc: '퀵메뉴 컨테이너 폭 1080 — 다른 섹션(1440)보다 좁다',
            selector: '.home-quickmenu',
            kind: 'box',
            prop: 'width',
            expected: 1080,
            proto: 'tsx L561 (maxWidth:1080)',
            severity: 'P1',
        },
        {
            id: 'quickmenu.count',
            desc: '퀵메뉴 카드 4개',
            selector: '.home-quickmenu-card',
            kind: 'count',
            expected: 4,
            proto: 'tsx L562~567',
            severity: 'P1',
        },
        {
            id: 'quickmenu.gap',
            desc: '퀵메뉴 grid gap 14',
            selector: '.home-quickmenu',
            kind: 'css',
            prop: 'column-gap',
            expected: '14px',
            proto: 'tsx L561 (gap:14)',
            severity: 'P2',
        },
        {
            id: 'quickmenu.icon.size',
            desc: '퀵메뉴 아이콘 박스 48x48',
            selector: '.home-quickmenu-icon',
            kind: 'box',
            prop: 'width',
            expected: 48,
            proto: 'tsx L569',
            severity: 'P2',
        },
        {
            id: 'quickmenu.icon.radius',
            desc: '퀵메뉴 아이콘 radius 14',
            selector: '.home-quickmenu-icon',
            kind: 'css',
            prop: 'border-radius',
            expected: '14px',
            proto: 'tsx L569 (borderRadius:14)',
            severity: 'P2',
        },

        // ── 프로그램 섹션 (비로그인) ────────────────────────────
        {
            id: 'programs.card.count',
            desc: '비로그인 프로그램 카드 4개',
            selector: '.home-program-card',
            kind: 'count',
            expected: 4,
            proto: 'tsx L615 (PROGRAMS.slice(0,4))',
            severity: 'P1',
        },
        {
            id: 'programs.card.image.height',
            desc: '비로그인 카드 이미지 높이 170',
            selector: '.home-program-card .program-card-image',
            kind: 'box',
            prop: 'height',
            expected: 170,
            proto: 'tsx L617 (height:170)',
            severity: 'P2',
        },
        {
            id: 'programs.card.title.fontSize',
            desc: '비로그인 카드 제목 폰트 15',
            selector: '.home-program-card .program-card-title',
            kind: 'css',
            prop: 'font-size',
            expected: '15px',
            proto: 'tsx L625 (fontSize:15)',
            severity: 'P2',
        },
        {
            id: 'programs.card.bookmark',
            desc: '카드 우상단 즐겨찾기 별 아이콘 — 목록 화면과 동일하게 홈에도 존재',
            selector: '.home-program-card .bookmark-btn',
            kind: 'exists',
            expected: true,
            proto: 'tsx L620~622 (Icon star/starFill)',
            severity: 'P1',
        },
        {
            id: 'programs.card.cta',
            desc: '카드 하단 CTA 버튼 (신청하기 / 오픈 알림 받기 / 빈자리 알림 받기)',
            selector: '.home-program-card .program-card-cta',
            kind: 'exists',
            expected: true,
            proto: 'tsx L629~632 (height:34 CTA)',
            severity: 'P1',
        },
        {
            id: 'programs.row.gap',
            desc: '프로그램 grid gap 20',
            selector: '.home-program-row',
            kind: 'css',
            prop: 'column-gap',
            expected: '20px',
            proto: 'tsx L614 (gap:20)',
            severity: 'P2',
        },

        // ── 맞춤 추천 (로그인) ──────────────────────────────────
        {
            id: 'recommend.interestChip',
            desc: '맞춤 추천 제목 옆 관심 태그 chip (예: 부천시 · 취업·창업 관심)',
            selector: '.home-section-title .interest-chip',
            kind: 'exists',
            expected: true,
            proto: 'tsx L581',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'recommend.card.image.height',
            desc: '맞춤 추천 카드 이미지 높이 150 (비로그인 170 과 다름)',
            selector: '.home-program-card .program-card-image',
            kind: 'box',
            prop: 'height',
            expected: 150,
            proto: 'tsx L590 (height:150)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'recommend.card.title.fontSize',
            desc: '맞춤 추천 카드 제목 폰트 14 (비로그인 15 와 다름)',
            selector: '.home-program-card .program-card-title',
            kind: 'css',
            prop: 'font-size',
            expected: '14px',
            proto: 'tsx L596 (fontSize:14)',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'recommend.badge.count',
            desc: '추천 라벨 배지 4개 (첫 카드 관심지역, 나머지 추천)',
            selector: '.recommend-badge',
            kind: 'count',
            expected: 4,
            proto: 'tsx L593',
            severity: 'P2',
            states: ['auth'],
        },

        // ── 공지 섹션 ───────────────────────────────────────────
        {
            id: 'notice.main.width',
            desc: '공지 대표 카드 고정폭 360 (flexShrink 0)',
            selector: '.home-notice-main',
            kind: 'box',
            prop: 'width',
            expected: 360,
            proto: 'tsx L649 (width:360)',
            severity: 'P1',
        },
        {
            id: 'notice.main.image.height',
            desc: '공지 대표 카드 이미지 높이 180',
            selector: '.home-notice-main-image',
            kind: 'box',
            prop: 'height',
            expected: 180,
            proto: 'tsx L650 (height:180)',
            severity: 'P2',
        },
        {
            id: 'notice.item.height',
            desc: '공지 리스트 행 높이 64',
            selector: '.home-notice-item',
            kind: 'box',
            prop: 'height',
            expected: 64,
            proto: 'tsx L661 (height:64)',
            severity: 'P2',
        },
        {
            id: 'notice.item.count',
            desc: '공지 리스트 3건 (NOTICES.slice(1))',
            selector: '.home-notice-item',
            kind: 'count',
            expected: 3,
            proto: 'tsx L660',
            severity: 'P2',
        },

        // ── 공간안내 ────────────────────────────────────────────
        {
            id: 'space.card.count',
            desc: '공간 카드 3개',
            selector: '.home-space-card',
            kind: 'count',
            expected: 3,
            proto: 'tsx L680 (IMGS.space)',
            severity: 'P2',
        },
        {
            id: 'space.card.height',
            desc: '공간 카드 높이 240',
            selector: '.home-space-card',
            kind: 'box',
            prop: 'height',
            expected: 240,
            proto: 'tsx L681 (height:240)',
            severity: 'P2',
        },
        {
            id: 'space.row.gap',
            desc: '공간 카드 간격 20',
            selector: '.home-space-row',
            kind: 'css',
            prop: 'column-gap',
            expected: '20px',
            proto: 'tsx L679 (gap:20)',
            severity: 'P2',
        },
    ],
};
