/**
 * 마이페이지 (`/mypage`) 디자인 계약 — 사용자 트랙 계약 시리즈 6번째 · 마지막 사용자 화면.
 *
 * 도입 (2026-08-14): login #138 · signup #139 · notices #140 · apply #141 · notifications #143·#145 이후.
 * prototype `MyPage` (tsx L1317~1628) 기준. 4탭 세그먼트 (history / favorites / noti / profile) 를
 * `?tab=` 쿼리 파라미터로 분기하는 **단일 라우트** 구조. profile 탭은 Step1 (비밀번호 재확인) 폼만
 * 렌더하고 Step2 (실제 편집 폼) 는 별도 라우트 `/mypage/profile/edit` 로 이동한다.
 *
 * ─────────────────────────────────────────────────────────
 * 계약 구조 결정: 하나의 계약 vs 탭별 분리
 * ─────────────────────────────────────────────────────────
 * 하나로 통합했다. 이유:
 *   1) URL 이 같다 (`/mypage?tab=…`) — 별도 `ScreenContract.path` 를 4개로 나눌 이유 없음
 *   2) 상단 profile-summary + tabnav 는 4탭 공통 (prototype L1352~1399) — 중복 체크 회피
 *   3) 탭별 고유 검사는 셀렉터 prefix (`.mypage-history …` / `.mypage-favorites …` /
 *      `.noti-… ` / `.mypage-profile-verify …`) 로 자연스레 분리됨
 *
 * 대신 visual-mypage.spec.ts 가 4탭을 순회 로드하며 계약을 실행하도록 구성한다.
 * 각 tab 진입 후 그 탭의 셀렉터만 존재하고 다른 탭 셀렉터는 없으므로, exists 계약은
 * 해당 탭에서만 매칭되고 나머지 탭에선 자동 skip 되도록 selector 를 명확히 나눈다.
 *
 * ─────────────────────────────────────────────────────────
 * 인증: 로그인 필수 (SecurityConfig `/mypage/**` authenticated).
 *   → 전 검사 states: ['auth']. helpers.login 으로 seed 계정 진입.
 *
 * side-effect: 렌더만 수행. 취소 폼 submit · 알림 토글 · 저장 · 탈퇴는 트리거하지 않음.
 *   단, 다음 데이터가 seed 상태로 전제된다 (rotation pool 불필요 — 읽기 only):
 *     - Application 최소 1건 (승인 or 대기) — history 카드 렌더 검사용
 *     - Bookmark 0건 or ≥1 (empty state 계약은 seed 30 계정 실측 후 결정 — 아래 note)
 *     - User.interestRegions/Categories 최소 1건씩 (interest chips 렌더 검사용)
 *
 * ─────────────────────────────────────────────────────────
 * 갭 예상 (2026-08-14 실측 기반, 상세는 mypage-gap-backlog.md T1~T12):
 *   P0: 없음 — 4탭 골격 · 상단 요약 · URL 라우팅은 이미 정상 동작
 *   P1: 다수 — SVG 아이콘 이식 (탭 이미 완료 · profile-verify eye 완료 · history calendar 완료),
 *       history 카드 이미지 슬롯 (prototype 88×88 vs 현재 존재 확인만),
 *       favorites 카드 필드 확장 (prototype 은 ProgramCard, 현재는 title+sub 만)
 *   P2: 문구 · 폰트 · 간격 미세 조정 다수 (mypage-gap-backlog T12 · POLICY P-1 로 상당수 deviation)
 *
 * 함께: `docs/design-contracts/mypage.md` — 아키텍처·상태머신·CTA·POLICY 매핑·§8 결정 Q.
 */

import type { ScreenContract } from './types';

export const mypageContract: ScreenContract = {
    screen: 'mypage',
    path: '/mypage', // 기본 tab=history
    source: 'prototype.tsx MyPage L1317~1628 · 2026-08-14 신설',
    viewport: { width: 1440, height: 900 },
    checks: [
        // ══════════════════════════════════════════════════════
        // 컨테이너 · 페이지 폭 (전 탭 공통)
        // ══════════════════════════════════════════════════════
        {
            id: 'container.max-width',
            desc: 'mypage-page inner max-width 1080 (prototype L1351)',
            selector: '.mypage-page .container',
            kind: 'css',
            prop: 'max-width',
            expected: '1080px',
            proto: 'tsx L1351 maxWidth:1080',
            states: ['auth'],
            severity: 'P2',
        },

        // ══════════════════════════════════════════════════════
        // 프로필 요약 카드 (전 탭 공통 · prototype L1353~1390)
        // ══════════════════════════════════════════════════════
        {
            id: 'summary.exists',
            desc: '프로필 요약 카드 존재',
            selector: '.mypage-summary',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1353 프로필 요약 카드',
            states: ['auth'],
            severity: 'P0',
        },
        {
            id: 'summary.padding',
            desc: '요약 카드 padding 26/30 (prototype L1353)',
            selector: '.mypage-summary-inner',
            kind: 'css',
            prop: 'padding-top',
            expected: '26px',
            proto: 'tsx L1353 padding:26px 30px',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'summary.avatar.size',
            desc: '아바타 원형 58×58 (prototype L1354)',
            selector: '.mypage-summary-avatar',
            kind: 'box',
            prop: 'width',
            expected: 58,
            tolerance: 1,
            proto: 'tsx L1354 Avatar size=58',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'summary.hello.font-size',
            desc: '환영 문구 font-size 20 (prototype L1356)',
            selector: '.mypage-summary-hello',
            kind: 'css',
            prop: 'font-size',
            expected: '20px',
            proto: 'tsx L1356 fontSize:20',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'summary.hello.font-weight',
            desc: '환영 문구 font-weight 700',
            selector: '.mypage-summary-hello',
            kind: 'css',
            prop: 'font-weight',
            expected: '700',
            proto: 'tsx L1356 fontWeight:700',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'summary.email.font-size',
            desc: '요약 이메일 font-size 13 (prototype L1357)',
            selector: '.mypage-summary-email',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L1357 fontSize:13',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'summary.interest-groups.count',
            desc: '관심 정보 그룹 2개 (지역·분야, prototype L1359)',
            selector: '.mypage-interest-group',
            kind: 'count',
            expected: 2,
            proto: 'tsx L1359 pin/star 2 groups',
            states: ['auth'],
            severity: 'P0',
        },
        {
            id: 'summary.interest-label.svg',
            desc: '관심 그룹 라벨 SVG 아이콘 (POLICY P-3)',
            selector: '.mypage-interest-group .mypage-interest-label svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1363 Icon n={g.icon} size:13',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'summary.interest-chip.exists',
            desc: '관심 태그 chip 최소 1개 (seed 사용자 interest 전제)',
            selector: '.mypage-interest-chip',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1367 shown.map 값 칩',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'summary.interest-chip.bg',
            desc: '관심 chip 배경 primary-light (prototype L1367)',
            selector: '.mypage-interest-chip',
            kind: 'css',
            prop: 'background-color',
            // prototype tsx L12 T.primaryLight = oklch(0.93 0.0425 280). 초기 계약 산출값 오류 정정 (2026-08-18).
            expected: 'oklch(0.93 0.0425 280)',
            proto: 'tsx L1367 background:T.primaryLight',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'summary.interest-chip.color',
            desc: '관심 chip 텍스트 primary (prototype L1367)',
            selector: '.mypage-interest-chip',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(63, 48, 233)',
            proto: 'tsx L1367 color:T.primary',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'summary.interest-edit-link.svg',
            desc: '관심 정보 수정 링크 SVG edit 아이콘 (POLICY P-3)',
            selector: '.mypage-interest-edit svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1374 Icon n="edit" size:12',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'summary.interest-edit-link.color',
            desc: '관심 정보 수정 링크 색 primary (prototype L1374)',
            selector: '.mypage-interest-edit',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(63, 48, 233)',
            proto: 'tsx L1374 color:T.primary',
            states: ['auth'],
            severity: 'P2',
        },

        // ══════════════════════════════════════════════════════
        // KPI 3열 (진행중·종료·즐겨찾기, prototype L1378~1389)
        // ══════════════════════════════════════════════════════
        {
            id: 'kpi.count',
            desc: 'KPI 3개 (진행중·종료·즐겨찾기, prototype L1379~1382)',
            selector: '.mypage-kpi',
            kind: 'count',
            expected: 3,
            proto: 'tsx L1379~1382 3 items',
            states: ['auth'],
            severity: 'P0',
        },
        {
            id: 'kpi.value.font-size',
            desc: 'KPI 값 font-size 24 (prototype L1385)',
            selector: '.mypage-kpi-value',
            kind: 'css',
            prop: 'font-size',
            expected: '24px',
            proto: 'tsx L1385 fontSize:24',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'kpi.value.font-weight',
            desc: 'KPI 값 font-weight 800 (prototype L1385)',
            selector: '.mypage-kpi-value',
            kind: 'css',
            prop: 'font-weight',
            expected: '800',
            proto: 'tsx L1385 fontWeight:800',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'kpi.value.color',
            desc: 'KPI 값 색 primary (prototype L1385)',
            selector: '.mypage-kpi-value',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(63, 48, 233)',
            proto: 'tsx L1385 color:T.primary',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'kpi.label.font-size',
            desc: 'KPI 라벨 font-size 12 (prototype L1386)',
            selector: '.mypage-kpi-label',
            kind: 'css',
            prop: 'font-size',
            expected: '12px',
            proto: 'tsx L1386 fontSize:12',
            states: ['auth'],
            severity: 'P2',
        },
        // Q-4 완료: KPI 카드 <a> 로 변환 (prototype L1380 setTab 이동 → 서버 렌더 ?tab= 링크)
        {
            id: 'kpi.clickable',
            desc: 'KPI 각 항목이 clickable (prototype L1384 goTab 이동)',
            selector: '.mypage-kpi',
            kind: 'css',
            prop: 'cursor',
            expected: 'pointer',
            proto: 'tsx L1384 cursor:pointer, onClick setTab',
            states: ['auth'],
            severity: 'P2',
        },

        // ══════════════════════════════════════════════════════
        // 탭바 4개 (세그먼트형, prototype L1391~1399)
        // ══════════════════════════════════════════════════════
        {
            id: 'tabs.count',
            desc: '탭 4개 (신청내역·즐겨찾기·알림설정·개인정보수정, prototype L1393)',
            selector: '.mypage-tab',
            kind: 'count',
            expected: 4,
            proto: 'tsx L1393 [history,favorites,noti,profile]',
            states: ['auth'],
            severity: 'P0',
        },
        {
            id: 'tabs.svg',
            desc: '각 탭 SVG 아이콘 (POLICY P-3 · T1 mypage-gap-backlog)',
            selector: '.mypage-tab svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1395 Icon n={m.icon} size:16',
            states: ['auth'],
            severity: 'P0',
        },
        {
            id: 'tabs.gap',
            desc: '탭바 gap 4 (prototype L1392)',
            selector: '.mypage-tabs',
            kind: 'css',
            prop: 'gap',
            expected: '4px',
            proto: 'tsx L1392 gap:4',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'tabs.padding',
            desc: '탭바 padding 5 (prototype L1392)',
            selector: '.mypage-tabs',
            kind: 'css',
            prop: 'padding-top',
            expected: '5px',
            proto: 'tsx L1392 padding:5',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'tabs.radius',
            desc: '탭바 radius 12 (prototype L1392)',
            selector: '.mypage-tabs',
            kind: 'css',
            prop: 'border-radius',
            expected: '12px',
            proto: 'tsx L1392 borderRadius:12',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'tabs.active.bg',
            desc: '활성 탭 배경 primary-light (prototype L1394)',
            selector: '.mypage-tab.active',
            kind: 'css',
            prop: 'background-color',
            // prototype tsx L12 T.primaryLight = oklch(0.93 0.0425 280). 초기 계약 산출값 오류 정정 (2026-08-18).
            expected: 'oklch(0.93 0.0425 280)',
            proto: 'tsx L1394 background:tab===m.key?T.primaryLight:transparent',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'tabs.active.font-weight',
            desc: '활성 탭 font-weight 700 (prototype L1396)',
            selector: '.mypage-tab.active',
            kind: 'css',
            prop: 'font-weight',
            expected: '700',
            proto: 'tsx L1396 fontWeight:tab===m.key?700:500',
            states: ['auth'],
            severity: 'P2',
        },

        // ══════════════════════════════════════════════════════
        // 콘텐츠 카드 (전 탭 공통 컨테이너, prototype L1401)
        // ══════════════════════════════════════════════════════
        {
            id: 'card.padding',
            desc: '콘텐츠 카드 padding 28/30 (prototype L1401)',
            selector: '.mypage-card',
            kind: 'css',
            prop: 'padding-top',
            expected: '28px',
            proto: 'tsx L1401 padding:28px 30px',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'card.border-radius',
            desc: '콘텐츠 카드 radius --radius-lg 12 (prototype L1401)',
            selector: '.mypage-card',
            kind: 'css',
            prop: 'border-radius',
            expected: '12px',
            proto: 'tsx L1401 borderRadius:T.radius(12)',
            states: ['auth'],
            severity: 'P2',
        },

        // ══════════════════════════════════════════════════════
        // ─────── history 탭 (prototype L1402~1475) ───────
        // seed: apply 계정 (seed 30) 이 승인 or 대기 앱 최소 1건 보유 전제
        // ══════════════════════════════════════════════════════
        {
            id: 'history.section-title.text',
            desc: 'history 섹션 제목 (prototype L1404)',
            selector: '.mypage-history .mypage-section-title',
            kind: 'text',
            expected: '프로그램 신청 내역',
            proto: 'tsx L1404 프로그램 신청 내역',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'history.section-title.font-size',
            desc: 'history 섹션 제목 font-size 20 (prototype L1404)',
            selector: '.mypage-history .mypage-section-title',
            kind: 'css',
            prop: 'font-size',
            expected: '20px',
            proto: 'tsx L1404 fontSize:20',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'history.period-tabs.count',
            desc: '기간 필터 4개 (3개월·6개월·1년·3년, prototype L1408)',
            selector: '.history-period-tab',
            kind: 'count',
            expected: 4,
            proto: 'tsx L1408 [3개월,6개월,1년,3년]',
            states: ['auth'],
            severity: 'P0',
        },
        {
            id: 'history.period-tab.height',
            desc: '기간 필터 height 44 (prototype L1409)',
            selector: '.history-period-tab',
            kind: 'box',
            prop: 'height',
            expected: 44,
            tolerance: 1,
            proto: 'tsx L1409 height:44',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'history.period-tab.radius',
            desc: '기간 필터 radius 8 (prototype L1409)',
            selector: '.history-period-tab',
            kind: 'css',
            prop: 'border-radius',
            expected: '8px',
            proto: 'tsx L1409 borderRadius:8',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'history.period-tab.active.color',
            desc: '활성 기간 필터 텍스트 primary (prototype L1409)',
            selector: '.history-period-tab.is-on',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(63, 48, 233)',
            proto: 'tsx L1409 color:period===p?T.primary:T.textSec',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'history.status-chips.count',
            desc: '상태 필터 칩 5개 (전체·승인·대기·반려·취소, prototype L1414)',
            selector: '.history-status-chip',
            kind: 'count',
            expected: 5,
            proto: 'tsx L1414 [전체,승인,대기,반려,취소]',
            states: ['auth'],
            severity: 'P0',
        },
        {
            id: 'history.status-chip.radius',
            desc: '상태 필터 칩 radius pill 20 (prototype L1418)',
            selector: '.history-status-chip',
            kind: 'css',
            prop: 'border-radius',
            expected: '20px',
            proto: 'tsx L1418 borderRadius:T.tagR(pill=20)',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'history.status-chip.font-size',
            desc: '상태 필터 칩 텍스트 font-size 13 (prototype L1419)',
            selector: '.history-status-chip span:first-child',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L1419 fontSize:13',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'history.status-chip.active.bg',
            desc: '활성 상태 필터 배경 primary (prototype L1418)',
            selector: '.history-status-chip.is-on',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgb(63, 48, 233)',
            proto: 'tsx L1418 background:on?T.primary:transparent',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'history.status-chip.active.color',
            desc: '활성 상태 필터 텍스트 흰색 (prototype L1419)',
            selector: '.history-status-chip.is-on span:first-child',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(255, 255, 255)',
            proto: 'tsx L1419 color:on?#fff',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'history.card.exists',
            desc: '신청 내역 카드 최소 1건 (seed 승인/대기 앱 전제)',
            selector: '.mypage-history-card',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1438 리스트 아이템',
            states: ['auth'],
            severity: 'P0',
        },
        {
            id: 'history.card.padding',
            desc: '신청 카드 padding 18/20 (prototype L1438)',
            selector: '.mypage-history-card',
            kind: 'css',
            prop: 'padding-top',
            expected: '18px',
            proto: 'tsx L1438 padding:18px 20px',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'history.card.thumb.size',
            desc: '신청 카드 이미지 88×88 (prototype L1448)',
            selector: '.history-card-thumb',
            kind: 'box',
            prop: 'width',
            expected: 88,
            tolerance: 1,
            proto: 'tsx L1448 width:88 height:88',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'history.card.time.font-size',
            desc: '신청일시 font-size 13 (prototype L1441)',
            selector: '.history-card-time',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L1441 fontSize:13',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'history.card.title.font-size',
            desc: '프로그램명 font-size 16 (prototype L1451)',
            selector: '.history-card-title',
            kind: 'css',
            prop: 'font-size',
            expected: '16px',
            proto: 'tsx L1451 fontSize:16',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'history.card.status-badge.exists',
            desc: '신청 상태 뱃지 존재 (prototype L1452)',
            selector: '.history-status-badge',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1452 상태 뱃지',
            states: ['auth'],
            severity: 'P0',
        },
        {
            id: 'history.card.detail-link.svg',
            desc: '신청 상세 링크 chevR SVG (POLICY P-3)',
            selector: '.history-card-detail-link svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1444 Icon n="chevR" size:15',
            states: ['auth'],
            severity: 'P1',
        },
        // Q-1 완료: 신청 상세 별도 라우트 `/mypage/applications/{id}` 신설
        {
            id: 'history.card.detail-link.href',
            desc: '신청 상세 링크가 clickable (prototype L1442 application-detail 이동)',
            selector: '.history-card-detail-link',
            kind: 'css',
            prop: 'cursor',
            expected: 'pointer',
            proto: 'tsx L1442 go(application-detail)',
            states: ['auth'],
            severity: 'P1',
        },

        // ══════════════════════════════════════════════════════
        // ─────── favorites 탭 (prototype L1476~1485) ───────
        // ══════════════════════════════════════════════════════
        {
            id: 'favorites.section-title.text',
            desc: 'favorites 섹션 제목 (prototype L1478)',
            selector: '.mypage-favorites .mypage-section-title',
            kind: 'text',
            expected: '즐겨찾기한 프로그램',
            proto: 'tsx L1478 즐겨찾기한 프로그램',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'favorites.section-title.font-size',
            desc: 'favorites 섹션 제목 font-size 20 (prototype L1478)',
            selector: '.mypage-favorites .mypage-section-title',
            kind: 'css',
            prop: 'font-size',
            expected: '20px',
            proto: 'tsx L1478 fontSize:20',
            states: ['auth'],
            severity: 'P2',
        },
        // Q-2 완료: 즐겨찾기 = ProgramCard 재사용 그리드
        {
            id: 'favorites.card.grid',
            desc: '즐겨찾기 카드 grid (prototype 는 ProgramCard grid)',
            selector: '.mypage-favorites-list',
            kind: 'css',
            prop: 'display',
            expected: 'grid',
            proto: 'tsx MyPage L1476~1484 (empty state 만 prototype 에 있음)',
            states: ['auth'],
            severity: 'P1',
        },
        // P1-4 후속 (2026-08-18): seed1 에 bookmark 3건 seed 되면서 empty state 렌더 안 됨.
        // favorites.card.grid (bookmarks 있을 때) 와 favorites.empty.svg (empty 상태) 는 상호 배타적.
        // seed 정책은 bookmarks 3건이므로 empty SVG check 는 deferred 로 변경.
        {
            id: 'favorites.empty.svg',
            desc: '즐겨찾기 empty state star SVG (POLICY P-3, prototype L1480)',
            selector: '.mypage-favorites .mypage-empty svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1480 Icon n="star" size:64 (empty)',
            states: ['auth'],
            severity: 'P1',
            deferred:
                'seed1 에 bookmarks 3건 시드되어 empty state 렌더 안 됨. 별도 empty seed 계정으로 검증하거나 계약 상태 분기 도입 후 활성화 예정',
        },

        // ══════════════════════════════════════════════════════
        // ─────── noti 탭 (prototype L1555~1580) ───────
        // ══════════════════════════════════════════════════════
        {
            id: 'noti.section-title.text',
            desc: 'noti 섹션 제목 (prototype L1557)',
            selector: '.mypage-noti .mypage-section-title',
            kind: 'text',
            expected: '알림 설정',
            proto: 'tsx L1557 알림 설정',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'noti.channel-heading.exists',
            desc: '알림 받을 방법 소제목 (prototype L1558)',
            selector: '.mypage-noti .noti-section-heading',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1558 알림 받을 방법',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'noti.channel.count',
            desc: '알림 채널 3개 (카카오·SMS·이메일, prototype L1561)',
            selector: '.noti-channel-row',
            kind: 'count',
            expected: 3,
            proto: 'tsx L1561 [kakao,sms,email]',
            states: ['auth'],
            severity: 'P0',
        },
        {
            id: 'noti.channel-icon.svg',
            desc: '알림 채널 아이콘 원형 안 SVG (POLICY P-3)',
            selector: '.noti-channel-icon svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1563 Icon n="bell" size:18',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'noti.channel-icon.size',
            desc: '알림 채널 아이콘 원형 38×38 (prototype L1563)',
            selector: '.noti-channel-icon',
            kind: 'box',
            prop: 'width',
            expected: 38,
            tolerance: 1,
            proto: 'tsx L1563 width:38 height:38',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'noti.channel-icon.radius',
            desc: '알림 채널 아이콘 원형 radius 10 (prototype L1563)',
            selector: '.noti-channel-icon',
            kind: 'css',
            prop: 'border-radius',
            expected: '10px',
            proto: 'tsx L1563 borderRadius:10',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'noti.item.count',
            desc: '알림 항목 4개 (필수 결과+D-1+빈자리+신규, prototype L1572)',
            selector: '.noti-item-row',
            kind: 'count',
            expected: 4,
            proto: 'tsx L1572 [_lock,remind,empty,news]',
            states: ['auth'],
            severity: 'P0',
        },
        {
            id: 'noti.lock-badge.exists',
            desc: '필수 뱃지 존재 (prototype L1574)',
            selector: '.noti-lock-badge',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1574 필수 뱃지',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'noti.lock-badge.text',
            desc: '필수 뱃지 텍스트',
            selector: '.noti-lock-badge',
            kind: 'text',
            expected: '필수',
            proto: 'tsx L1574 필수',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'noti.autosave-hint.svg',
            desc: '자동 저장 힌트 check SVG (POLICY P-3, prototype L1579)',
            selector: '.noti-autosave-hint svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1579 Icon n="check" size:13',
            states: ['auth'],
            severity: 'P1',
        },
        {
            // 260819: prototype L1556 은 form 전체를 560 wrapper 로 감쌌지만, profile 탭과 정렬을 통일하기
            // 위해 헤더는 왼쪽 · 컨트롤(채널·항목 리스트) 만 폭 560 + 가운데 정렬로 조정. 사용자 지시 반영.
            id: 'noti.channel-list.max-width',
            desc: 'noti 채널 리스트 max-width 560 (prototype L1560)',
            selector: '.mypage-noti .noti-channel-list',
            kind: 'css',
            prop: 'max-width',
            expected: '560px',
            proto: 'tsx L1560 maxWidth:560',
            states: ['auth'],
            severity: 'P2',
        },
        {
            id: 'noti.item-list.max-width',
            desc: 'noti 항목 리스트 max-width 560 (prototype L1571)',
            selector: '.mypage-noti .noti-item-list',
            kind: 'css',
            prop: 'max-width',
            expected: '560px',
            proto: 'tsx L1571 maxWidth:560',
            states: ['auth'],
            severity: 'P2',
        },

        // ══════════════════════════════════════════════════════
        // ─────── profile 탭 = Step1 비밀번호 재확인 (prototype L1489~1504) ───────
        // ══════════════════════════════════════════════════════
        {
            id: 'profile-verify.section-title.text',
            desc: 'Step1 섹션 제목 (prototype L1488 · Q-6 결정으로 prototype 공백 정합)',
            selector: '.mypage-profile-verify .mypage-section-title',
            kind: 'text',
            expected: '개인 정보 수정',
            proto: 'tsx L1488 개인 정보 수정',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'profile-verify.form.exists',
            desc: '비밀번호 재확인 폼 존재',
            selector: '.mypage-verify-form',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1493 재확인 grid',
            states: ['auth'],
            severity: 'P0',
        },
        {
            id: 'profile-verify.password-input.exists',
            desc: '비밀번호 재확인 input (prototype L1498)',
            selector: '#verifyPassword',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1498 password input',
            states: ['auth'],
            severity: 'P0',
        },
        // eye 토글은 wireframe #9 로 인해 prototype 을 초과. 구현 유지.
        {
            id: 'profile-verify.eye-btn.svg',
            desc: '비밀번호 눈 토글 SVG (F-wireframe #9)',
            selector: '.mypage-profile-verify .auth-eye-btn svg',
            kind: 'exists',
            expected: true,
            proto: 'wireframe #9 · prototype 초과',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'profile-verify.submit-btn.exists',
            desc: '확인 버튼 (prototype L1501)',
            selector: '.mypage-verify-form button[type="submit"]',
            kind: 'text',
            expected: '확인',
            proto: 'tsx L1501 확인',
            states: ['auth'],
            severity: 'P1',
        },
        // ── 260825 X-1 방어: mobile G5 hotfix (flex column min-height:320) 가
        //    media query 조기 종료로 데스크톱까지 누출된 사고 재발 방지.
        //    데스크톱 verify-form 은 원 flow (block · min-height 0 · flex-direction row) 유지되어야 함.
        {
            id: 'profile-verify.form.display',
            desc: 'Step1 폼 데스크톱 display block (모바일 flex hotfix 누출 방지)',
            selector: '.mypage-verify-form',
            kind: 'css',
            prop: 'display',
            expected: 'block',
            proto: 'tsx L1493 재확인 폼 — 데스크톱 원 flow',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'profile-verify.form.min-height',
            desc: 'Step1 폼 데스크톱 min-height 0 (모바일 320px hotfix 누출 방지)',
            selector: '.mypage-verify-form',
            kind: 'css',
            prop: 'min-height',
            expected: '0px',
            proto: 'tsx L1493 — 데스크톱은 자연 높이',
            states: ['auth'],
            severity: 'P1',
        },
        {
            id: 'profile-verify.form.flex-direction',
            desc: 'Step1 폼 데스크톱 flex-direction row (모바일 column hotfix 누출 방지)',
            selector: '.mypage-verify-form',
            kind: 'css',
            prop: 'flex-direction',
            expected: 'row',
            proto: 'tsx L1493 — flex 미사용 시 계산값 row',
            states: ['auth'],
            severity: 'P2',
        },
    ],
};
