/**
 * 프로그램 상세 (`/programs/{id}`) 디자인 계약 — 기계 검사 항목.
 *
 * 추출 기준: docs/00_assets/prototype.tsx L945~1124 (ProgramDetail) / 2026-07-28
 *   헬퍼: CapacityBar L214~249 · DdayChip L250~258 · WaitlistModal L265~321 · 토큰 T L10~21
 * 서술 계약 (아키텍처·상태머신·CTA 라우팅): docs/design-contracts/program-detail.md
 *
 * ── 상태(state) 슬롯 사용법 ─────────────────────────────────────────
 * 이 화면의 시각 분기는 「로그인 여부」가 아니라 「프로그램 상태」다.
 * (prototype 의 isLoggedIn 은 클릭 동작만 바꾸고 렌더 결과를 바꾸지 않는다 — L1013·L1029)
 * 그래서 runner 의 2개 상태 슬롯을 아래처럼 프로그램 상태에 배정해 쓴다.
 *
 *   states: ['anon'] → 모집중(OPEN) 프로그램 `/programs/1`, 비로그인
 *   states: ['auth'] → 종료(ENDED) 프로그램 `/programs/4`, 로그인
 *
 * 갭 리포트의 「비로그인 / 로그인」 머리글은 위 매핑으로 읽는다 (contract.source 에도 명시).
 * 진행예정(UPCOMING `/programs/5`)·운영중단(SUSPENDED `/programs/9`) 분기는 슬롯이 없어
 * 서술 계약의 상태표로 관리한다.
 *
 * 디자인 토큰 (prototype.tsx L10~21):
 *   primary #3F30E9 = rgb(63, 48, 233) / radius 12 / tagR 20
 *   border oklch(0.9 0.014 280) / borderLight oklch(0.95 0.007 280)
 *   text oklch(0.22 0.051 280) / textSec oklch(0.55 0.034 280) / textTri oklch(0.7 0.02 280)
 */

import type { ScreenContract } from './types';

export const programDetailContract: ScreenContract = {
    screen: 'program-detail',
    path: '/programs/1',
    source:
        'prototype.tsx L945~1124 (ProgramDetail), 2026-07-28 추출 · ' +
        '상태 슬롯 매핑: 「비로그인」= 모집중 프로그램 /programs/1 (비로그인) · ' +
        '「로그인」= 종료 프로그램 /programs/4 (로그인)',
    viewport: { width: 1440, height: 900 },
    checks: [
        // ── 페이지 골격 ─────────────────────────────────────────
        {
            id: 'container.width',
            desc: '본문 컨테이너 폭 1000 (좌우 패딩 0) — 다른 화면의 1440 과 다르다',
            selector: '.detail-container',
            kind: 'box',
            prop: 'width',
            expected: 1000,
            proto: 'tsx L954 (maxWidth:1000)',
            severity: 'P0',
        },
        {
            id: 'container.paddingTop',
            desc: '컨테이너 상단 패딩 36',
            selector: '.detail-container',
            kind: 'css',
            prop: 'padding-top',
            expected: '36px',
            proto: "tsx L954 (padding:'36px 0 48px')",
            severity: 'P2',
        },
        {
            id: 'back.width',
            desc: '뒤로가기 아이콘 박스 38x38',
            selector: '.detail-back-btn',
            kind: 'box',
            prop: 'width',
            expected: 38,
            proto: 'tsx L955 (width:38)',
            severity: 'P1',
        },
        {
            id: 'back.height',
            desc: '뒤로가기 아이콘 박스 높이 38',
            selector: '.detail-back-btn',
            kind: 'box',
            prop: 'height',
            expected: 38,
            proto: 'tsx L955 (height:38)',
            severity: 'P2',
        },
        {
            id: 'back.radius',
            desc: '뒤로가기 박스 radius 9 (T.radius 12 아님)',
            selector: '.detail-back-btn',
            kind: 'css',
            prop: 'border-radius',
            expected: '9px',
            proto: 'tsx L955 (borderRadius:9)',
            severity: 'P2',
        },
        {
            id: 'back.marginBottom',
            desc: '뒤로가기 박스 하단 여백 24',
            selector: '.detail-back-btn',
            kind: 'css',
            prop: 'margin-bottom',
            expected: '24px',
            proto: 'tsx L955 (marginBottom:24)',
            severity: 'P2',
        },
        {
            id: 'back.isSvg',
            desc: '뒤로가기는 lucide arrowL SVG — 텍스트 ← 대체 금지',
            selector: '.detail-back-btn svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L956 (<Icon n="arrowL" size={18}>)',
            severity: 'P1',
        },

        // ── Hero (이미지 + 정보) ────────────────────────────────
        {
            id: 'hero.gap',
            desc: 'Hero 2열 간격 32',
            selector: '.detail-hero',
            kind: 'css',
            prop: 'column-gap',
            expected: '32px',
            proto: 'tsx L974 (gap:32)',
            severity: 'P2',
        },
        {
            id: 'hero.image.width',
            desc: '대표 이미지 340x340 정사각 (flexShrink 0)',
            selector: '.detail-image',
            kind: 'box',
            prop: 'width',
            expected: 340,
            proto: 'tsx L975 (width:340)',
            severity: 'P1',
        },
        {
            id: 'hero.image.height',
            desc: '대표 이미지 높이 340',
            selector: '.detail-image',
            kind: 'box',
            prop: 'height',
            expected: 340,
            proto: 'tsx L975 (height:340)',
            severity: 'P1',
        },
        {
            id: 'hero.image.radius',
            desc: '대표 이미지 radius 12 (T.radius)',
            selector: '.detail-image',
            kind: 'css',
            prop: 'border-radius',
            expected: '12px',
            proto: 'tsx L975 (borderRadius:T.radius)',
            severity: 'P2',
        },
        {
            id: 'hero.badge.count',
            desc: '제목 위 배지는 상태 1개만 (카테고리 배지 없음)',
            selector: '.detail-badges .status-badge',
            kind: 'count',
            expected: 1,
            proto: 'tsx L981~983 (<Badge> 1개)',
            severity: 'P2',
        },
        {
            id: 'hero.title.fontSize',
            desc: '제목 h1 폰트 26',
            selector: '.detail-title',
            kind: 'css',
            prop: 'font-size',
            expected: '26px',
            proto: 'tsx L984 (fontSize:26)',
            severity: 'P1',
        },
        {
            id: 'hero.title.fontWeight',
            desc: '제목 h1 weight 700',
            selector: '.detail-title',
            kind: 'css',
            prop: 'font-weight',
            expected: '700',
            proto: 'tsx L984 (fontWeight:700)',
            severity: 'P2',
        },
        {
            id: 'hero.subtitle.fontSize',
            desc: '센터 · 지역 줄 폰트 14',
            selector: '.detail-subtitle',
            kind: 'css',
            prop: 'font-size',
            expected: '14px',
            proto: 'tsx L985 (fontSize:14)',
            severity: 'P2',
        },

        // ── 모집 상태 카드 (CapacityBar 확장형) ─────────────────
        {
            id: 'status.box.radius',
            desc: '모집 상태 카드 radius 12 (T.radius)',
            selector: '.detail-capacity-box',
            kind: 'css',
            prop: 'border-radius',
            expected: '12px',
            proto: 'tsx L986 (borderRadius:T.radius)',
            severity: 'P1',
        },
        {
            id: 'status.box.padding',
            desc: '모집 상태 카드 패딩 14',
            selector: '.detail-capacity-box',
            kind: 'css',
            prop: 'padding',
            expected: '14px',
            proto: 'tsx L986 (padding:14)',
            severity: 'P2',
        },
        {
            id: 'status.box.marginBottom',
            desc: '모집 상태 카드 하단 여백 20',
            selector: '.detail-capacity-box',
            kind: 'css',
            prop: 'margin-bottom',
            expected: '20px',
            proto: 'tsx L986 (marginBottom:20)',
            severity: 'P2',
        },
        {
            id: 'status.headline.fontSize',
            desc: '상태 헤드라인 폰트 14',
            selector: '.detail-capacity-headline',
            kind: 'css',
            prop: 'font-size',
            expected: '14px',
            proto: 'tsx L988 (fontSize:14)',
            severity: 'P2',
        },
        {
            id: 'status.headline.fontWeight',
            desc: '상태 헤드라인 weight 700',
            selector: '.detail-capacity-headline',
            kind: 'css',
            prop: 'font-weight',
            expected: '700',
            proto: 'tsx L988 (fontWeight:700)',
            severity: 'P2',
        },
        {
            id: 'status.count.fontSize',
            desc: '신청 인원 숫자 폰트 13/700',
            selector: '.detail-capacity-count strong',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L989 (fontSize:13, fontWeight:700)',
            severity: 'P2',
        },
        {
            id: 'status.count.cap.fontSize',
            desc: '정원 표기(/N명) 폰트 12/400 textSec',
            selector: '.detail-capacity-count-cap',
            kind: 'css',
            prop: 'font-size',
            expected: '12px',
            proto: 'tsx L989 (fontSize:12, fontWeight:400)',
            severity: 'P2',
        },
        {
            id: 'status.bar.height',
            desc: 'CapacityBar 트랙 높이 6',
            selector: '.detail-capacity-box .capacity-bar',
            kind: 'box',
            prop: 'height',
            expected: 6,
            proto: 'tsx L991 → L244 (height:6)',
            severity: 'P2',
        },
        {
            id: 'status.bar.radius',
            desc: 'CapacityBar 트랙 radius 3',
            selector: '.detail-capacity-box .capacity-bar',
            kind: 'css',
            prop: 'border-radius',
            expected: '3px',
            proto: 'tsx L991 → L244 (borderRadius:3)',
            severity: 'P2',
        },
        {
            id: 'status.bar.trackColor',
            desc: 'CapacityBar 트랙 배경 borderLight',
            selector: '.detail-capacity-box .capacity-bar',
            kind: 'css',
            prop: 'background-color',
            expected: 'oklch(0.95 0.007 280)',
            proto: 'tsx L991 → L244 (background:T.borderLight)',
            severity: 'P2',
        },
        {
            id: 'status.subtext.fontSize',
            desc: '상태 부가 안내 폰트 12',
            selector: '.detail-capacity-subtext',
            kind: 'css',
            prop: 'font-size',
            expected: '12px',
            proto: 'tsx L992 (fontSize:12)',
            severity: 'P2',
        },
        {
            id: 'status.subtext.marginTop',
            desc: '상태 부가 안내 상단 여백 8',
            selector: '.detail-capacity-subtext',
            kind: 'css',
            prop: 'margin-top',
            expected: '8px',
            proto: 'tsx L992 (marginTop:8)',
            severity: 'P2',
        },
        {
            id: 'status.bar.ended.fillWidth',
            desc: '종료 프로그램은 bar 를 100% 채운다 (신청률 표시 아님)',
            selector: '.detail-capacity-box .capacity-bar-fill',
            kind: 'box',
            prop: 'width',
            expected: 598,
            tolerance: 2,
            proto: "tsx L991 → L223 (width:'100%')",
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'status.bar.ended.fillColor',
            desc: '종료 프로그램 bar 색은 T.border (textTri 아님)',
            selector: '.detail-capacity-box .capacity-bar-fill',
            kind: 'css',
            prop: 'background-color',
            expected: 'oklch(0.9 0.014 280)',
            proto: 'tsx L991 → L223 (background:T.border)',
            severity: 'P2',
            states: ['auth'],
        },

        // ── 정보 그리드 (2열) ───────────────────────────────────
        {
            id: 'meta.item.count',
            desc: '정보 항목 5개 (신청 기간·진행 기간·진행 장소·모집인원·문의처)',
            selector: '.detail-meta-item',
            kind: 'count',
            expected: 5,
            proto: 'tsx L995',
            severity: 'P1',
        },
        {
            id: 'meta.grid.gap',
            desc: '정보 그리드 gap 10',
            selector: '.detail-meta-grid',
            kind: 'css',
            prop: 'column-gap',
            expected: '10px',
            proto: 'tsx L994 (gap:10)',
            severity: 'P2',
        },
        {
            id: 'meta.item.padding',
            desc: '정보 카드 패딩 14 16',
            selector: '.detail-meta-item',
            kind: 'css',
            prop: 'padding',
            expected: '14px 16px',
            proto: "tsx L996 (padding:'14px 16px')",
            severity: 'P2',
        },
        {
            id: 'meta.item.radius',
            desc: '정보 카드 radius 12 (T.radius)',
            selector: '.detail-meta-item',
            kind: 'css',
            prop: 'border-radius',
            expected: '12px',
            proto: 'tsx L996 (borderRadius:T.radius)',
            severity: 'P2',
        },
        {
            id: 'meta.item.gap',
            desc: '정보 카드 내부 아이콘–본문 간격 11',
            selector: '.detail-meta-item',
            kind: 'css',
            prop: 'column-gap',
            expected: '11px',
            proto: 'tsx L996 (gap:11)',
            severity: 'P2',
        },
        {
            id: 'meta.icon.size',
            desc: '정보 카드 아이콘 박스 34x34',
            selector: '.detail-meta-icon',
            kind: 'box',
            prop: 'width',
            expected: 34,
            proto: 'tsx L997 (width:34)',
            severity: 'P2',
        },
        {
            id: 'meta.icon.radius',
            desc: '정보 카드 아이콘 박스 radius 9',
            selector: '.detail-meta-icon',
            kind: 'css',
            prop: 'border-radius',
            expected: '9px',
            proto: 'tsx L997 (borderRadius:9)',
            severity: 'P2',
        },
        {
            id: 'meta.icon.isSvg',
            desc: '정보 카드 아이콘은 lucide SVG (calendar/pin/user/bell)',
            selector: '.detail-meta-icon svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L997 (<Icon n={ic} size={16}>)',
            severity: 'P1',
        },
        {
            id: 'meta.key.fontSize',
            desc: '정보 카드 라벨 폰트 12 (textTri)',
            selector: '.detail-meta-key',
            kind: 'css',
            prop: 'font-size',
            expected: '12px',
            proto: 'tsx L999 (fontSize:12)',
            severity: 'P2',
        },
        {
            id: 'meta.value.fontSize',
            desc: '정보 카드 값 폰트 13.5/600',
            selector: '.detail-meta-value',
            kind: 'css',
            prop: 'font-size',
            expected: '13.5px',
            proto: 'tsx L1007 (fontSize:13.5)',
            severity: 'P2',
        },
        {
            id: 'meta.mapBtn.exists',
            desc: '진행 장소 항목의 「지도」 pill 버튼',
            selector: '.detail-map-btn',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1003~1005',
            severity: 'P1',
        },
        {
            id: 'meta.mapBtn.padding',
            desc: '「지도」 버튼 패딩 3 9',
            selector: '.detail-map-btn',
            kind: 'css',
            prop: 'padding',
            expected: '3px 9px',
            proto: "tsx L1003 (padding:'3px 9px')",
            severity: 'P2',
        },
        {
            id: 'meta.mapBtn.radius',
            desc: '「지도」 버튼 radius 20 (tagR)',
            selector: '.detail-map-btn',
            kind: 'css',
            prop: 'border-radius',
            expected: '20px',
            proto: 'tsx L1003 (borderRadius:T.tagR)',
            severity: 'P2',
        },
        {
            id: 'meta.mapBtn.fontSize',
            desc: '「지도」 버튼 라벨 폰트 11.5',
            selector: '.detail-map-btn',
            kind: 'css',
            prop: 'font-size',
            expected: '11.5px',
            proto: 'tsx L1004 (fontSize:11.5)',
            severity: 'P2',
        },

        // ── 액션 행 (즐겨찾기 · 공유 · CTA) ─────────────────────
        {
            id: 'actions.marginTop',
            desc: '액션 행 상단 여백 20 (prototype 은 정보 그리드에 하단 여백 없음)',
            selector: '.detail-actions',
            kind: 'css',
            prop: 'margin-top',
            expected: '20px',
            proto: 'tsx L1012 (marginTop:20)',
            severity: 'P2',
        },
        {
            id: 'actions.gap',
            desc: '액션 행 간격 10',
            selector: '.detail-actions',
            kind: 'css',
            prop: 'column-gap',
            expected: '10px',
            proto: 'tsx L1012 (gap:10)',
            severity: 'P2',
        },
        {
            id: 'actions.icon.size',
            desc: '즐겨찾기·공유 아이콘 버튼 42x42',
            selector: '.detail-action-icon',
            kind: 'box',
            prop: 'width',
            expected: 42,
            proto: 'tsx L1013 (width:42)',
            severity: 'P2',
        },
        {
            id: 'actions.icon.radius',
            desc: '즐겨찾기·공유 버튼 radius 8',
            selector: '.detail-action-icon',
            kind: 'css',
            prop: 'border-radius',
            expected: '8px',
            proto: 'tsx L1013 (borderRadius:8)',
            severity: 'P2',
        },
        {
            id: 'actions.fav.isSvg',
            desc: '즐겨찾기는 star / starFill SVG',
            selector: '.detail-actions .bookmark-btn svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1014 (<Icon n={fav?"starFill":"star"} size={20}>)',
            severity: 'P1',
        },
        {
            id: 'actions.share.isSvg',
            desc: '공유는 share SVG',
            selector: '.detail-actions [data-share-btn] svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1017 (<Icon n="share" size={18}>)',
            severity: 'P2',
        },

        // ── 본문 CTA ────────────────────────────────────────────
        {
            id: 'cta.exists',
            desc: '본문 CTA 존재 (액션 행 우측 flex:1)',
            selector: '.detail-cta',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1019~1033',
            severity: 'P0',
        },
        {
            id: 'cta.height',
            desc: '본문 CTA 높이 42',
            selector: '.detail-cta',
            kind: 'box',
            prop: 'height',
            expected: 42,
            proto: 'tsx L1029 (height:42)',
            severity: 'P1',
        },
        {
            id: 'cta.radius',
            desc: '본문 CTA radius 20 (tagR)',
            selector: '.detail-cta',
            kind: 'css',
            prop: 'border-radius',
            expected: '20px',
            proto: 'tsx L1029 (borderRadius:T.tagR)',
            severity: 'P2',
        },
        {
            id: 'cta.fontSize',
            desc: '본문 CTA 라벨 폰트 15',
            selector: '.detail-cta',
            kind: 'css',
            prop: 'font-size',
            expected: '15px',
            proto: 'tsx L1031 (fontSize:15)',
            severity: 'P2',
        },
        {
            id: 'cta.open.icon',
            desc: '모집중 CTA 좌측 check 아이콘 SVG',
            selector: '.detail-cta svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1030 (<Icon n="check" size={18} color="#fff">)',
            severity: 'P1',
        },
        {
            id: 'cta.open.text',
            desc: '모집중 CTA 라벨 「신청하기」',
            selector: '.detail-cta',
            kind: 'text',
            expected: '신청하기',
            proto: 'tsx L1031',
            severity: 'P1',
        },
        {
            id: 'cta.open.background',
            desc: '모집중 CTA 배경 primary 채움',
            selector: '.detail-cta',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgb(63, 48, 233)',
            proto: 'tsx L1029 (background:T.primary)',
            severity: 'P1',
        },
        {
            id: 'cta.open.fontWeight',
            desc: '모집중 CTA weight 600 (알림 계열 700 과 다름)',
            selector: '.detail-cta',
            kind: 'css',
            prop: 'font-weight',
            expected: '600',
            proto: 'tsx L1031 (fontWeight:(full||upcoming)?700:600)',
            severity: 'P2',
        },
        {
            id: 'cta.ended.text',
            desc: '종료 CTA 라벨 「비슷한 프로그램 보기」',
            selector: '.detail-cta',
            kind: 'text',
            expected: '비슷한 프로그램 보기',
            proto: 'tsx L1022',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'cta.ended.icon',
            desc: '종료 CTA 좌측 search 아이콘 SVG',
            selector: '.detail-cta svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1021 (<Icon n="search" size={17} color={T.primary}>)',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'cta.ended.background',
            desc: '종료 CTA 배경 투명 (아웃라인)',
            selector: '.detail-cta',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgba(0, 0, 0, 0)',
            proto: "tsx L1020 (background:'transparent')",
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'cta.ended.borderWidth',
            desc: '종료 CTA 테두리 1.5px primary',
            selector: '.detail-cta',
            kind: 'css',
            prop: 'border-top-width',
            expected: '1.5px',
            proto: 'tsx L1020 (border:1.5px solid T.primary)',
            severity: 'P2',
            states: ['auth'],
            // 2026-08-03: CSS 에 border-width:1.5px 를 지정해도 Chromium 이 subpixel 라운딩으로 1px 반환.
            // prototype 도 동일 브라우저 이슈. 소스 스펙 (1.5) 은 유지하되 검사에서는 제외.
            deviation:
                '브라우저 subpixel 라운딩 — Chromium 이 1.5px 지정을 getComputedStyle 에서 1px 로 반환 (prototype 도 동일). CSS 소스는 1.5px 유지, 계약은 이탈로 기록',
        },
        {
            id: 'cta.ended.fontWeight',
            desc: '종료 CTA weight 700',
            selector: '.detail-cta',
            kind: 'css',
            prop: 'font-weight',
            expected: '700',
            proto: 'tsx L1022 (fontWeight:700)',
            severity: 'P2',
            states: ['auth'],
        },

        // ── 종료 상태 이미지 처리 ───────────────────────────────
        {
            id: 'ended.image.filter',
            desc: '종료 프로그램 이미지 grayscale(1) brightness(0.82)',
            selector: '.detail-image img',
            kind: 'css',
            prop: 'filter',
            expected: 'grayscale(1) brightness(0.82)',
            proto: 'tsx L976',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'ended.image.overlay.background',
            desc: '종료 이미지 위 오버레이 rgba(0,0,0,0.3)',
            selector: '.detail-image-overlay',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgba(0, 0, 0, 0.3)',
            proto: 'tsx L978',
            severity: 'P2',
            states: ['auth'],
        },
        {
            id: 'ended.image.chip.text',
            desc: '종료 이미지 중앙 칩 「종료된 프로그램」',
            selector: '.detail-image-overlay-chip',
            kind: 'text',
            expected: '종료된 프로그램',
            proto: 'tsx L978',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'ended.image.chip.background',
            desc: '종료 칩 배경 rgba(120,124,130,0.9)',
            selector: '.detail-image-overlay-chip',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgba(120, 124, 130, 0.9)',
            proto: 'tsx L978',
            severity: 'P2',
            states: ['auth'],
        },

        // ── 지원 대상 섹션 ──────────────────────────────────────
        {
            id: 'divider.height',
            desc: '섹션 구분선 1px',
            selector: '.detail-divider',
            kind: 'box',
            prop: 'height',
            expected: 1,
            proto: 'tsx L1037 (height:1)',
            severity: 'P2',
        },
        {
            id: 'section.title.fontSize',
            desc: '섹션 제목 폰트 20',
            selector: '.detail-section-title',
            kind: 'css',
            prop: 'font-size',
            expected: '20px',
            proto: 'tsx L1038 (fontSize:20)',
            severity: 'P2',
        },
        {
            id: 'section.title.fontWeight',
            desc: '섹션 제목 weight 600',
            selector: '.detail-section-title',
            kind: 'css',
            prop: 'font-weight',
            expected: '600',
            proto: 'tsx L1038 (fontWeight:600)',
            severity: 'P2',
        },
        {
            id: 'req.card.count',
            desc: '지원 대상 카드 3개 (연령·거주지·기타), 2열 그리드',
            selector: '.detail-requirement-card',
            kind: 'count',
            expected: 3,
            proto: 'tsx L1040~1044',
            severity: 'P2',
        },
        {
            id: 'req.grid.gap',
            desc: '지원 대상 그리드 gap 12',
            selector: '.detail-requirement-grid',
            kind: 'css',
            prop: 'column-gap',
            expected: '12px',
            proto: 'tsx L1039 (gap:12)',
            severity: 'P2',
        },
        {
            id: 'req.icon.size',
            desc: '지원 대상 아이콘 박스 36x36 (정보 그리드 34 와 다름)',
            selector: '.detail-requirement-icon',
            kind: 'box',
            prop: 'width',
            expected: 36,
            proto: 'tsx L1046 (width:36)',
            severity: 'P2',
        },
        {
            id: 'req.value.fontSize',
            desc: '지원 대상 값 폰트 14/600',
            selector: '.detail-requirement-value',
            kind: 'css',
            prop: 'font-size',
            expected: '14px',
            proto: 'tsx L1051 (fontSize:14)',
            severity: 'P2',
        },
        {
            id: 'warning.icon.isSvg',
            desc: '지원 대상 경고 아이콘은 lucide bell SVG — 이모지/문자 ⚠ 대체 금지',
            selector: '.detail-warning svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1057 (<Icon n="bell" size={16} color={T.warning}>)',
            severity: 'P1',
        },
        {
            id: 'warning.padding',
            desc: '경고 박스 패딩 12 14',
            selector: '.detail-warning',
            kind: 'css',
            prop: 'padding',
            expected: '12px 14px',
            proto: "tsx L1056 (padding:'12px 14px')",
            severity: 'P2',
        },
        {
            id: 'warning.radius',
            desc: '경고 박스 radius 12',
            selector: '.detail-warning',
            kind: 'css',
            prop: 'border-radius',
            expected: '12px',
            proto: 'tsx L1056 (borderRadius:T.radius)',
            severity: 'P2',
        },
        {
            id: 'warning.text.fontSize',
            desc: '경고 문구 폰트 13',
            selector: '.detail-warning-text',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L1058 (fontSize:13)',
            severity: 'P2',
        },

        // ── 프로그램 설명 ───────────────────────────────────────
        {
            id: 'content.placeholder.height',
            desc: '프로그램 설명 이미지 영역 높이 360',
            selector: '.detail-content-placeholder',
            kind: 'box',
            prop: 'height',
            expected: 360,
            proto: 'tsx L1063 (height:360)',
            severity: 'P2',
        },
        {
            id: 'content.placeholder.img.opacity',
            desc: '설명 영역 배경 이미지 opacity 0.3',
            selector: '.detail-content-placeholder-img',
            kind: 'css',
            prop: 'opacity',
            expected: '0.3',
            proto: 'tsx L1064 (opacity:0.3)',
            severity: 'P2',
        },
        {
            id: 'content.placeholder.text.fontSize',
            desc: '설명 영역 안내 문구 폰트 14',
            selector: '.detail-content-placeholder-text',
            kind: 'css',
            prop: 'font-size',
            expected: '14px',
            proto: 'tsx L1065 (fontSize:14)',
            severity: 'P2',
        },

        // ── 하단 sticky CTA 바 ──────────────────────────────────
        {
            id: 'sticky.exists',
            desc: '하단 고정 CTA 바 존재',
            selector: '.detail-sticky-cta',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1094~1120',
            severity: 'P0',
        },
        {
            id: 'sticky.position',
            desc: '하단 바 position: sticky',
            selector: '.detail-sticky-cta',
            kind: 'css',
            prop: 'position',
            expected: 'sticky',
            proto: "tsx L1095 (position:'sticky', bottom:0)",
            severity: 'P0',
        },
        {
            id: 'sticky.zIndex',
            desc: '하단 바 z-index 20',
            selector: '.detail-sticky-cta',
            kind: 'css',
            prop: 'z-index',
            expected: '20',
            proto: 'tsx L1095 (zIndex:20)',
            severity: 'P2',
        },
        {
            id: 'sticky.background',
            desc: '하단 바 배경 rgba(255,255,255,0.92)',
            selector: '.detail-sticky-cta',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgba(255, 255, 255, 0.92)',
            proto: 'tsx L1095',
            severity: 'P2',
        },
        {
            id: 'sticky.backdropFilter',
            desc: '하단 바 backdrop-filter blur(8px)',
            selector: '.detail-sticky-cta',
            kind: 'css',
            prop: 'backdrop-filter',
            expected: 'blur(8px)',
            proto: 'tsx L1095',
            severity: 'P2',
        },
        {
            id: 'sticky.inner.width',
            desc: '하단 바 내부 폭 1080 — 본문 1000·전역 1440 과 모두 다른 고유 값',
            selector: '.detail-sticky-inner',
            kind: 'box',
            prop: 'width',
            expected: 1080,
            proto: 'tsx L1096 (maxWidth:1080)',
            severity: 'P1',
        },
        {
            id: 'sticky.inner.padding',
            desc: '하단 바 내부 패딩 14 24',
            selector: '.detail-sticky-inner',
            kind: 'css',
            prop: 'padding',
            expected: '14px 24px',
            proto: "tsx L1096 (padding:'14px 24px')",
            severity: 'P2',
        },
        {
            id: 'sticky.inner.gap',
            desc: '하단 바 내부 간격 16',
            selector: '.detail-sticky-inner',
            kind: 'css',
            prop: 'column-gap',
            expected: '16px',
            proto: 'tsx L1096 (gap:16)',
            severity: 'P2',
        },
        {
            id: 'sticky.title.fontSize',
            desc: '하단 바 프로그램명 폰트 15/700',
            selector: '.detail-sticky-title',
            kind: 'css',
            prop: 'font-size',
            expected: '15px',
            proto: 'tsx L1098 (fontSize:15)',
            severity: 'P2',
        },
        {
            id: 'sticky.status.fontSize',
            desc: '하단 바 상태 줄 폰트 12.5/600',
            selector: '.detail-sticky-status',
            kind: 'css',
            prop: 'font-size',
            expected: '12.5px',
            proto: 'tsx L1099 (fontSize:12.5)',
            severity: 'P2',
        },
        {
            id: 'sticky.status.ended.text',
            desc: '하단 바 종료 상태 문구',
            selector: '.detail-sticky-status',
            kind: 'text',
            expected: '종료된 프로그램',
            proto: 'tsx L1099',
            severity: 'P2',
            states: ['auth'],
            deviation:
                '카피는 현행 구현 유지로 확정 (2026-07-28). 현재 상태 배지 라벨(「종료」)을 그대로 노출. ' +
                '다만 모집중일 때 prototype 은 「마감까지 N일 · 27/30명」처럼 D-day·신청 인원을 노출하는데 ' +
                '구현은 상태 라벨(「모집중」)만 노출 — 정보량 차이는 서술 계약 §5 에 별도 기록',
        },
        {
            id: 'sticky.bookmark.size',
            desc: '하단 바 즐겨찾기 버튼 48x48',
            selector: '.detail-sticky-bookmark',
            kind: 'box',
            prop: 'width',
            expected: 48,
            proto: 'tsx L1101 (width:48)',
            severity: 'P2',
        },
        {
            id: 'sticky.bookmark.radius',
            desc: '하단 바 즐겨찾기 버튼 radius 12',
            selector: '.detail-sticky-bookmark',
            kind: 'css',
            prop: 'border-radius',
            expected: '12px',
            proto: 'tsx L1101 (borderRadius:12)',
            severity: 'P2',
        },
        {
            id: 'sticky.bookmark.isSvg',
            desc: '하단 바 즐겨찾기는 star SVG (size 22)',
            selector: '.detail-sticky-bookmark svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1102 (<Icon n={fav?"starFill":"star"} size={22}>)',
            severity: 'P1',
        },
        {
            id: 'sticky.cta.minWidth',
            desc: '하단 바 CTA 최소 폭 200',
            selector: '.detail-sticky-cta-btn',
            kind: 'box',
            prop: 'width',
            expected: 200,
            proto: 'tsx L1114 (minWidth:200)',
            severity: 'P1',
        },
        {
            id: 'sticky.cta.height',
            desc: '하단 바 CTA 높이 48 (본문 CTA 42 와 다름)',
            selector: '.detail-sticky-cta-btn',
            kind: 'box',
            prop: 'height',
            expected: 48,
            proto: 'tsx L1114 (height:48)',
            severity: 'P1',
        },
        {
            id: 'sticky.cta.radius',
            desc: '하단 바 CTA radius 12 (본문 CTA 의 tagR 20 과 다름)',
            selector: '.detail-sticky-cta-btn',
            kind: 'css',
            prop: 'border-radius',
            expected: '12px',
            proto: 'tsx L1114 (borderRadius:12)',
            severity: 'P2',
        },
        {
            id: 'sticky.cta.fontSize',
            desc: '하단 바 CTA 라벨 폰트 16/700',
            selector: '.detail-sticky-cta-btn',
            kind: 'css',
            prop: 'font-size',
            expected: '16px',
            proto: 'tsx L1116 (fontSize:16, fontWeight:700)',
            severity: 'P2',
        },
        {
            id: 'sticky.cta.icon',
            desc: '하단 바 CTA 좌측 아이콘 SVG (모집중 check / 종료 search)',
            selector: '.detail-sticky-cta-btn svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1115 (<Icon n={(full||upcoming)?"bell":"check"} size={19}>)',
            severity: 'P1',
        },
        {
            id: 'sticky.cta.open.text',
            desc: '하단 바 모집중 CTA 라벨 「신청하기」',
            selector: '.detail-sticky-cta-btn',
            kind: 'text',
            expected: '신청하기',
            proto: 'tsx L1116',
            severity: 'P1',
        },
        {
            id: 'sticky.cta.ended.text',
            desc: '하단 바 종료 CTA 라벨 「비슷한 프로그램 보기」',
            selector: '.detail-sticky-cta-btn',
            kind: 'text',
            expected: '비슷한 프로그램 보기',
            proto: 'tsx L1107',
            severity: 'P1',
            states: ['auth'],
        },
        {
            id: 'sticky.cta.ended.icon',
            desc: '하단 바 종료 CTA 좌측 search 아이콘 SVG',
            selector: '.detail-sticky-cta-btn svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L1106 (<Icon n="search" size={18} color={T.primary}>)',
            severity: 'P1',
            states: ['auth'],
        },
    ],
};
