/**
 * 프로그램 목록 화면 (`/programs`) 디자인 계약 — 기계 검사 항목.
 *
 * 추출 기준: docs/00_assets/prototype.tsx L815~944 (ProgramList) / 2026-07-28
 *   보조 참조 — FilterPopChip L697~727 · ProgramCalendar L728~814 ·
 *              CapacityBar L214~249 · DdayChip L250~258 · 디자인 토큰 T L10~21
 * 서술 계약 (레이아웃 축·상태머신·CTA 라우팅·필터 동작·정렬): docs/design-contracts/programs.md
 *
 * 디자인 토큰 (prototype.tsx L10~21):
 *   primary #3F30E9 = rgb(63, 48, 233) / secondary #F97316 / radius 12 / tagR 20
 *   text oklch(0.22 0.051 280) / textSec oklch(0.55 0.034 280) / textTri oklch(0.7 0.02 280)
 *
 * 셀렉터는 전부 현재 템플릿(`program/list.html`, `program/_list-fragment.html`,
 * `fragments/capacity-bar.html`, `fragments/bookmark-button.html`) 과 `static/css/main.css` 에
 * 실재하는 것만 사용한다. prototype 에는 있고 구현에 아예 없는 요소는 `exists: true` / `count: 0`
 * 으로 넣어 "에러" 가 아니라 "갭" 으로 리포트되게 한다.
 */

import type { ScreenContract } from './types';

export const programsContract: ScreenContract = {
    screen: 'programs',
    path: '/programs',
    source: 'prototype.tsx L815~944 (ProgramList), 2026-07-28 추출',
    viewport: { width: 1440, height: 900 },
    checks: [
        // ── 페이지 타이틀 바 ─────────────────────────────────────
        {
            id: 'title.fontSize',
            desc: '페이지 제목 "프로그램" 폰트 28',
            selector: '.page-title-bar h2',
            kind: 'css',
            prop: 'font-size',
            expected: '28px',
            proto: 'tsx L839 (fontSize:28)',
            severity: 'P2',
        },
        {
            id: 'title.fontWeight',
            desc: '페이지 제목 weight 700',
            selector: '.page-title-bar h2',
            kind: 'css',
            prop: 'font-weight',
            expected: '700',
            proto: 'tsx L839 (fontWeight:700)',
            severity: 'P2',
        },
        {
            id: 'titlebar.paddingTop',
            desc: '타이틀 바 상단 패딩 28',
            selector: '.page-title-bar',
            kind: 'css',
            prop: 'padding-top',
            expected: '28px',
            proto: "tsx L838 (padding:'28px 0 24px')",
            severity: 'P2',
        },
        {
            id: 'titlebar.paddingBottom',
            desc: '타이틀 바 하단 패딩 24',
            selector: '.page-title-bar',
            kind: 'css',
            prop: 'padding-bottom',
            expected: '24px',
            proto: "tsx L838 (padding:'28px 0 24px')",
            severity: 'P2',
        },

        // ── 본문 컨테이너 ────────────────────────────────────────
        {
            id: 'layout.width',
            desc: '본문 컨테이너 폭 1160 — 다른 화면(1440)보다 좁다',
            selector: '.programs-layout',
            kind: 'box',
            prop: 'width',
            expected: 1160,
            proto: 'tsx L841 (maxWidth:1160)',
            severity: 'P1',
        },
        {
            id: 'layout.paddingX',
            desc: '본문 컨테이너 좌우 패딩 80',
            selector: '.programs-layout',
            kind: 'css',
            prop: 'padding-left',
            expected: '80px',
            proto: "tsx L841 (padding:'28px 80px 48px')",
            severity: 'P2',
        },
        {
            id: 'layout.paddingTop',
            desc: '본문 컨테이너 상단 패딩 28',
            selector: '.programs-layout',
            kind: 'css',
            prop: 'padding-top',
            expected: '28px',
            proto: "tsx L841 (padding:'28px 80px 48px')",
            severity: 'P2',
        },

        // ── 필터 바 (좌: 상태탭·팝오버칩 / 우: 카운트·정렬·뷰전환) ──
        {
            id: 'filterbar.justify',
            desc: '필터 바 좌우 그룹 양끝 정렬',
            selector: '.filter-bar',
            kind: 'css',
            prop: 'justify-content',
            expected: 'space-between',
            proto: "tsx L844 (justifyContent:'space-between')",
            severity: 'P2',
        },
        {
            id: 'filterbar.marginBottom',
            desc: '필터 바 하단 여백 20',
            selector: '.filter-bar',
            kind: 'css',
            prop: 'margin-bottom',
            expected: '20px',
            proto: 'tsx L844 (marginBottom:20)',
            severity: 'P2',
        },
        {
            id: 'filterleft.gap',
            desc: '좌측 그룹(탭·칩) 간격 8',
            selector: '.filter-left',
            kind: 'css',
            prop: 'column-gap',
            expected: '8px',
            proto: 'tsx L845 (gap:8)',
            severity: 'P2',
        },

        // ── 상태 탭 ──────────────────────────────────────────────
        {
            id: 'tabs.count',
            desc: '상태 탭 4개 (전체·모집중·진행예정·종료)',
            selector: '.status-tab',
            kind: 'count',
            expected: 4,
            proto: "tsx L847 (['전체','모집중','진행예정','종료'])",
            severity: 'P1',
        },
        {
            id: 'tabs.gap',
            desc: '상태 탭 간격 6',
            selector: '.status-tabs',
            kind: 'css',
            prop: 'column-gap',
            expected: '6px',
            proto: 'tsx L846 (gap:6)',
            severity: 'P2',
        },
        {
            id: 'tab.paddingX',
            desc: '상태 탭 좌우 패딩 16',
            selector: '.status-tab',
            kind: 'css',
            prop: 'padding-left',
            expected: '16px',
            proto: "tsx L848 (padding:'8px 16px')",
            severity: 'P2',
        },
        {
            id: 'tab.radius',
            desc: '상태 탭 pill radius 20 (tagR)',
            selector: '.status-tab',
            kind: 'css',
            prop: 'border-radius',
            expected: '20px',
            proto: 'tsx L848 (borderRadius:T.tagR)',
            severity: 'P2',
        },
        {
            id: 'tab.fontSize',
            desc: '상태 탭 폰트 13',
            selector: '.status-tab',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L848 (fontSize:13)',
            severity: 'P2',
        },
        {
            id: 'tab.active.bg',
            desc: '선택 탭 배경 primary',
            selector: '.status-tab.active',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgb(63, 48, 233)',
            proto: 'tsx L848 (background: active ? T.primary)',
            severity: 'P2',
        },
        {
            id: 'divider.height',
            desc: '탭·필터 칩 사이 구분선 높이 20',
            selector: '.filter-divider',
            kind: 'box',
            prop: 'height',
            expected: 20,
            proto: 'tsx L853 (width:1, height:20)',
            severity: 'P2',
        },

        // ── 필터 팝오버 칩 (지역 / 청년센터) ─────────────────────
        {
            id: 'popchip.count',
            desc: '팝오버 필터 칩 2개 (지역·청년센터)',
            selector: '.filter-pop-chip',
            kind: 'count',
            expected: 2,
            proto: 'tsx L854~855 (FilterPopChip 지역/청년센터)',
            severity: 'P1',
        },
        {
            id: 'popchip.radius',
            desc: '필터 칩 pill radius 20 (tagR)',
            selector: '.filter-pop-chip',
            kind: 'css',
            prop: 'border-radius',
            expected: '20px',
            proto: 'tsx L702 (borderRadius:T.tagR)',
            severity: 'P2',
        },
        {
            id: 'popchip.paddingX',
            desc: '필터 칩 좌우 패딩 14',
            selector: '.filter-pop-chip',
            kind: 'css',
            prop: 'padding-left',
            expected: '14px',
            proto: "tsx L702 (padding:'8px 14px')",
            severity: 'P2',
        },
        {
            id: 'popchip.fontSize',
            desc: '필터 칩 폰트 13',
            selector: '.filter-pop-chip',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L703 (fontSize:13)',
            severity: 'P2',
        },
        {
            id: 'popchip.chevron',
            desc: '필터 칩 우측 chevD 아이콘 (SVG)',
            selector: '.filter-pop-chip svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L704 (<Icon n="chevD" size={13}>)',
            severity: 'P2',
        },
        {
            id: 'popover.width',
            desc: '드롭다운 폭 260',
            selector: '.filter-popover',
            kind: 'css',
            prop: 'width',
            expected: '260px',
            proto: 'tsx L708 (width:260)',
            severity: 'P2',
        },
        {
            id: 'popover.padding',
            desc: '드롭다운 패딩 14',
            selector: '.filter-popover',
            kind: 'css',
            prop: 'padding-top',
            expected: '14px',
            proto: 'tsx L708 (padding:14)',
            severity: 'P2',
        },
        {
            id: 'popover.options.maxHeight',
            desc: '드롭다운 옵션 목록 최대 높이 220 (초과 시 스크롤)',
            selector: '.filter-popover-options',
            kind: 'css',
            prop: 'max-height',
            expected: '220px',
            proto: "tsx L713 (maxHeight:220, overflowY:'auto')",
            severity: 'P2',
        },
        {
            id: 'popover.noHeader',
            desc: '드롭다운에 제목·닫기(×) 헤더가 없다 — 컨테이너 안은 검색 행 + 옵션 목록뿐',
            selector: '.filter-popover-header',
            kind: 'exists',
            expected: false,
            proto: 'tsx L708~723 (padding:14 컨테이너 직계 자식은 검색 div + 옵션 div 2개뿐)',
            severity: 'P2',
        },
        {
            id: 'popover.noApplyFooter',
            desc: '드롭다운은 체크 즉시 반영 — 취소/적용 버튼 푸터가 없다',
            selector: '.filter-popover-footer',
            kind: 'exists',
            expected: false,
            proto: 'tsx L715 (label onClick 이 곧바로 setSel — 확인 단계 없음)',
            severity: 'P2',
        },

        // ── 필터 바 우측 그룹 ────────────────────────────────────
        {
            id: 'filterright.gap',
            desc: '우측 그룹(카운트·정렬·뷰전환) 간격 14',
            selector: '.filter-right',
            kind: 'css',
            prop: 'column-gap',
            expected: '14px',
            proto: 'tsx L858 (gap:14)',
            severity: 'P2',
        },
        {
            id: 'resultcount.placement',
            desc: '결과 카운트("전체 N건")는 필터 바 우측 그룹 안, 정렬 옵션 왼쪽에 위치',
            selector: '.filter-right .result-count',
            kind: 'exists',
            expected: true,
            proto: 'tsx L858~860 (우측 flex 그룹 첫 요소)',
            severity: 'P1',
        },

        // ── 정렬 ─────────────────────────────────────────────────
        {
            id: 'sort.count',
            desc: '정렬 옵션 3개',
            selector: '.sort-link',
            kind: 'count',
            expected: 3,
            proto: "tsx L862 (['기본','마감임박','인기'])",
            severity: 'P1',
        },
        {
            id: 'sort.first.text',
            desc: '첫 정렬 옵션은 "기본순" (정렬 미적용 = 원래 순서)',
            selector: '.sort-link',
            kind: 'text',
            expected: '기본순',
            proto: "tsx L862 (['기본','기본순'])",
            severity: 'P1',
        },
        {
            id: 'sort.gap',
            desc: '정렬 옵션 간격 2',
            selector: '.sort-options',
            kind: 'css',
            prop: 'column-gap',
            expected: '2px',
            proto: 'tsx L861 (gap:2)',
            severity: 'P2',
        },
        {
            id: 'sort.fontSize',
            desc: '정렬 옵션 폰트 13',
            selector: '.sort-link',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L865 (fontSize:13)',
            severity: 'P2',
        },
        {
            id: 'sort.active.color',
            desc: '선택된 정렬 옵션 색 primary',
            selector: '.sort-link.active',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(63, 48, 233)',
            proto: 'tsx L865 (color: sort===k ? T.primary)',
            severity: 'P2',
        },

        // ── 뷰 전환 (목록 / 캘린더) ──────────────────────────────
        {
            id: 'viewtoggle.count',
            desc: '뷰 전환 버튼 2개 (목록·캘린더)',
            selector: '.view-toggle-btn',
            kind: 'count',
            expected: 2,
            proto: "tsx L871 ([['grid','목록'],['calendar','캘린더']])",
            severity: 'P1',
        },
        {
            id: 'viewtoggle.enabled',
            desc: '두 뷰 모두 전환 가능 — 비활성 버튼이 없어야 함',
            selector: '.view-toggle-btn[disabled]',
            kind: 'count',
            expected: 0,
            proto: 'tsx L872 (onClick={()=>setView(v)} — 두 항목 모두 활성)',
            severity: 'P1',
        },
        {
            id: 'viewtoggle.icon',
            desc: '뷰 전환 버튼에 grid/calendar SVG 아이콘 (텍스트 전용 아님)',
            selector: '.view-toggle-btn svg',
            kind: 'exists',
            expected: true,
            proto: 'tsx L873 (<Icon n={v} size={14}>)',
            severity: 'P1',
        },
        {
            id: 'viewtoggle.paddingX',
            desc: '뷰 전환 버튼 좌우 패딩 14',
            selector: '.view-toggle-btn',
            kind: 'css',
            prop: 'padding-left',
            expected: '14px',
            proto: "tsx L872 (padding:'7px 14px')",
            severity: 'P2',
        },
        {
            id: 'viewtoggle.fontSize',
            desc: '뷰 전환 버튼 라벨 폰트 12.5',
            selector: '.view-toggle-btn',
            kind: 'css',
            prop: 'font-size',
            expected: '12.5px',
            proto: 'tsx L874 (fontSize:12.5)',
            severity: 'P2',
        },
        {
            id: 'viewtoggle.radius',
            desc: '뷰 전환 그룹 radius 8',
            selector: '.view-toggle',
            kind: 'css',
            prop: 'border-radius',
            expected: '8px',
            proto: 'tsx L870 (borderRadius:8)',
            severity: 'P2',
        },

        // ── 카드 그리드 ──────────────────────────────────────────
        {
            id: 'grid.gap',
            desc: '카드 그리드 gap 16 (3열)',
            selector: '.program-grid',
            kind: 'css',
            prop: 'column-gap',
            expected: '16px',
            proto: "tsx L882 (gridTemplateColumns:'repeat(3,1fr)', gap:16)",
            severity: 'P2',
        },
        {
            id: 'grid.excludeEnded',
            desc: '"전체" 탭은 종료 프로그램을 제외한다 — 종료 카드는 "종료" 탭에서만 노출',
            selector: '.program-card--ended',
            kind: 'count',
            expected: 0,
            proto: "tsx L825 (active==='전체' ? p.status!=='종료' : ...)",
            severity: 'P1',
        },
        {
            id: 'card.radius',
            desc: '카드 radius 12',
            selector: '.program-card',
            kind: 'css',
            prop: 'border-radius',
            expected: '12px',
            proto: 'tsx L893 (borderRadius:T.radius)',
            severity: 'P2',
        },
        {
            id: 'card.image.height',
            desc: '카드 이미지 높이 160',
            selector: '.program-card-image',
            kind: 'box',
            prop: 'height',
            expected: 160,
            proto: 'tsx L894 (height:160)',
            severity: 'P2',
        },

        // ── D-day 칩 ─────────────────────────────────────────────
        {
            id: 'dday.top',
            desc: 'D-day 칩 이미지 좌상단 10,10',
            selector: '.dday-chip',
            kind: 'css',
            prop: 'top',
            expected: '10px',
            proto: 'tsx L896 (top:10, left:10)',
            severity: 'P2',
        },
        {
            id: 'dday.radius',
            desc: 'D-day 칩 pill radius 20 (tagR)',
            selector: '.dday-chip',
            kind: 'css',
            prop: 'border-radius',
            expected: '20px',
            proto: 'tsx L257 (borderRadius:T.tagR)',
            severity: 'P2',
        },
        {
            id: 'dday.fontSize',
            desc: 'D-day 칩 폰트 11 / weight 700',
            selector: '.dday-chip',
            kind: 'css',
            prop: 'font-size',
            expected: '11px',
            proto: 'tsx L257 (fontSize:11, fontWeight:700)',
            severity: 'P2',
        },
        {
            id: 'dday.bg',
            desc: 'D-day 칩 기본 배경 rgba(0,0,0,0.55)',
            selector: '.dday-chip',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgba(0, 0, 0, 0.55)',
            proto: "tsx L257 (background:'rgba(0,0,0,0.55)')",
            severity: 'P2',
        },

        // ── 즐겨찾기 별 ──────────────────────────────────────────
        {
            id: 'bookmark.exists',
            desc: '카드 우상단 즐겨찾기 별',
            selector: '.card-bookmark-btn',
            kind: 'exists',
            expected: true,
            proto: 'tsx L897~899 (Icon star/starFill)',
            severity: 'P1',
        },
        {
            id: 'bookmark.top',
            desc: '즐겨찾기 별 우상단 10,10',
            selector: '.card-bookmark-btn',
            kind: 'css',
            prop: 'top',
            expected: '10px',
            proto: 'tsx L897 (top:10, right:10)',
            severity: 'P2',
        },
        {
            id: 'bookmark.icon.size',
            desc: '즐겨찾기 별 아이콘 20x20',
            selector: '.card-bookmark-btn svg',
            kind: 'box',
            prop: 'width',
            expected: 20,
            tolerance: 0,
            proto: 'tsx L898 (size={20})',
            severity: 'P2',
        },
        {
            id: 'bookmark.color',
            desc: '미즐겨찾기 별 색 rgba(255,255,255,0.85)',
            selector: '.card-bookmark-btn',
            kind: 'css',
            prop: 'color',
            expected: 'rgba(255, 255, 255, 0.85)',
            proto: "tsx L898 (color:'rgba(255,255,255,0.85)')",
            severity: 'P2',
        },
        {
            id: 'bookmark.auth.isButton',
            desc: '로그인 상태에서는 별이 즉시 토글되는 버튼 (링크 이동 아님)',
            selector: 'button.card-bookmark-btn',
            kind: 'exists',
            expected: true,
            proto: 'tsx L897 (onClick: isLoggedIn ? setFav(...) : onLoginClick())',
            severity: 'P2',
            states: ['auth'],
        },

        // ── 카드 본문 ────────────────────────────────────────────
        {
            id: 'cardbody.paddingTop',
            desc: '카드 본문 상단 패딩 12',
            selector: '.program-card-body',
            kind: 'css',
            prop: 'padding-top',
            expected: '12px',
            proto: "tsx L901 (padding:'12px 14px 14px')",
            severity: 'P2',
        },
        {
            id: 'cardbody.paddingX',
            desc: '카드 본문 좌우 패딩 14',
            selector: '.program-card-body',
            kind: 'css',
            prop: 'padding-left',
            expected: '14px',
            proto: "tsx L901 (padding:'12px 14px 14px')",
            severity: 'P2',
        },
        {
            id: 'card.title.fontSize',
            desc: '카드 제목 폰트 15 / weight 600',
            selector: '.program-card-title',
            kind: 'css',
            prop: 'font-size',
            expected: '15px',
            proto: 'tsx L902 (fontSize:15, fontWeight:600)',
            severity: 'P2',
        },
        {
            id: 'card.title.marginBottom',
            desc: '카드 제목 하단 여백 3',
            selector: '.program-card-title',
            kind: 'css',
            prop: 'margin-bottom',
            expected: '3px',
            proto: 'tsx L902 (marginBottom:3)',
            severity: 'P2',
        },
        {
            id: 'card.org.fontSize',
            desc: '센터명 폰트 12',
            selector: '.program-card-org',
            kind: 'css',
            prop: 'font-size',
            expected: '12px',
            proto: 'tsx L903 (fontSize:12)',
            severity: 'P2',
        },
        {
            id: 'card.org.marginBottom',
            desc: '센터명 하단 여백 2',
            selector: '.program-card-org',
            kind: 'css',
            prop: 'margin-bottom',
            expected: '2px',
            proto: 'tsx L903 (marginBottom:2)',
            severity: 'P2',
        },
        {
            id: 'card.date.marginBottom',
            desc: '기간 텍스트 하단 여백 10',
            selector: '.program-card-date',
            kind: 'css',
            prop: 'margin-bottom',
            expected: '10px',
            proto: 'tsx L904 (marginBottom:10)',
            severity: 'P2',
        },

        // ── CapacityBar ──────────────────────────────────────────
        {
            id: 'capacity.wrap.marginBottom',
            desc: 'CapacityBar 블록 하단 여백 10',
            selector: '.capacity-bar-wrap',
            kind: 'css',
            prop: 'margin-bottom',
            expected: '10px',
            proto: 'tsx L905 (marginBottom:10)',
            severity: 'P2',
        },
        {
            id: 'capacity.bar.height',
            desc: '진행 바 높이 6',
            selector: '.capacity-bar',
            kind: 'box',
            prop: 'height',
            expected: 6,
            proto: 'tsx L244 (height:6)',
            severity: 'P2',
        },
        {
            id: 'capacity.label.fontSize',
            desc: '정원 라벨 폰트 12 / weight 600',
            selector: '.capacity-bar-primary',
            kind: 'css',
            prop: 'font-size',
            expected: '12px',
            proto: 'tsx L241 (fontSize:12, fontWeight:600)',
            severity: 'P2',
        },
        {
            id: 'capacity.pct.fontSize',
            desc: '우측 퍼센트 폰트 11',
            selector: '.capacity-bar-secondary',
            kind: 'css',
            prop: 'font-size',
            expected: '11px',
            proto: 'tsx L242 (fontSize:11)',
            severity: 'P2',
        },
        {
            id: 'capacity.label.marginBottom',
            desc: '정원 라벨과 바 사이 5',
            selector: '.capacity-bar-label',
            kind: 'css',
            prop: 'margin-bottom',
            expected: '5px',
            proto: 'tsx L240 (marginBottom:5)',
            severity: 'P2',
        },

        // ── 카드 CTA ─────────────────────────────────────────────
        {
            id: 'cta.height',
            desc: '카드 CTA 높이 34',
            selector: '.card-action-btn',
            kind: 'box',
            prop: 'height',
            expected: 34,
            proto: 'tsx L911 (height:34)',
            severity: 'P2',
        },
        {
            id: 'cta.radius',
            desc: '카드 CTA pill radius 20 (tagR) — 사각 버튼 아님',
            selector: '.card-action-btn',
            kind: 'css',
            prop: 'border-radius',
            expected: '20px',
            proto: 'tsx L911 (borderRadius:T.tagR)',
            severity: 'P1',
        },
        {
            id: 'cta.fontSize',
            desc: '카드 CTA 폰트 13 / weight 600',
            selector: '.card-action-btn',
            kind: 'css',
            prop: 'font-size',
            expected: '13px',
            proto: 'tsx L911 (fontSize:13, fontWeight:600)',
            severity: 'P2',
        },
        {
            id: 'cta.icon.size',
            desc: 'CTA 아이콘 15x15 (check / bell)',
            selector: '.card-action-btn svg',
            kind: 'box',
            prop: 'width',
            expected: 15,
            tolerance: 0,
            proto: 'tsx L912 (<Icon size={15}>)',
            severity: 'P2',
        },
        {
            id: 'cta.primary.color',
            desc: '모집중 CTA(신청하기) 색 primary',
            selector: '.card-action-btn--primary',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(63, 48, 233)',
            proto: 'tsx L911 (color: T.primary)',
            severity: 'P2',
        },
        {
            id: 'cta.upcoming.color',
            desc: '진행예정 CTA(오픈 알림 받기) 색 secondary #F97316',
            selector: '.card-action-btn--secondary',
            kind: 'css',
            prop: 'color',
            expected: 'rgb(249, 115, 22)',
            proto: 'tsx L911~913 (c.upcoming ? T.secondary)',
            severity: 'P2',
        },

        // ── 페이지네이션 ─────────────────────────────────────────
        {
            id: 'pagination.marginTop',
            desc: '페이지네이션 상단 여백 28',
            selector: '.pagination',
            kind: 'css',
            prop: 'margin-top',
            expected: '28px',
            proto: 'tsx L922 (marginTop:28)',
            severity: 'P2',
        },
        {
            id: 'pagination.gap',
            desc: '페이지 버튼 간격 4',
            selector: '.pagination',
            kind: 'css',
            prop: 'column-gap',
            expected: '4px',
            proto: 'tsx L922 (gap:4)',
            severity: 'P2',
        },
        {
            id: 'page.size',
            desc: '페이지 버튼 32x32',
            selector: '.page-link',
            kind: 'box',
            prop: 'width',
            expected: 32,
            proto: 'tsx L923 (width:32, height:32)',
            severity: 'P2',
        },
        {
            id: 'page.radius',
            desc: '페이지 버튼 radius 7',
            selector: '.page-link',
            kind: 'css',
            prop: 'border-radius',
            expected: '7px',
            proto: 'tsx L923 (borderRadius:7)',
            severity: 'P2',
        },
        {
            id: 'page.active.bg',
            desc: '현재 페이지 버튼 배경 primary / weight 700',
            selector: '.page-link.active',
            kind: 'css',
            prop: 'background-color',
            expected: 'rgb(63, 48, 233)',
            proto: 'tsx L927~928 (background: n===1 ? T.primary, fontWeight:700)',
            severity: 'P2',
        },

        // ── 빈 상태 (카피 — 의도적 이탈로 검사 제외) ─────────────
        {
            id: 'empty.title.text',
            desc: '빈 상태 제목 카피',
            selector: '.empty-state-rich .empty-title',
            kind: 'text',
            expected: '조건에 맞는 프로그램이 없어요',
            proto: 'tsx L888',
            severity: 'P1',
            deviation:
                '구현 카피 유지 결정 (2026-07-28, 홈 hero 카피와 동일 건). 현행 "조건에 맞는 프로그램이 아직 없어요" 유지',
        },
        {
            id: 'empty.sub.text',
            desc: '빈 상태 보조 카피',
            selector: '.empty-state-rich .empty-sub',
            kind: 'text',
            expected: '필터를 바꾸거나 초기화해 보세요',
            proto: 'tsx L889',
            severity: 'P1',
            deviation:
                'empty.title.text 와 동일 사유 (2026-07-28). 현행 "선택하신 필터를 줄여보거나, 다른 지역도 살펴보시겠어요?" 유지',
        },
    ],
};
