--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: application; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application (
    applied_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    processed_at timestamp(6) without time zone,
    processed_by bigint,
    program_id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    cancel_reason character varying(200),
    reject_reason character varying(500),
    apply_reason oid,
    CONSTRAINT application_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: application_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookmark; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmark (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    program_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: bookmark_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookmark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: center; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.center (
    holiday_closed boolean,
    is_active boolean NOT NULL,
    is_featured boolean NOT NULL,
    latitude numeric(10,7),
    longitude numeric(10,7),
    saturday_close time(0) without time zone,
    saturday_open time(0) without time zone,
    sunday_close time(0) without time zone,
    sunday_open time(0) without time zone,
    weekday_close time(0) without time zone,
    weekday_open time(0) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    phone character varying(20),
    region character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    operating_hours character varying(100),
    address character varying(255)
);


--
-- Name: center_content; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.center_content (
    center_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    description character varying(500),
    image_url character varying(500)
);


--
-- Name: center_content_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.center_content ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.center_content_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: center_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.center ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.center_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notice (
    is_pinned boolean NOT NULL,
    view_count integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    category character varying(20) NOT NULL,
    image_url character varying(500),
    title character varying(255) NOT NULL,
    content oid NOT NULL,
    CONSTRAINT notice_category_check CHECK (((category)::text = ANY ((ARRAY['EVENT'::character varying, 'NOTICE'::character varying, 'OPERATION'::character varying, 'ETC'::character varying])::text[])))
);


--
-- Name: notice_attachment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notice_attachment (
    sort_order integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    file_size bigint NOT NULL,
    id bigint NOT NULL,
    notice_id bigint NOT NULL,
    content_type character varying(100),
    file_name character varying(255) NOT NULL,
    stored_name character varying(255)
);


--
-- Name: notice_attachment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notice_attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notice_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification (
    is_read boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    type character varying(30) NOT NULL,
    link character varying(500),
    message character varying(500) NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY ((ARRAY['APPLICATION_APPROVED'::character varying, 'APPLICATION_REJECTED'::character varying, 'APPLICATION_CANCELLED'::character varying, 'WAITLIST_PROMOTED'::character varying, 'PROGRAM_DEADLINE_NEAR'::character varying, 'WELCOME'::character varying])::text[])))
);


--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persistent_logins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.persistent_logins (
    last_used timestamp(6) without time zone NOT NULL,
    series character varying(64) NOT NULL,
    token character varying(64) NOT NULL,
    username character varying(64) NOT NULL
);


--
-- Name: phone_verifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.phone_verifications (
    attempts integer NOT NULL,
    verified boolean NOT NULL,
    code character varying(6) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_sent_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    verified_at timestamp(6) without time zone,
    phone character varying(20) NOT NULL
);


--
-- Name: phone_verifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.phone_verifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.phone_verifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: program; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.program (
    capacity integer,
    end_date date,
    is_active boolean NOT NULL,
    start_date date,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    category character varying(50),
    region character varying(50),
    eligibility_age character varying(100),
    eligibility_region character varying(100),
    organization character varying(100) NOT NULL,
    eligibility_etc character varying(200),
    apply_url character varying(500),
    image_url character varying(500),
    title character varying(255) NOT NULL,
    content oid NOT NULL
);


--
-- Name: program_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.program ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.program_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: region; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.region (
    is_featured boolean NOT NULL,
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: region_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.region ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.region_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: site_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.site_image (
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    id bigint NOT NULL,
    caption character varying(100),
    slot character varying(100) NOT NULL,
    image_url character varying(500) NOT NULL
);


--
-- Name: site_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.site_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.site_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_interest_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_interest_category (
    user_id bigint NOT NULL,
    category character varying(50)
);


--
-- Name: user_interest_region; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_interest_region (
    user_id bigint NOT NULL,
    region_name character varying(50)
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    birth_date date,
    notify_email boolean NOT NULL,
    notify_kakao boolean NOT NULL,
    notify_new_program_news boolean DEFAULT false NOT NULL,
    notify_remind_d1 boolean DEFAULT true NOT NULL,
    notify_sms boolean NOT NULL,
    notify_waitlist_empty boolean DEFAULT true NOT NULL,
    phone_verified boolean DEFAULT false NOT NULL,
    center_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    gender character varying(10),
    zipcode character varying(10),
    phone character varying(20),
    role character varying(20) NOT NULL,
    center_scope character varying(50),
    name character varying(50) NOT NULL,
    email character varying(191) NOT NULL,
    address character varying(255),
    address_detail character varying(255),
    password character varying(255),
    CONSTRAINT users_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'CENTER_ADMIN'::character varying, 'SYSTEM_ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application application_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT application_pkey PRIMARY KEY (id);


--
-- Name: bookmark bookmark_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmark
    ADD CONSTRAINT bookmark_pkey PRIMARY KEY (id);


--
-- Name: center_content center_content_center_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.center_content
    ADD CONSTRAINT center_content_center_id_key UNIQUE (center_id);


--
-- Name: center_content center_content_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.center_content
    ADD CONSTRAINT center_content_pkey PRIMARY KEY (id);


--
-- Name: center center_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.center
    ADD CONSTRAINT center_pkey PRIMARY KEY (id);


--
-- Name: notice_attachment notice_attachment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_attachment
    ADD CONSTRAINT notice_attachment_pkey PRIMARY KEY (id);


--
-- Name: notice notice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice
    ADD CONSTRAINT notice_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: persistent_logins persistent_logins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persistent_logins
    ADD CONSTRAINT persistent_logins_pkey PRIMARY KEY (series);


--
-- Name: phone_verifications phone_verifications_phone_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phone_verifications
    ADD CONSTRAINT phone_verifications_phone_key UNIQUE (phone);


--
-- Name: phone_verifications phone_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phone_verifications
    ADD CONSTRAINT phone_verifications_pkey PRIMARY KEY (id);


--
-- Name: program program_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program
    ADD CONSTRAINT program_pkey PRIMARY KEY (id);


--
-- Name: region region_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.region
    ADD CONSTRAINT region_name_key UNIQUE (name);


--
-- Name: region region_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.region
    ADD CONSTRAINT region_pkey PRIMARY KEY (id);


--
-- Name: site_image site_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.site_image
    ADD CONSTRAINT site_image_pkey PRIMARY KEY (id);


--
-- Name: application uk_application_user_program; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT uk_application_user_program UNIQUE (user_id, program_id);


--
-- Name: bookmark uk_bookmark_user_program; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmark
    ADD CONSTRAINT uk_bookmark_user_program UNIQUE (user_id, program_id);


--
-- Name: user_interest_category user_interest_category_user_id_category_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_interest_category
    ADD CONSTRAINT user_interest_category_user_id_category_key UNIQUE (user_id, category);


--
-- Name: user_interest_region user_interest_region_user_id_region_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_interest_region
    ADD CONSTRAINT user_interest_region_user_id_region_name_key UNIQUE (user_id, region_name);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_notification_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notification_user_created ON public.notification USING btree (user_id, created_at DESC);


--
-- Name: idx_notification_user_read; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notification_user_read ON public.notification USING btree (user_id, is_read);


--
-- Name: users fk1e6g0g0em2d4heu43rt5lvhrk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk1e6g0g0em2d4heu43rt5lvhrk FOREIGN KEY (center_id) REFERENCES public.center(id);


--
-- Name: application fk4d5qw50go2f7oobfpyq4feh4l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT fk4d5qw50go2f7oobfpyq4feh4l FOREIGN KEY (program_id) REFERENCES public.program(id);


--
-- Name: user_interest_category fk6gb21n38rr7r9nh356uqijex; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_interest_category
    ADD CONSTRAINT fk6gb21n38rr7r9nh356uqijex FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: application fkawte0mbtubellxed1dvpoxhdj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT fkawte0mbtubellxed1dvpoxhdj FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_interest_region fkefulw2akf4gnp0o8ttjh550gy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_interest_region
    ADD CONSTRAINT fkefulw2akf4gnp0o8ttjh550gy FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: center_content fkfjuaglfjptel0m3e8sowjele0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.center_content
    ADD CONSTRAINT fkfjuaglfjptel0m3e8sowjele0 FOREIGN KEY (center_id) REFERENCES public.center(id);


--
-- Name: application fkij8xodlgj0fp2qignjhlblhhi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT fkij8xodlgj0fp2qignjhlblhhi FOREIGN KEY (processed_by) REFERENCES public.users(id);


--
-- Name: notice_attachment fkm1x66jg7f8x9mitn5s2ickp72; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_attachment
    ADD CONSTRAINT fkm1x66jg7f8x9mitn5s2ickp72 FOREIGN KEY (notice_id) REFERENCES public.notice(id);


--
-- Name: bookmark fknb7rhbywasmd7il7lhi0frve2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmark
    ADD CONSTRAINT fknb7rhbywasmd7il7lhi0frve2 FOREIGN KEY (program_id) REFERENCES public.program(id);


--
-- Name: notification fknk4ftb5am9ubmkv1661h15ds9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fknk4ftb5am9ubmkv1661h15ds9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bookmark fko4vbqvq5trl11d85bqu5kl870; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmark
    ADD CONSTRAINT fko4vbqvq5trl11d85bqu5kl870 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--


