-- F-signup-terms-agreement: 약관 정의(terms) + 동의 이력(user_agreements) 신설.
--
-- 배경: 회원가입 시 termsAgreed/privacyAgreed 는 검증만 하고 폐기되어 "누가·언제·어떤 버전에" 동의했는지
-- 시스템에 남지 않는 실질적 결함. 분쟁·감사·재동의 판정 근거를 위해 엔티티화한다.
--
-- 규칙:
--   - user_agreements 는 이력이므로 (user_id, term_id) UNIQUE 를 걸지 않는다. UPDATE 없이 INSERT 만.
--   - agreed_version 은 동의 당시 Term.version 스냅샷. 개정 후 재동의 필요 판정에 사용.
--   - is_active=false 인 약관도 과거 이력은 보존.
--
-- 한 번 머지된 V 파일은 수정 금지 (CLAUDE.md DB 규칙).

CREATE TABLE terms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL,
    title varchar(100) NOT NULL,
    content_path varchar(200) NOT NULL,
    required boolean NOT NULL,
    version integer NOT NULL,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_terms_code UNIQUE (code)
);

CREATE TABLE user_agreements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    term_id bigint NOT NULL,
    agreed_version integer NOT NULL,
    agreed boolean NOT NULL,
    agreed_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT fk_user_agreements_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_agreements_term FOREIGN KEY (term_id) REFERENCES terms(id)
);

CREATE INDEX idx_user_agreements_user_term ON user_agreements(user_id, term_id);
