-- F-notice-attachment: 공지사항 첨부파일 실 바이트 저장.
--
-- notice_attachment 테이블은 F0g 에서 Hibernate ddl-auto=update 로 자동 생성되었으나 V 파일 등록 누락.
-- V4 에서 정식 등록 + data 컬럼(byte[] LOB) 추가를 한 번에 처리.
--
-- IF NOT EXISTS 로 idempotent — 이미 dev/e2e 환경에서 생성된 테이블·컬럼은 skip.
-- Supabase(V1 baseline 스킵) 에서는 신규 생성.
--
-- 학습 단계 정책: 데이터는 DB oid(bytea) 로 저장. 배포 준비 시 Supabase Storage 이관 예정.
-- 상한 5MB, 허용 확장자(pdf/hwp/docx/xlsx) 는 NoticeService 정책 상수에서 방어.

CREATE TABLE IF NOT EXISTS notice_attachment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id bigint NOT NULL,
    file_name varchar(255) NOT NULL,
    stored_name varchar(255),
    file_size bigint NOT NULL,
    content_type varchar(100),
    sort_order integer NOT NULL,
    data bytea,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT fk_notice_attachment_notice FOREIGN KEY (notice_id) REFERENCES notice(id)
);

-- Hibernate 가 자동 생성한 테이블에는 data 컬럼이 없을 수 있으므로 명시 추가
ALTER TABLE notice_attachment ADD COLUMN IF NOT EXISTS data bytea;

CREATE INDEX IF NOT EXISTS idx_notice_attachment_notice ON notice_attachment(notice_id);
